## Chapter 6.1 {.unnumbered}

The third victim of U.S. aggression and savagery in Indochina, Cambodia, falls into a different category than postwar Vietnam and Laos.[^ch06-fn001] While the Western propaganda system has selected and modified information about Vietnam to convey the required image of a country suffering under Communist tyranny—the sole source of its current problems—it has been unable to conjure up the bloodbath that was confidently predicted (Laos, as usual, is rarely noticed at all). In fact, by historical standards, the treatment of collaborators in postwar Vietnam has been relatively mild, as the precedents reviewed indicate, though the provocation for merciless revenge was incomparably greater than in the instances we surveyed. But in the case of Cambodia, there is no difficulty in documenting major atrocities and oppression, primarily from the reports of refugees, since Cambodia has been almost entirely closed to the West since the war's end.




One might imagine that in the United States, which bears a major responsibility for what François Ponchaud calls "the calvary of a people,"[^ch06-fn002] reporting and discussion would be tinged with guilt and regret. That has rarely been the case, however. The U.S. role and responsibility have been quickly forgotten or even explicitly denied as the mills of the propaganda machine grind away. From the spectrum of informed opinion, only the most extreme condemnations have been selected, magnified, distorted, and hammered into popular consciousness through endless repetition. Questions that are obviously crucial even apart from the legacy of the war—for example, the sources of the policies of the postwar Cambodian regime in historical experience, traditional culture, Khmer nationalism, or internal social conflict—have been passed by in silence as the propaganda machine gravitates to the evils of a competitive socioeconomic system so as to establish its basic principle: that "liberation" by "Marxists" is the worst fate that can befall any people under Western dominance.



The record of atrocities in Cambodia is substantial and often gruesome, but it has by no means satisfied the requirements of Western propagandists, who must labor to shift the blame for the torment of Indochina to the victims of France and the United States. Consequently, there has been extensive fabrication of evidence, a tide that is not stemmed even by repeated exposure. Furthermore, more tempered and cautious assessments are given little notice, as is evidence that runs contrary to the chorus of denunciation that has dominated the Western media. The coverage of real and fabricated atrocities in Cambodia also stands in dramatic contrast to the silence with regard to atrocities comparable in scale within U.S. domains—Timor, for example. This coverage has conferred on that land of much suffering the distinction of being perhaps the most extensively reported Third World country in U.S. journalism. At the same time, propagandists in the press and elsewhere, recognizing a good thing when they see it, like to pretend that their lone and courageous voice of protest can barely be heard, or alternatively, that controversy is raging about events in postwar Cambodia.[^ch06-fn003]


Critics of U.S. violence find themselves in a curious position in this connection. Generally ignored by the press, they find that in this case their comment is eagerly sought out in the hope that they will deny atrocity reports, so that this denial can be featured as "proof" that inveterate apologists for Communism will never learn and never cease their sleazy efforts, which create such problems for the honorable seekers after truth who must somehow penetrate the barriers erected by those who "defend Cambodia."[^ch06-fn004] When no real examples can be found, the Free Press resorts to the familiar device of invention; the alleged views of critics of the propaganda barrage who do exist are known primarily through ritual denunciation rather than direct exposure. Or there are somber references to unnamed people who "make use of the deaths of millions of Khmers to defend [their] own theories or projects for society."[^ch06-fn005]






Another common device is to thunder that the doves "had better explain" why there has been a bloodbath,[^ch06-fn006] or "concede" that their "support for the Communists"—the standard term for opposition to U.S. subversion and aggression—was wrong; it is the critics who must, it is claimed, shoulder the responsibility for the consequences of U.S. intervention, not those who organized and supported it or concealed the facts concerning it for many years, and still do.

It is, surely, not in doubt that it was U.S. intervention that inflamed a simmering civil struggle and brought the horrors of modern warfare to relatively peaceful Cambodia, at the same time arousing violent hatreds and a thirst for revenge in the demolished villages where the Khmer Rouge were recruited by the bombardment of the U.S. and its local clients. Matters have reached such a point that a social democratic journal can organize a symposium on the quite astounding question of whether opposition to the U.S. war in Indochina should be reassessed, given its consequences in Cambodia.[^ch06-fn007] Others claim that the scale of the atrocities in Cambodia or their nature—peasant revenge or systematic state-organized murder—does not really matter; it is enough that atrocities have occurred, a stance that would be rejected with amazement and contempt if adopted with regard to benign or constructive bloodbaths.

Predictably, the vast outcry against alleged genocide in Cambodia led to calls for military intervention in the U.S. Congress; we will comment no further on the fact that such a proposal can be voiced in the Congress of the United States or what the fact implies in the light of recent history. A look at some of these proposals reveals how effectively any concern for mere fact has been submerged in the tide of propaganda.

Representative Stephen J. Solarz raised the question "of some kind of international police action under the auspices of the United Nations."[^ch06-fn008] This proposal was advanced during the testimony of Gareth Porter, who had exposed earlier bloodbath lies and also raised doubts about the evidence offered in connection with Cambodia.[^ch06-fn009] As evidence for the genocidal nature of the Cambodian regime, Solarz cited "Khieu Samphan's interview with Oriana Fallaci" in which he allegedly acknowledged "that somewhere in the vicinity of 1 million had been killed since the war." As Porter commented in response, the interview was not with Oriana Fallaci, contained no such "acknowledgement," and is at best of very dubious origin and authenticity, as we discuss below. Undeterred, Solarz raised the question of international intervention.






In congressional hearings a year later, Senator George McGovern gained wide—and unaccustomed—publicity when he suggested military intervention during the testimony of Douglas Pike, who is described in the press as a "State Department Indochina specialist."[^ch06-fn010] According to an AP report, McGovern "called yesterday for international military intervention in Cambodia to stop what he called 'a clear case of genocide,'" citing "estimates that as many as 2.5 million of Cambodia's 7 million people have died of starvation, disease and execution since the Communist takeover three years ago." He is quoted as follows:



This is the most extreme I've ever heard of...Based on the percentage of the population that appears to have died, this makes Hitler's operation look tame...Is any thought being given...of sending in a force to knock this government out of power? I'm talking about an international peacekeeping force, not the United States going in with the Marine Corps.[^ch06-fn011]






McGovern went on to speak of the "crime when an estimated two million innocent Cambodians are systematically slaughtered or starved by their own rulers,'' a case of "genocidal conduct" that cannot be ignored by "the United States, as a leading proponent of human rights."[^ch06-fn012] On CBS television the same day he said that "here you have a situation where in a country of seven million people, possibly as many as a third of them have been systematically slaughtered by their own government," that is, "by a band of murderers that's taken over that government."[^ch06-fn013] He returned to the same theme a few days later, informing the Congress that "a band of murderous thugs has been systematically killing their fellow citizens. Two million Cambodians are said to have been destroyed."[^ch06-fn014]






If 2-2½ million people, about 1/3 of the population, have been systematically slaughtered by a band of murderous thugs who have taken over the government, then McGovern is willing to consider international military intervention. We presume that he would not have made this proposal if the figure of those killed were, say, less by a factor of 100—that is 25,000 people—though this would be bad enough.[^ch06-fn015] Nor would he have been likely to propose this extreme measure if the deaths in Cambodia were not the result of systematic slaughter and starvation organized by the state but rather attributable in large measure to peasant revenge, undisciplined military units out of government control, starvation and disease that are direct consequences of the U.S. war, or other such factors. Nor has McGovern, or anyone else, called for military intervention to cut short the apparent massacre of something like one-sixth of the population of East Timor in the course of the Indonesian invasion, though in this case a mere show of displeasure by the government that provides the military equipment and the diplomatic and economic support for these atrocities might well suffice to bring the murderous attack to a halt.






Assuming then that facts do matter, we naturally ask what McGovern's basis may have been for the specific allegations that he put forth. An inquiry to his office in Washington elicited no source for these charges or documentary evidence to substantiate them. It is interesting that McGovern's call for intervention, widely discussed in the press (occasionally, with some derision because of his record as a dove), has not been criticized on grounds that he seems to have had no serious basis for his charges. Nor did any journalist, to our knowledge, report an inquiry to McGovern to determine what evidence, if any, lay behind the specific factual claims that he put forth in calling for military intervention. (At our urging, one TV newsman has made such an inquiry, and was informed by the staff that his source may have been Lon Nol! For the sake of McGovern's reputation, we would prefer to believe that the numbers were invented).[^ch06-fn016]






On the assumption that facts do matter, we will inquire into the reporting of postwar Cambodia in the Western (primarily U.S.) media. We concede at once that for those who "know the truth" irrespective of the facts, this inquiry will appear to be of little moment. As in the other cases discussed, our primary concern here is not to establish the facts with regard to postwar Indochina, but rather to investigate their refraction through the prism of Western ideology, a very different task. We will consider the kinds of evidence used by the media and those naive enough to place their faith in them, and the selection of evidence from what is available. We will see that the general theory of the Free Press, well-supported by what we have already reviewed, is once again dramatically confirmed: the more severe the allegations of crimes committed by an enemy, the greater (in general) the attention they receive. Exposure of falsehoods is considered largely irrelevant. The situation is rather different from the manufacture of Hun atrocities during World War I, to take an example already discussed, since at that time the falsehoods were exposed only years after—in this case, they continue to surface though refuted at once. The U.S. responsibility is largely ignored, though critics such as Jean Lacouture are not guilty of this incredible moral lapse,[^ch06-fn017] and virtually no effort is made to consider postwar Cambodia, or the credibility of evidence concerning it, in the light of historical experience such as that reviewed in chapter 2.






Ponchaud comments that there is a prima facie case in support of atrocity allegations: "the exodus of over one hundred thousand persons is a fact, and a bulky one, that raises enough questions in itself."[^ch06-fn018] We would add that by parity of argument, the same considerations apply elsewhere; the exodus of approximately one hundred thousand persons fleeing from the victors of the American revolution also raises questions, particularly when we recall that the white population was about 2½ million as compared with 7-8 million Cambodians and that this was after a war that was far less bitterly fought and lacked any comparable atrocities by foreign powers.[^ch06-fn019]






Most of the well-publicized information concerning postwar Cambodia derives from reports of refugees—or to be more precise, from accounts by journalists and others of what refugees are alleged to have said. On the basis of such reports, these observers draw conclusions about the scale and character of atrocities committed in Cambodia, conclusions which are then circulated (often modified) in the press or the halls of Congress. For example, Barron-Paul present some examples of what they claim to have heard from refugees and then conclude that the government of Cambodia is bent on genocide, a conclusion which is then presented in various forms by commentators. Similarly Ponchaud cites examples of refugee reports and concludes that the government is engaged in "the assassination of a people," giving estimates of the numbers executed or otherwise victims of centralized government policies. Reviewers and other commentators then inform the public that Ponchaud has shown that the Cambodian government, with its policies of autogenocide, is on a par with the Nazis, perhaps worse. With each link in the chain of transmission, the charges tend to escalate, as we shall see.






Evidently, a serious inquiry into the facts and the way they are depicted should deal with several issues: (1) the nature of the refugee testimony; (2) the media selection from the evidence available; (3) the credibility of those who transmit their version of refugee reports and draw conclusions from them; (4) the further interpretations offered by commentators on the basis of what evidence they select and present. We will concentrate on the third and fourth issues. But a few observations are in order about the first and second.






It is a truism, obvious to anyone who has ever dealt with refugees or considers the historical record or simply uses common sense, that "the accounts of refugees are indeed to be used with great care."[^ch06-fn020] It is a truism commonly ignored. For example, the New York Times Pulitzer prize-winning specialist on refugees from Communism interviewed Cambodian refugees in Thailand "in a cage 8 feet square and 10 feet high in the police station of this provincial capital," where "9 men are huddled on the bare floor" rarely speaking and staring "into the narrow space before them with dulled eyes."[^ch06-fn021] It does not occur to him, here or elsewhere, to treat the accounts offered under such circumstances with the "great care" that Ponchaud properly recommends. The media favorite, Barron-Paul, is based largely on visits to refugee camps arranged in part by a representative of the Thai Ministry of the Interior, whose "knowledge and advice additionally provided us with invaluable guidance."[^ch06-fn022] In the camps to which they gained access with the help of this Thai official, who is responsible for internal security matters including anti-Communist police and propaganda operations, they "approached the camp leader elected by the Cambodians and from his knowledge of his people compiled a list of refugees who seemed to be promising subjects"[^ch06-fn023]—one can easily imagine which "subjects" would seem "promising" to these earnest seekers after truth, to whom we return. Citing this comment,[^ch06-fn024] Porter points out that "the Khmer camp chief works closely with and in subordination to Thai officials who run the camps and with the Thai government-supported anti-Communist Cambodian organization carrying out harassment and intelligence operations in Cambodia." The camps and their leaders are effectively under Thai control and the refugees who eke out a miserable existence there are subject to the whims of the passionately anti-Communist Thai authorities, a point that should be obvious to journalists and should suggest some caution, but is entirely ignored by Barron-Paul, as well as by many others. The story is just too useful to be treated with the requisite care.






Ponchaud, who is more serious, describes the treatment of the refugees in Thailand: they spend a week or more in prison before being sent to camps where they are "fed increasingly short rations" and "have to offer some token of gratitude to the camp guards for letting them out to look for work." He continues:






There is little hope for them. They live with their memories, constantly reliving the horrors they have witnessed. Each one recounts what he saw or heard, his imagination and homesickness tending to exaggerate and distort the facts.[^ch06-fn025]






Essentially the same point is made by Charles Twining, whom the State Department regards as "really the best expert [on Cambodian refugees]...that exists in the world today."[^ch06-fn026] Stating that executions continue, he says that "we hear about executions from refugees who have just come out. You must talk to a refugee as soon as he comes out or the story may become exaggerated."[^ch06-fn027] How exaggerated it may become by the time it reaches Barron-Paul or Kamm, the reader may try to estimate. The issue does not concern them, judging by their reports. Nor has it concerned those who rely on and draw firm conclusions from these reports.






Access to refugees is generally controlled by Thai authorities or their subordinates (to speak of "election," as Barron-Paul do without qualification, is odd indeed under these circumstances). The translators also presumably fall in this category, or are believed to by the refugees who depend for survival on the grace of their supervisors. Clearly, these are unpromising circumstances for obtaining a meaningful record—compare in contrast, the circumstances of the Bryce report with its record of apparent fabrications.[^ch06-fn028] Ponchaud is unusual in making the obvious point that great care must be exercised. Clearly, the reports of refugees should be carefully heeded, but the potential for abuse is great, and those who want to use them with propagandistic intent can do so without serious constraint.






Not surprisingly, there are many internal contradictions in refugee reports. In the May Hearings Porter cites the case of Chou Try, who told a CBS reporter that he had witnessed the beating to death of five students by Khmer Rouge soldiers. In October 1976, he told Patrice de Beer of Le Monde that he had witnessed no executions though he had heard rumors of them.[^ch06-fn029] Porter notes that he was "chosen to be the Khmer chief" of the refugee camp at Aranyaphrathet, where a great many of the interviews have taken place. There are many similar examples. As Porter and Retbøll both insist, refugee reports should certainly not be disregarded, but some care is in order. Evidently, interviews arranged under the circumstances described by Kamm or Barron-Paul are of limited credibility.






One refugee who became both well-known and influential in the United States is Pin Yathai. At a press conference held under the auspices of the American Security Council, Yathai, described as "one of his country's top civil engineers and a leading member of the government" who escaped to Thailand in June of 1977, testified that people were reduced to cannibalism under Khmer Rouge rule:[^ch06-fn030] "A teacher ate the flesh of her own sister" and was later caught and beaten to death as an example, he alleged, citing also another case of cannibalism in a hospital and other stories of starvation, brutality, and disease.[^ch06-fn031] He was interviewed by Jack Anderson on ABC television,[^ch06-fn032] and his stories were also featured in the mass circulation TV Guide in "an article on the paucity of media coverage of the Cambodian holocaust by Patrick Buchanan," one of Nixon's speechwriters.[^ch06-fn033] Later, they became the basis for a substantial right wing attack on the Washington Post for its failure to cover Pin Yathai's news conference, and in general, to give what these groups regard as adequate coverage to Cambodian atrocities. Le Monde also published two articles based on Pin Yathai's allegations as well as a letter from another Cambodian attacking his credibility and accusing him of having been a member of the "Special Committee" of the Lon Nol government that was engaged in counterespionage, assassinations, perhaps the drug traffic, and was believed to have been funded by the CIA.[^ch06-fn034]






The right wing Bangkok Post did report the press conference in which Pin Yathai presented his account of cannibalism and other horrors.[^ch06-fn035] The Bangkok Post story observed that "Cambodian refugees in Thailand yesterday discounted reports that cannibalism is frequent in Cambodia and even doubted if it has occurred at all." It also quoted "another Cambodian civil engineer who had long talks with Pin Yathai while he was in Bangkok" and who told AFP: "No more than 40 per cent of the statement Pin Yathai made in the United States is true. He never went so far while talking to fellow refugees in his own language." This information was not circulated by Accuracy in Media in its attacks on the Washington Post nor has it been presented by others who gave wide publicity to Pin Yathai's accounts.






Not all refugees are welcomed so eagerly as Pin Yathai. Consider, for example, a story in the London Times on a Vietnamese refugee who escaped from Vietnam through Cambodia to Thailand, which he entered in April 1976.[^ch06-fn036] He walked 350 miles through Cambodia over a two-month period.[^ch06-fn037] A civil engineer "with high qualifications" who speaks French, Thai, Khmer and Lao in addition to English, this refugee with his unique experience in postwar Cambodia, where "because of his fluency in Khmer and local knowledge he was taken everywhere for a Cambodian," seems a prime candidate for interviews in the press. But, in fact, he never made it to the New York Times, Time, TV Guide, or other U.S. media. His lack of qualifications are revealed by his comments when he arrived in Thailand, where he heard stories of massacres in Cambodia:






I could not believe it. Walking across the country for two months I saw no sign of killing or mass extermination and nobody I spoke to told me of it. I still don't believe it happened.






Note that the observations of this man, a middle-class refugee from Vietnam with the appropriate anti-Communist credentials, do not contradict the stories of brutal atrocities told in profusion by refugees. Rather, they are consistent with the remarks by State Department Cambodia watchers and other specialists on the geographical limitations of the worst atrocity stories, and suggest that there may be a good deal of local variation rather than the coordinated campaign of state-directed genocide that the media and their main sources prefer. But this very fact suffices to consign this report to oblivion in the United States, despite its undoubted significance as a rare window on inner Cambodia from what appears to be a fairly credible source. We will return to other examples, merely noting here the striking contrast between the media exposure in this case and in the case of Pin Yathai.






In fact, even the witnesses who are specifically selected to recount atrocity stories often add significant qualifications. For example, one of the witnesses at the Oslo Hearings on Human Rights Violations in Cambodia held in April 1978, was Lim Pech Kuon, who said that he "well understood" the Khmer Rouge policy. He asserted, "that he had never heard the Khmer Rouge indicate that they intended to kill all classes except the workers and poor peasants":






It was perhaps more correct to say that, in the Khmer Rouge interpretations, the relics of the classes would be abolished—not eradicated. He also said that he had never seen an execution with his own eyes. When he arrived in Phnom Penh after the Khmer Rouge victory he had seen a number of corpses in the streets, but the corpses were covered, and so he could not see whether they were soldiers or civilians. He made it clear that it was the lack of freedom which made him flee by heliocopter.[^ch06-fn038]






While the media give the impression that refugees have uniformly recounted stories of horrible atrocities, journalists have occasionally noticed that the reports are actually more varied. John Fraser of the Toronto Globe and Mail, whose reports from Vietnam we discussed briefly in chapter 4, also visited a Cambodian refugee camp in Vietnam, "fully prepared for a host of atrocity stories about mass executions, bloody beheadings and savage Khmer Rouge brutality," particularly since the camp was only 50 miles from the border where there had been "deadly combat":






To my surprise I got lots of tales of hardship, but no atrocities save for a second-hand account of an execution of two men. The accounts of life in Cambodia were grim enough and the atrocity stories too well authenticated to doubt, but still no one at that camp was able to tell me one. I finally had to ask if there was anyone who knew of an execution and after some time I got the second-hand story. I offer no conclusions on this singular fact, except that it was strange with so many refugees not to be able to get more information, particularly since it would have been useful for Vietnamese propaganda.[^ch06-fn039]






We know of only one Khmer-speaking Westerner who is an academic specialist on Cambodia and has visited refugee camps in Thailand without the supervision of authorities, namely, Michael Vickery, who reports as follows on his August 1976 visit:






Since I speak Khmer I was something of a curiosity for them and it was easy to gather a crowd around and listen to what they said whether in response to questions or to unorganized conversation. It was soon clear that there was much disagreement among the refugees about conditions in Cambodia. Some pushed the brutality line, others denied it, or emphasized that killings were rare and due to the cruelty of a few individual leaders. Thus many of the refugees admitted that they had left because they disliked the rigorous working life under the new regime, not because they were themselves threatened with death or brutality. So much, though, was already apparent from a close reading of newspaper accounts. What I found more intriguing was that once when alone with one of the men he called attention to the lack of agreement and added that it was never noticed by outsiders because they didn't understand Khmer. According to him, camp authorities had organized French and English speaking refugees as informants to give the official line to journalists who came to visit.[^ch06-fn040]






We return to Vickery's published and private comments, which are valuable and very much to the point.






Not everyone who is interested in analyzing refugee accounts is permitted the kind of access offered by the Thai Ministry of Interior to Barron and Paul. Cornell University Cambodian specialist Stephen Heder, who was a journalist in Phnom Penh, speaks and reads Khmer, is the author of articles on contemporary Cambodia—and has been notably skeptical about the standard conclusions drawn by journalists after guided tours through refugee camps—received funding from the Social Science Research Council and the Fulbright-Hays Program to do a systematic study of postwar Cambodia based on refugee testimony and Phnom Penh Radio broadcasts. He was informed by the Secretary-General of the National Research Council of Thailand that "the present political situations [sic] in Thailand do not favour us to consider this type of research. Therefore, if you still have an intention to do a research works [sic] in Thailand, please be advised to change your topic." One way to give the impression that refugee stories consistently and without exception report atrocities is to prevent competent researchers fluent in Khmer, who do not need the guidance of Thai ministers or "elected camp commanders," from examining the evidence for themselves. We have no doubt that when Heder publishes on contemporary Cambodia, his work will be criticized by those who do not approve of his conclusions on the grounds that he "ignores refugee data."






To summarize, several points are worth noting. Refugee reports are to be taken seriously, but with care. In their eagerness to obtain "evidence" that could be used to defame the regime in Cambodia, such reporters as Barron and Paul or Henry Kamm, as their own testimony indicates, failed to observe the most obvious and elementary cautions that should be second nature to any serious journalist and that are specifically emphasized by Ponchaud, Twining, and others. The media, furthermore, have their own criteria for deciding which reports to emphasize and which to ignore. To evaluate refugee reports it is necessary to take into account extreme bias both in selection of stories and treatment of them. The apparent uniformity of refugee testimony is in part at least an artifact reflecting media bias. In particular, it would be difficult to construct an argument in support of the thesis of central direction and planning of atrocities on the basis of alleged uniformity of refugee reports, since in fact there appears to be considerable variety; to sustain such a thesis other evidence is required, for example, documentary evidence. The unwillingness of the Thai authorities to permit independent scholarly study also raises questions, given the obvious interest of the Thai—shared by Western media and governments—in presenting the worst possible picture of postwar Cambodia. We will consider these questions in more detail below, but even a brief look at the handling of refugee reports suggests that a degree of caution is in order.






Refugee reports constitute one essential category of information about a society as closed to the outside as postwar Cambodia has been. The second link in the chain of transmission of information, which in this case is subject to some independent check for credibility, is the reporters and others who transmit their stories. To inquire into their credibility is surely a crucial matter in evaluating the material that reaches the public. People who have expressed skepticism about the press barrage are commonly accused of refusing to believe the accounts of miserable refugees, a line that is much easier to peddle than the truth: that they are primarily raising questions about the credibility of those who report—and perhaps exploit—the suffering of the refugees and what they are alleged to have said.[^ch06-fn041] When refugee stories are transmitted by reporters of demonstrated integrity,[^ch06-fn042] they merit more serious attention than when the account is given by someone who is otherwise unknown or has an obvious axe to grind. When a reporter from Pravda describes the horrors of U.S. bombing in Northern Laos, a rational observer will be more skeptical than when similar eyewitness reports are provided by Jacques Decornay of Le Monde.[^ch06-fn043] Similarly, when Leo Cherne, chairman of the International Rescue Committee, discusses the barbarism of the Khmer Rouge,[^ch06-fn044] a rational reader will recall the previous history of this longtime apologist for U.S. violence and oppression who attempts to disguise this miserable display under a humanitarian cloak—for example, his supremely cynical description of the victims of U.S. bombings in South Vietnam: "There are more than 700,000 additional refugees who have recently fled the countryside dominated by the Vietcong and with their act of flight have chosen the meager sanctuary provided by the government of South Vietnam."[^ch06-fn045]






To determine the credibility of those who transmit reports is a critical matter for anyone concerned to discover the truth, either about Cambodia or about the current phase of imperial ideology. There is only one way to investigate this question: namely, to pay careful attention to the use of quotes and evidence. Such an inquiry may seem pointless or irrelevant, or even cruel, to people who are quite certain that they already know the truth. Lacouture expresses feelings that are not uncommon in his "Corrections":






Faced with an enterprise as monstrous as the new Cambodian government, should we see the main problem as one of deciding exactly which person uttered an inhuman phrase, and whether the regime has murdered thousands or hundreds of thousands of wretched people? Is it of crucial historical importance to know whether the victims of Dachau numbered 100,000 or 500,000. Or if Stalin had 1,000 or 10,000 Poles shot at Katyn?[^ch06-fn046]






Or perhaps, we may add, whether the victims of My Lai numbered in the hundreds, as reported, or tens of thousands, or whether the civilians murdered in Operation SPEEDY EXPRESS numbered 5,000 or 500,000, if a factor of 100 is relatively insignificant?[^ch06-fn047] If facts are so unimportant, then why bother to present alleged facts at all?






If, indeed, the Cambodian regime was, as Lacouture believes, as monstrous as the Nazis at their worst, then his comment might be comprehensible, though it is worth noting that he has produced no evidence to support this judgment.[^ch06-fn048] But if a more appropriate comparison is, say, to France after liberation, where a minimum of 30-40,000 people were massacred within a few months with far less motive for revenge and under far less rigorous conditions than those left by the U.S. war in Cambodia, then perhaps a rather different judgment is in order.[^ch06-fn049] As we shall see, there is a considerable range of opinion on this score among qualified observers, though the press has favored Lacouture's conclusion, generally ignoring mere questions of fact.






We disagree with Lacouture's judgment on the importance of accuracy on this question, particularly in the present historical context, when allegations of genocide are being used to whitewash Western imperialism, to distract attention from the "institutionalized violence" of the expanding system of subfascism and to lay the ideological basis for further intervention and oppression. We have seen how effectively the Western propaganda system creates, embroiders, plays up, distorts, and suppresses evidence according to imperial needs. Western domination of world communications adds to the importance of closely evaluating evidence that so conveniently meets pressing ideological requirements. In this context, it becomes a question of some interest whether in Cambodia, for example, a gang of Marxist murderers are systematically engaged in what Lacouture calls "autogenocide"—"the suicide of a people in the name of revolution; worse, in the name of socialism"[^ch06-fn050]—or whether the worst atrocities have taken place at the hands of a peasant army, recruited and driven out of their devastated villages by U.S. bombs and then taking revenge against the urban civilization that they regarded, not without reason, as a collaborator in their destruction and their long history of oppression. Future victims of imperial savagery will not thank us for assisting in the campaign to restore the public to apathy and conformism so that the subjugation of the weak can continue without annoying domestic impediments. Especially in such countries as France and the United States—to mention only two international gangsters whose post-World War II depredations are not dismissed so quickly by past and potential victims as they are at home—it is a crucially important matter to be quite scrupulous with regard to fact, to pay careful attention to past history and to subject to critical analysis whatever information is available about the current situation.[^ch06-fn051]






Attention to fact was a particularly significant matter under the conditions of 1975-78, when extreme and unsupported allegations could be used to support military intervention, not a small consideration as we see from McGovern's statements already discussed or—more significantly, as recent history shows—from the context of the Vietnamese invasion discussed in the preface to this volume.






Quite apart from these considerations, which seem to us rather important, it is surely worthwhile, if one is going to discuss Cambodia at all, to try to comprehend what has in fact taken place there, which is quite impossible if critical standards are abandoned and "facts" are contrived even out of honest anger or distress.






The inquiry to which we now turn will appear to be a pointless exegetical exercise to people who share Lacouture's judgment or for whom facts are simply an irrelevant nuisance, like the editors of the Wall Street Journal. While the latter reaction merits no comment, Lacouture's is not so quickly dismissed, though we feel that it is deeply wrong in the case of an investigation of postwar Cambodia, and entirely untenable if one is concerned—as we are here—with the workings of the Western propaganda system.






There is a related methodological point that merits comment, if only because it is so commonly misunderstood. Plainly, we may divide the evidence available into two categories: (1) evidence subject to some independent verification; (2) evidence that must be taken on faith. A person who is at all serious will concentrate on category (1) in trying to determine how much trust to place in unverifiable reports of category (2).[^ch06-fn052] If it turns out that some source is quite untrustworthy when claims can be checked, then naturally one will view with corresponding skepticism reports from this source that are subject to no such check. But in the sources that raise the charge of genocide, the overwhelming bulk of the evidence is of category (2). Therefore it is easy to be misled into thinking that even if the evidence of category (1) does not withstand critical analysis, the matter is of no serious import since it is of such a minor nature as compared with the far more serious (and unverifiable) charges. A moment's thought should suffice to show that this conclusion is entirely untenable; nevertheless, as we shall see, it is not at all uncommon.






Let us return now to McGovern's call for intervention and the press reaction to it. McGovern provided no source for his estimate of 2-2½ million systematically killed by thugs who had taken over the government of Cambodia, though such charges have been bandied about widely in the press since immediately after the Khmer Rouge victory.[^ch06-fn053] Nor did McGovern attempt to sort out the relative proportions of those who were killed by government plan or edict or in random acts of violence (evidently, rather different categories) as compared with those who died from malnutrition and disease.






McGovern's remarks, as well as much of the press commentary concerning them, amount to the claim that the population is suffering in misery under a savage oppressor bent on genocide. Mere common sense, even apart from special knowledge, should raise at least some doubts about this picture. In the first place, is it proper to attribute deaths from malnutrition and disease to the Cambodian authorities? Compare, for example, the case of Laos already discussed, where relief workers speak of hundreds of thousands of deaths from malnutrition and disease as a legacy of colonialism and more specifically, the U.S. attack on a defenseless society, while the United States withholds desperately needed aid. It surely should occur to a journalist or the reader to ask how many of the deaths in Cambodia fall to the U.S. account. There is evidence on this matter, but it is systematically excluded from the press. Or, one might wonder, how can it be that a population so oppressed by a handful of fanatics does not rise up to overthrow them? In fact, even in the hearings where McGovern reported the estimates of 2½ million deaths attributable to the Khmer Rouge and "called for international military intervention," the State Department response should have aroused some questions in the mind of a moderately serious reporter. Douglas Pike, responding to McGovern, said that "the notion of a quick, surgical takeout of the government of Cambodia probably is not possible":






He pointed to Cambodia's unique government consisting of a ruling group of nine men at the center and communal government 'in the style of the 14th century' in the villages, with no regional or provincial governments in between..."To take over Cambodia you're going to have to take over the villages—all of them," he said.[^ch06-fn054]






Evidently there must be at least some support for the group of nine men at the center if it will be necessary to take over every village to overthrow their rule. The quandary has been expressed by other State Department experts. Charles Twining, who says that he was "sent to Bangkok [by the State Department] as the Indochina watcher with responsibility primarily for finding out what is happening in Cambodia and Vietnam," made the following remark in response to Rep. Solarz's query as to "how people at the top manage to establish their authority over these young soldiers out in the villages who are carrying out this policy of extermination":






It is a difficult question. We know the levels of administration in Cambodia; it goes from the central to the region to the sector to the district to the commune to the village. Presumably, then, there are loyal people at all of these levels. What really binds together these largely Paris-educated fanatics at the top with almost purposefully ignorant farm boys at the bottom who are the ones with the guns carrying out their orders—I really don't know what it is that keeps them together and I wonder in the future how long something like this can continue, how long that glue can hold.[^ch06-fn055]






It is, indeed, "a difficult question."






Similar doubts were raised by experts close to the U.S. government during the earlier May Hearings. In response to Rep. Solarz's remarks about possible intervention, Peter A. Poole, formerly a Foreign Service Officer in Cambodia and now a professor of international relations at American University, said that "I think that an international police force would be one of the worst possible things we could do." On the evacuation of Phnom Penh, he said: "They obviously overdid it. They obviously did it very badly. But the general thrust of moving people out of the city was something that practically any regime would have contemplated and done at some stage in that year, getting the people back on the land and producing rice." The Khmer Rouge, he added, "took over at a time when society was in ruins, so that there were no normal means of government...in a state of social, political, and economic chaos" and ran the country with "an ignorant peasant teen-age army, a rather large, very obedient army, well-armed and totally flexible, totally obedient to orders" who might respond to a command to march the people down the road by shooting those who do not obey. As to how the Khmer Rouge were able "to establish that sense of total discipline in the ranks of the army," Poole answered: "I don't know the answer to that question."[^ch06-fn056]






Another former Foreign Service Officer in Phnom Penh, David P. Chandler, now a senior lecturer at Monash University in Australia, added some further comments which had little impact on the subsequent proceedings:






What drove the Cambodians to kill? Paying off old scores or imaginary ones played a part, but, to a large extent, I think, American actions are to blame. From 1969 to 1973, after all, we dropped more than 500,000 tons of bombs on the Cambodian countryside. Nearly half of this tonnage fell in 1973...In those few months, we may have driven thousands of people out of their minds. We certainly accelerated the course of the revolution. According to several accounts, the leadership hardened its ideology and got rid of wavering factions during 1973 and 1974...We bombed Cambodia without knowing why, without taking note of the people we destroyed...it is ironic, to use a colorless word, for us to accuse the Cambodians of being indifferent to life when, for so many years, Cambodian lives made so little difference to us.[^ch06-fn057]






Chandler's comment was rejected by Rep. William F. Goodling on the following grounds:






Our bombs didn't single out certain segments or certain peoples in Cambodia. Our bombs hit them all [sic]. And whether you thought it was right or I thought it was right, the military at that particular time thought it was right.[^ch06-fn058]






The comment is a fitting one from a leading apologist for the U.S.-backed Indonesian atrocities in Timor.[^ch06-fn059]






Twining's "difficult question" is addressed in an article by Kenneth Quinn of the National Security Council Staff,[^ch06-fn060] one of the three leading U.S. government experts on Cambodia.[^ch06-fn061] Basing himself primarily on refugees who fled Cambodia in 1973-1974, Quinn reviews Khmer Rouge programs in an effort to explain "how a small but dedicated force was able to impose a revolution on a society without widespread participation of the peasantry" and indeed in the face of strong peasant opposition. He does not remark that since his evidence derives primarily "from the in-depth interviewing of selected refugees," it will obviously be negative; those who might approve of these programs are excluded from his sample. But ignoring this trivial point, Quinn states that "the evidence overwhelmingly demonstrates that the peasantry was opposed to almost all of the [Khmer Rouge] programs." Quinn discusses programs which included land reform, establishment of cooperatives, ensuring "that all citizens have roughly the same degree of wealth," obliterating class lines by confiscating property from the wealthy and compelling university students to plant and harvest rice, distributing excess crops "to feed other groups whose harvest was insufficient," etc. He notes that "as a result [of collectivization], production has outstripped previous individual efforts" and that "political-­psychological [Khmer Rouge] efforts" seem to "have achieved significant results...according to all accounts" among the youth, who "were passionate in their loyalty to the state and party," "rejected the mystical aspects of religion," and "stopped working on their family plot of land and instead worked directly for the youth association on its land." He also comments that the Khmer Rouge "success is all the more amazing when it is realized that they had few, if any, cadres at the village or hamlet level...In most cases, there was no separate party existence nor were there political cadres at the village level or at any level below," though there were small, apparently locally recruited military units (in the midst of the civil war), as well as "interfamily groups" of a sort that "have existed in other Southeast Asian countries for years" and were used by the Khmer Rouge "for forcing the population to carry out a whole series of radically new programs."






Quinn then asks the "difficult question": "How did such a small group of people carry out such a varied and all-encompassing effort?" His answer is that "they cowed people and suppressed dissent and opposition through harsh and brutal punishments; and they constructed a governmental apparatus at the village and hamlet level which allowed them to exercise tight control over every family in the area." The possibility that some of the programs he reviewed might appeal to poor peasants is nowhere considered; it is excluded on doctrinal grounds.






Quinn claims that in 1973 the Khmer Rouge programs became extremely harsh as new cadres took over, described as "fanatics," who were "austere" and "did not take anything for themselves and seemed willing to live a frugal life" but instituted widespread terror. Other sources, as we have seen, confirm that the Khmer Rouge programs became harsh in 1973—as the United States stepped up its murderous program of saturation bombing, a possible causal factor that Quinn is careful never to mention.






There are other aspects to the "difficult question" that properly troubled government specialists. How indeed do the Khmer Rouge manage to maintain control? Here, the refugee reports evoke some questions. For example, R.-P. Paringaux reported interviews with two high functionaries of the Lon Nol regime who had escaped to Thailand.[^ch06-fn062] They report that armed surveillance was "almost nonexistent" in the village to which they were sent. "In case there are problems, the village chief can call upon a militia group of 12 Khmers Rouges who maintain order in the ten villages of the sector." One of these functionaries comments that the "old people"—those who were with the Khmer Rouge during the war—offer more support to the new regime: "they are peasants, who have always been used to hard work and to be content with little.[^ch06-fn063] It would seem not unlikely that part of the answer to the difficult question, and a reason why a dozen militiamen can maintain order in ten villages, is that the regime has a modicum of support among the peasants.






Other questions arise. If 1/3 of the population has been killed by a murderous band that has taken over the government—which somehow manages to control every village—or have died as a result of their genocidal policies, then surely one would expect if not a rebellion then at least unwillingness to fight for the Paris-educated fanatics at the top. But the confused and obscure record of the border conflicts with Thailand and Vietnam would appear to indicate that there are a substantial number of "purposefully ignorant farm boys" who have not exactly been awaiting liberation from their oppressors.[^ch06-fn064] As Pike observed in response to McGovern's call for intervention, the Vietnamese tried a "quick judo chop" against the Cambodian regime with 60,000 troops but "failed abysmally."[^ch06-fn065] Basing herself on Pike's testimony, Susan Spencer of CBS raised the question to McGovern in a TV interview.[^ch06-fn066] When McGovern referred to Cambodia as "an underdeveloped country that has gotten out of control and is systematically slaughtering its own citizens," Spencer make the following comment:






You mentioned that we should apply pressure. It seems, though, that the Vietnamese, who periodically are at war with Cambodia, have found that the Cambodian citizens, at least the villagers, seem to support the government. What lever do we have to break in—to break that?






Spencer's question is a bit odd to begin with. If the villagers of this largely peasant society support the government, as Spencer assumes, then exactly what right do we have to find a "lever" to "break that"? And how does that alleged support square with the charge of genocide? These questions did not arise, however. McGovern simply replied that "the evidence is that about nine men are controlling that government in Cambodia" without a "loyal infrastructure out across the country" and it is "hard to believe that there's mass support for the Cambodian government."






The problem is implicit, though rarely discussed in these terms, in other reports concerning Cambodia. Robert Shaplen, who has been the Far Eastern correspondent for The New Yorker for many years, observes that in the border war with Vietnam, "the Cambodians have proved to be tough, ruthless and relentless fighters."[^ch06-fn067] The Southeast Asia correspondent for the Christian Science Monitor comments that "despite Vietnam's superior size, economy, and military power, Cambodia appears to have emerged the technical 'victor' after the Vietnamese invasion that ended with a military withdrawal in January...In fact, Cambodian attacks across Vietnam's borders currently are described by one analyst as 'heavier than ever'...Vietnam appears to have underestimated the strength of Cambodian resistance, several analysts note."[^ch06-fn068] The continuing conflict with Thailand brings out similar anomalies. Whatever the facts may be—and they are far from clear—it seems that Cambodian forces held their own, so much so that U.S. analysts "voice skepticism about Hanoi's ability to crush Cambodia" despite its overwhelming military advantages, because of "factors such as the apparently excellent morale of Cambodia's ground forces."[^ch06-fn069]






Various explanations have been offered for these facts, which at the very least raise questions about the allegations that the population is groaning under the heels of the conquerer.[^ch06-fn070]






William Buckley explains the difficulty away with resort to the mysterious Asian mind: nationalism carried to such lengths "is utterly alien to the western experience."[^ch06-fn071] Ponchaud argues that "the old Hindu core, which regarded authority as a divine incarnation, was still strong in the Khmers...'The Cambodian sticks to the rule'; The Khmer people still respect authority with a respect that to us is tinged with fatalism, even passivity, but that eminates an underlying confidence in the abilities of those in power...The underlying ideology [of the revolution] may come from somewhere else, but the methods employed show every mark of the Cambodian character," and Khmer culture makes it possible for the authorities to rule "the countryside with terror and lies," though "under Marxist influence, perhaps the Khmer will suddenly open a critical eye." "Another cause of the radicality of the Khmer revolution lies in the Khmer way of reasoning, which is bewildering to Cartesian minds. The Khmer thinks by accretions or juxtapositions, but adheres strictly to the rules of his own internal logic," apparently incapable of "Cartesian" logic.[^ch06-fn072]






The non-specialist may wonder about the cogency of these explanations of the "difficult question" that government specialists rightly find troubling. It is noteworthy that in the varied attempts to find a solution to this most difficult question, one conceivable hypothesis does not seem to have been considered, even to be rejected: that there was a significant degree of peasant support for the Khmer Rouge and the measures that they had instituted in the countryside.






As we begin to inquire a little further, other difficult questions arise. Consider the numbers game. What is the source of the figures invoked by the press? We shall see that the sources are obscure or misrepresented, though when corrected, they continue to surface. Furthermore, there is considerably more controversy among knowledgeable observers than the standard line of the press would indicate. For example, Lewis M. Simons, the outstanding Washington Post correspondent, reported from Bangkok that "disease and malnutrition combined with a dropping birthrate are taking a greater toll of Cambodia's population than Communist executions, according to some of the latest analyses made here." There is a






major reversal in Western judgments of what had gone on inside Democratic Kampuchea...Most Westerners who make an occupation of observing Cambodia from Thailand are talking in terms of several hundred thousand deaths from all causes. This is a marked shift from the estimates of just six months ago, when it was popular to say that anywhere between 800,000 and 1.4 million Cambodians had been executed by vengeful Communist rulers.[^ch06-fn073]






He also noted that "few Cambodia-watchers believe that






"The Organization" [Angkar, the governing group] is organized well enough to control much of the country. It is generally accepted that local military commanders, operating from jungle bases, conduct their own small-scale border rations [sic] and impose summary justice.






There are two noteworthy points in this report by Lewis Simons—which was accepted with one irrelevant qualification as "excellent" by the State Department's leading Cambodia watcher. First, the number of deaths is estimated by "most Westerners" who are close observers as in the several hundred thousand range, most of them from disease and malnutrition. Second, most Cambodia watchers doubt that the "summary justice" is centrally organized, believing rather that it is the responsibility of local commanders. Again we are left with some doubts, to put it conservatively, as regards the standard media picture: a centrally-controlled genocidal policy of mass execution.






Note also that the numbers killed were estimated by the leading government expert as in the "thousands or hundreds of thousands." (Twining, who adds that "very honestly, I think we can't accurately estimate a figure.") His superior, Richard Holbrooke, offered an estimate of "tens if not hundreds of thousands" for "deaths" from all causes.[^ch06-fn074] He offered his "guess" that "for every person executed several people have died of disease, malnutrition, or other factors ..." (which he claims were "avoidable," though he does not indicate how).[^ch06-fn075] Twining's colleague Timothy Carney—the second of the State Department's leading Cambodia watchers—estimated the number of deaths from "brutal, rapid change" (not "mass genocide") as in the hundreds of thousands.[^ch06-fn076] What about deaths from causes other than killing? A major source of death, Simons reports:






appears to be failure of the 1976 rice crop. The government averted famine in mid-1975 by evacuating Phnom Penh and other cities and forcing almost every ablebodied person to work the land. But food production fell badly last year.






If this "excellent" analysis is correct, as Twining indicates, the evacuation of Phnom Penh, widely denounced at the time and since for its undoubted brutality, may actually have saved many lives.[^ch06-fn077] It is striking that the crucial facts rarely appear in the chorus of condemnations. At the time of the evacuation, AFP reported from Bangkok that:






Recent aerial photographs by American reconnaissance planes are said to have shown that only 12 percent of the rice paddies have been planted. The monsoon, which marks the beginning of the planting season, came a month early this year. There was also the problem of the acute shortage of rice in the capital when the Communists took over on April 17. According to Long Boret, the old Government's last premier, Phnom Penh had only eight days' worth of rice on hand on the eve of the surrender.[^ch06-fn078]






In a New York Times Op-Ed, William Goodfellow, who left Cambodia with the final U.S. evacuation in April, 1975 wrote that "A.I.D. officials reported that stockpiles of rice in Phnom Penh could last for six days." Commenting on the "death march" from Phnom Penh, he writes that "in fact, it was a journey away from certain death by starvation...[which]...was already a reality in the urban centers."[^ch06-fn079] The director of the U.S. aid program "estimated that in Phnom Penh alone 1.2 million people were in 'desperate need' of United States food, although at the time only 640,000 people were actually receiving some form of United States food support" and "starvation was widely reported."[^ch06-fn080] Goodfellow also correctly assigns the responsibility for the impending famine: it was caused primarily by the U.S. bombing campaign which "shattered" the agrarian economy—an unquestionable fact that has since been quietly forgotten.






The situation in Phnom Penh resulting from the U.S. war is graphically described in a carefully-documented study by Hildebrand and Porter that has been almost totally ignored by the press.[^ch06-fn081] By early 1974 the World Health Organization estimated that half the children of Phnom Penh, which was swollen to almost 5 times its normal size by the U.S. bombardment and the ravages of the war directly caused by U.S. intervention, were suffering from malnutrition. A Congressional study mission reported "severe nutritional damage." Studies in late 1974 and early 1975 revealed "a disastrous decline in nutritional status," indicating "a caloric intake during a year or longer of less than 60 percent of the minimum required to maintain body weight." A Department of State study of February 1975 reported that these statistics "confirmed the universal medical impression given us by those involved in Cambodia health and nutrition that children are starving to death." Starvation also lowered resistance to infection and disease. There were reports that cholera was spreading rapidly in Phnom Penh. The medical director for Catholic Relief Services declared in March, 1975, that "hundreds are dying of malnutrition every day." Red Cross and other observers reported thousands of small children dying from hunger and disease. Note that all of this refers to the period before the Khmer Rouge victory.






As Hildebrand and Porter remark, "those children who did not die from starvation will suffer permanent damage to their bodies and minds due to the severe malnutrition." They quote Dr. Penelope Key of the World Vision Organization, working in Phnom Penh:






This generation is going to be a lost generation of children. Malnutrition is going to affect their numbers and their mental capacities. So, as well as knocking off a generation of young men, the war is knocking off a generation of children.






Porter added relevant information in his Congressional testimony:






It must be noted that the same official sources who were claiming [a postwar death toll of 800,000-1.4 million] had been saying in June 1975 that a million people were certain to die of starvation in the next year because there were simply no food stocks available in Cambodia to provide for them.[^ch06-fn082]






Porter drew the conclusion that the postwar death tolls were exaggerated by officials who "had an obvious vested interest [in] not admitting their failure to understand the capacity of the new regime to feed its people." Alternatively, suppose that their postwar estimates are correct. Since the situation at the war's end is squarely the responsibility of the United States, so are the million or so deaths that were predicted as a direct result of that situation.[^ch06-fn083]






The horrendous situation in Phnom Penh (as elsewhere in Cambodia) as the war drew to an end was a direct and immediate consequence of the U.S. assault—prior to the U.S. actions that drew Cambodia into the Indochina war, the situation was far from ideal, contrary to colonialist myths about happy peasants, but it was nothing like the accounts just reviewed by Congressional study missions and health and relief workers. The same is true of the vast destruction of agricultural lands and draught animals, peasant villages and communications, not to speak of the legacy of hatred and revenge. The United States bears primary responsibility for these consequences of its intervention. All of this is forgotten when sole responsibility is assigned to the Khmer Rouge for deaths from malnutrition and disease. It is as if some Nazi apologist were to condemn the allies for postwar deaths from starvation and disease in DP camps, though the analogy is unfair to the Nazis, since the allies at least had the resources to try to deal with the Nazi legacy.






Consider again what lies behind the call for military intervention in Cambodia. The leading State Department specialist estimated killings in the "thousands or hundreds of thousands," and attributed a still larger number of deaths to disease and malnutrition—in significant and perhaps overwhelming measure, a consequence of U.S. terror. Furthermore, a news report that the State Department specialist regards as "excellent" notes that "it is generally accepted" by Cambodia watchers that "summary justice" is not centrally-directed. Another government expert insists that it would be necessary to conquer every village to subdue the Khmer Rouge. But when a leading senatorial dove calls for military intervention, the Wall Street Journal, which backed the U.S. aggression and massacre through the worst atrocities, has the gall to make the following editorial comment:






Now, having finished the task of destroying [the U.S. presence in Indochina, American liberals] are shocked and dismayed by the news of the grim and brutal world that resulted. One of the few good things to come out of the sordid end of our Indochina campaign was a period of relative silence from the people who took us through all its painful contortions. They should have the grace to maintain their quiet for at least a while longer.[^ch06-fn084]






About postwar Cambodia, they have only this to say: the "present Communist rulers have starved, worked, shot, beaten and hacked to death upwards of a million of the country's citizens." Not a word about the U.S. role or continuing responsibility for death and suffering, let alone an effort to evaluate the evidence or to face the "difficult questions" that arise.






It would take a volume to record the material of this sort that dominates the U.S., indeed the Western press. Before turning to the nature of the evidence adduced concerning the scale and character of postwar atrocities in Cambodia, we will cite only one more example selected out of the mass of comparable instances, along with an example of journalistic integrity that is another of the rare exceptions.






On July 31, 1978, Time magazine published a "Time Essay" entitled: "Cambodia: An Experiment in Genocide," by David Aikman. The essay is short on documentation but not sparing in its outrage. The sole documentation offered is the "interview" with Khieu Samphan already cited—an example that was specifically pointed out in advance to a Time reporter preparing background for this article as a probable fabrication—and a statement on Radio Phnom Penh that "more than 2,000 years of Cambodian history have virtually ended," which Aikman presents as a "boast of this atrocity," though other interpretations easily come to mind.






According to Time, "the lowest estimate of the bloodbath to date—by execution, starvation, and disease—is in the hundreds of thousands. The highest exceeds 1 million, and that in a country that once numbered no more than 7 million." Figures apart, what is striking about this claim is that nowhere in the article is there any reference to any U.S. role or responsibility, no indication that deaths from starvation and disease may be something other than a "bloodbath" by the Khmer Rouge.






A major theme of the Time essay is that "somehow the enormity of the Cambodian tragedy—even leaving aside the grim question of how many or how few actually died in Angka Loeu's experiment in genocide—has failed to evoke an appropriate response of outrage in the West," and even worse, "some political theorists have defended it, as George Bernard Shaw and other Western intellectuals defended the brutal social engineering in the Soviet Union during the 1930s"; "there are intellectuals in the West so committed to the twin Molochs of our day—'liberation' and 'revolution'—that they can actually defend what has happened in Cambodia." In fact, the Western press since 1975 has poured forth reams of denunciations of Cambodia in the most strident tones, repeating the most extreme denunciations often on flimsy evidence, in striking contrast to its behavior in the case of massacres elsewhere, as in Timor; the U.S. press is particularly notable for a marked double standard in this regard, though it is hardly alone. And there is good reason why Aikman fails to mention the names of those "political theorists" who have defended "the Cambodian tragedy"—as this would require differentiating those who have exposed media distortions and tried to discover the facts, instead of joining the bandwagon of uncritical abuse, from those who say that no serious atrocities have occurred (a small or non-existent set that Time has searched for, apparently without success).[^ch06-fn085] Specificity also might require publicizing the views of critics of the current propaganda barrage, which would make it difficult to avoid discussion of the crucial U.S. role in postwar suffering and deaths in Cambodia or of the actual nature of what Time regards as "evidence." For Time ideologists, a defender of the "Cambodian tragedy" is one who fails to place all the blame for postwar suffering on the Khmer Rouge and who otherwise contests the patriotic truths handed down by the Reader's Digest and similar sources.






For the ideologists of Time, the Cambodian tragedy is the "logical conclusion" of "bloodbath sociology" associated with socialism and Marxism. The "moral relativism" of the West makes it difficult to see that the Cambodian experience "is the deadly logical consequence of an atheistic, man-centered system of values, enforced by fallible human beings with total power, who believe, with Marx, that morality is whatever the powerful define it to be and, with Mao, that power grows from gun barrels." Unlike the more "humane Marxist societies in Europe today," the Cambodians do not "permit the dilution of their doctrine by what Solzhenitsyn has called 'the great reserves of mercy and sacrifice' from a Christian tradition." As for the significance of the Christian tradition for the Third World—not to speak of the European experience—Time has no more to say than it does about the great reserves of mercy and sacrifice shown by the U.S. leaders who sent their angels of mercy to flatten the villages of Indochina while the editors of Time lauded this noble enterprise.[^ch06-fn086] And it is fitting indeed that they should cite Solzhenitsyn, the profound thinker who denounced the West for failing to carry this enterprise to a successful conclusion, in the spirit of Christian humanism.






To show in contrast that honest journalism remains possible, consider a report by Richard Dudman just after the fall of Phnom Penh.[^ch06-fn087] Dudman was captured in Cambodia while serving as a U.S. war correspondent in Southeast Asia, and wrote an important book on his experiences with the Khmer Rouge.[^ch06-fn088] Dudman writes that "the constant indiscriminate bombing, an estimated 450,000 dead and wounded civilians to say nothing of military casualties, and the estimated 4,000,000 refugees were almost inevitable results of the short U.S. invasion of Cambodia and the subsequent proxy war that ended in defeat for the United States as well as for its client regime in Phnom Penh." Relying in part on his personal experience in captivity, he adds that "the U.S. invasion spread the Communist-led guerrillas through most of Cambodia" and drove the Vietnamese Communists and the Cambodian population "into an alliance as comrades in arms against a common enemy—American tanks and bombs," which were a "catalyst": "we [the Khmer Rouge prisoners] could see Cambodian peasants turning to a friend in need in the form of the military forces of the Vietnamese Communists."






To ignore these basic facts in reporting postwar Cambodia is as disgraceful as to attribute the U.S. legacy of starvation, disease, and bitter hatreds simply to atheistic Communism carried to its "logical conclusion."






Let us now turn to an evaluation of the evidence that is used by the media as support for their denunciations. Simons examined this question in an analysis after his return from several years as Post correspondent in Bangkok.[^ch06-fn089] Accompanying the article is a photograph showing workers under military guard with the following caption: "Photo from smuggled film purports to show forced labor in Cambodian countryside." Simons comments that "a number of journals, including the Washington Post, Newsweek, Time and Paris Match, have published several photographs purporting to show atrocities in Cambodia." But he continues:






Several U.S. and other experts believe that these pictures were posed in Thailand. "They're fakes," commented a State Department officer who has followed Cambodian affairs closely since before the end of the war.






As we shall see there is more to the story: the photographs continued to be published long after they were exposed as frauds, and corrections were refused by the journals that published them.






Simons next turns to the interview in which Khieu Samphan is alleged to have conceded that the Khmer Rouge are responsible for a million deaths, which he writes, was "subsequently referred to in the New York Times Magazine." He adds that the very occurrence of that interview is denied by François Ponchaud. Again, as we shall see, there is more to the story.






Simons then makes the following interesting observation:






Oddly, those few Western governments which have diplomatic relations with Cambodia generally refuse to accept the genocide allegation. "We'd need a lot more evidence before we'd be ready to believe such a serious charge," said an ambassador from a Scandinavian country. Representatives of his government have visited Phnom Penh several times since the war ended.






This lead too deserves to be explored. It is indeed "odd" that Western visitors to Phnom Penh refused to join the chorus. At the very least, a rational person might well heed Simons' observation that "reports about Cambodia should be treated with skepticism."






Simons offers other reasons for skepticism. Noting that "just one member of the U.S. embassy staff in Thailand [presumably, Twining] is assigned to monitoring Cambodian affairs," Simons comments:






Most information gathered by this official and by journalists in Southeast Asia comes from interviewing Cambodian refugees who have fled to Thailand. Almost all of these refugees come from the northwestern part of Cambodia, an area which was never well controlled by the Communists and where reprisals by long-embittered guerrillas were fierce in the months immediately following the Communist victory. From this bare-bones intelligence gathering, nationwide projections have been drawn. It is these projections that have led to the conclusion that Cambodian leaders are genocidal monsters and that the torment of this once-gentle land has no parallel in modern history.






Again, what Simons reports has been emphasized by specialists to whom we return.[^ch06-fn090] The State Department's Cambodia watcher, Charles Twining, comments that "our information is just inadequate. Most of it is from northwestern Cambodia and we have virtually nothing from northeastern Cambodia, so it is awfully hard to put together a significant figure and I think none of us want to give an estimate [of deaths]."[^ch06-fn091]






Simons cites Gareth Porter's comment that the forced evacuation of urban centers "was well-advised, though 'heavy-handed.'"[^ch06-fn092] He quotes Porter as follows:






The fact is that the evacuation and the regime's concentration on rice production have averted mass starvation. If you look at the three Indochinese countries today, you'll find that Cambodia undoubtedly is in the best food position.






Simons continues: "This claim is more or less supported by State Department officials," who say "people are probably eating better" and note reports of rice exports. We will return to reports by visitors that confirm these conclusions, contrary to the standard picture presented by the media of mass starvation or even systematic policies of starvation undertaken by the leadership, as Lacouture and others contend. It is particularly worthy of note that visitors in late 1978 found food supplies to be more than adequate. The severe floods of the preceding months had a devastating effect on agricultural production throughout the region, causing a very serious shortage of food in neighboring countries. Some reports indicate that Cambodia may have been the hardest hit of all the countries of the region,[^ch06-fn093] but it seems that the extensive development of dikes and dams in the postwar period, which has consistently impressed visitors, sufficed, despite some damage, to overcome the worst effects and to afford the population an ample supply of food, even including a surplus for export, according to the regime; an achievement that U.S. specialists describe as "spectacular" if true.[^ch06-fn094]






Simons takes note of the U.S. attack on Cambodia and gives an accurate account of doubts raised by critics of the Western propaganda system, whom he misleadingly describes as "supporters of the Cambodian regime" (or "defenders," or "friends," of the regime); concern for factual accuracy carries no such implication. He asks why the most extreme conclusions about Cambodia have been "widely accepted" despite their often flimsy basis, and suggests two reasons: "First, while figures may be subject to doubt, what's the difference between whether tens of thousands or a million people have been killed?"[^ch06-fn095] Second, the refusal of the government to permit outside observers itself suggests that they are attempting "to hide some horrible secret." Simons argues that these points "have acceptable moral bases" but "sidestep key issues." Reprisals have been common after other wars, and while the Cambodian government's policy towards foreigners "may be judged extreme xenophobia, it does not prove that genocide is being carried out behind the bamboo curtain." We are more skeptical about the moral basis for these points, for reasons already discussed. We wonder, for example, whether the reaction would be the same if some critic of the United States were to charge that U.S. troops had killed 40,000 civilians at My Lai, then responding to a correction by asking what's the difference—just a factor of a hundred. Recall further that it is the more sensational claims that have been endlessly repeated by the media and have led to a call for military intervention in Cambodia. As for Cambodian "xenophobia," it is worth considering just what the experience of Cambodian peasants has been with the West, not only under French colonialism but also in the few years of the war.[^ch06-fn096] Does the term "xenophobia" accurately convey their reaction?






This report, by one of the few serious U.S. correspondents who have recently worked in Southeast Asia, stands alone in the U.S. mass media, to our knowledge, in its fairness and accuracy in presenting the views of critics of the media barrage and its concern for the quality of available evidence, though Simons's skepticism, like that of many other close observers, has been drowned in the deluge.






Let us now consider in detail the several points that Simons raised. To begin with, consider the photograph that appeared along with Simons's article. This is one of several that have, as he notes, been widely circulated in the press as sure proof of Communist barbarism.






On April 8, 1977, the Washington Post devoted half a page to "photographs believed to be the first of actual forced labor conditions in the countryside of Cambodia [to] have reached the West." The pictures show armed soldiers guarding people pulling plows, others working fields, and one bound man ("It is not known if this man was killed," the caption reads). Quite a sensational testimonial to Communist atrocities. But there is a slight problem. The Post account of how they were smuggled out by a relative of the photographer who died in the escape attempt is entirely fanciful. Furthermore, the photos had appeared a year earlier in France, Germany, and Australia, as well as in the Bangkok Post (19 April 1976), where they appeared under the caption "True or False?" This strongly anti-Communist journal turned down an attempt by a Thai trader to sell them the photos "because the origin and authenticity of the photos were in doubt." The photos appeared in a Thai-language newspaper two days before the April 4th election. The Bangkok Post then published them, explaining that "Khmer watchers were dubious about the clothes and manner of the people depicted, and quoting "other observers" who "pointed to the possibility that the series of pictures could have been taken in Thailand with the prime objective of destroying the image of the Socialist parties" before the election. This speculation seems eminently reasonable. Westerners in Southeast Asia have reported that the Thai press, including the Bangkok Post, was exploiting "horror stories" from Cambodia to undermine the Socialist parties in Thailand.[^ch06-fn097]






The facts were reported in the U.S./Indochina Report of the Washington-based Indochina Resource Center in July, 1976, along with the additional information that a Thai intelligence officer later admitted that the photos were indeed posed inside Thailand: "'Only the photographer and I were supposed to know,' he confided to a Thai journalist." The full details were again given in the International Bulletin (circulation 6,000).[^ch06-fn098] A letter of April 20 to the Washington Post correcting its story was not printed, though "the Post published a short item acknowledging the doubts, but pointing out that the pictures had been published elsewhere."[^ch06-fn099] The "freedom of the press" assures that readers of the International Bulletin could learn the true facts of the matter concealed by the mass media.






We reviewed the story thus far shortly thereafter.[^ch06-fn0100] But it continued to evolve. The major newsweeklies did not want to miss the opportunity to offer their readers visual evidence of Khmer Rouge tyranny, and could not be deterred merely because the evidence was faked—repeated exposure has rarely dimmed the lustre of other familiar propaganda tales, such as the North Vietnamese land reform bloodbath of the 1950s, discussed in Volume I. On November 21, 1977, Time magazine ran the photo of the bound man. While the Washington Post had withheld judgment on whether the victim was killed in the staged photo, doubts had now been eliminated and Time assured the reader that he was executed. Several letters were sent to Time reporting the facts just reviewed and also noting that their fakery went beyond that of the Washington Post. Those who had wasted their efforts alerting Time to the facts were rewarded by the following response:





[^ch06-fn001]: We would like to thank Stephen Reder, Ben Kiernan, Torben Retbøll, Laura Summers, Serge Thion and Michael Vickery for important information and very helpful comments on an earlier draft of this chapter.











During the period of this review—mid-1975 to the end of 1978—the regime used the name "Democratic Kampuchea." With some misgivings, we will continue to use the conventional English spelling, "Cambodia," throughout. Again with misgivings, we will use the term "Khmer Rouge" to refer to the revolutionary movement of Cambodia and to the regime during the period of our review. See Volume I, chapter 1, note 56.






[^ch06-fn002]: François Ponchaud, Cambodia: Year Zero, Holt, Rinehart and Winston, 1978; a revised and updated translation of his Cambodge: année zéro, Julliard, 1977, which became perhaps the most influential unread book in recent political history after a review by Jean Lacouture, to which we return. It is also unusual in that it is the only recent French book on Cambodia to have been not only widely quoted and misquoted, but also translated. In contrast, important French studies of the colonial period and the U.S. intervention have gone unreviewed, unnoticed and untranslated, as was the case with Lacouture's book on Vietnam, mentioned above: for example, Charles Meyer, Derrière le sourire Khmer, Plon, 1971; Jean-Claude Pomonti and Serge Thion, Des courtisans aux partisans, Gallimard, 1971 (for some discussion of these books, see Chomsky, For Reasons of State, chapter 2). Ponchaud, a French priest who lived in Cambodia for ten years, is the best-informed and most careful of those who have done extensive critical work on postwar Cambodia, though his study is not without serious flaws. For tens of millions of readers in the United States and throughout the world, the major source of information is no doubt John Barron and Anthony Paul, Murder of a Gentle Land: the Untold Story of Communist Genocide in Cambodia, Reader's Digest Press, Crowell, 1977, expanded from an article in the Reader's Digest, February 1977. Subsequent references to Ponchaud will be to the U.S. edition cited above, unless explicitly noted. We stress that references are to the U.S., not the British edition, which differs in crucial respects, as we shall see.






[^ch06-fn003]: We will return to a few examples. As one indication of the power of the U.S. propaganda system, consider a study of the "Ten Best Censored Stories of 1977" described as "a nationwide media research project" with "a panel often nationally recognized individuals"; one of us (Chomsky) was among them, along with journalist Shana Alexander, Ben Bagdikian of the Graduate School of Journalism at Berkeley, Congresswoman Shirley Chisholm, Nicholas Johnson (chairman of the ­National Citizens Communications Lobby), Victor Marchetti (former CIA agent who has written important exposés of the intelligence system) and other well-known journalists, writers, and media specialists. The panel selected "Massacre in Cambodia and Vietnam" as one of the ten best censored stories (news release, Office of Public Affairs, Sonoma State College, 9 August 1978). Putting aside any question as to the facts of the matter, this story does not even merit consideration in a study of "censorship," given the actual media coverage.






[^ch06-fn004]: We do not want to imply that this is the only reason why journalists sought out dissenting opinion. In the case of Cambodia, as in the other cases we have discussed, there remains a current of honest journalism though it is often buried under the avalanche of propaganda.






[^ch06-fn005]: Ponchaud, Author's note for the American translation, dated 20 September 1977, op. cit., p. xvi.






[^ch06-fn006]: For example, Morton Kondracke, "How Much Blood Makes a Bloodbath?' New Republic, 1 October 1977: "Perhaps the United States does bear some responsibility [note the admirable caution], but the doves themselves had better explain why similar things haven't happened in Vietnam... ." Why is it the responsibility of those who opposed the U.S. intervention that converted a civil struggle into a murderous war to "explain" the consequences that ensued?






[^ch06-fn007]: Dissent, Fall 1978. Evidently, the question can be raised only if one accepts two assumptions: 1) the U.S. intervention in Indochina would have prevented a Cambodian bloodbath or was designed for this purpose; 2) the United States has the right to use force and violence to prevent potential crimes—and thus, a fortiori, to resort to force to prevent actual crimes by invading Indonesia, much of Latin America, etc. It is difficult to decide which of the two assumptions that are jointly required for the question even to be raised is the more absurd.






[^ch06-fn008]: Human Rights in Cambodia, Hearing before the Subcommittee on International Organizations of the Committee on International Relations, House of Representatives, Ninety-Fifth Congress, First Session, 3 May 1977 (henceforth, May Hearings), p. 40; see also the Hearing before the same subcommittee, 26 July 1977 (henceforth, July Hearings). Government Printing Office, Washington, 1977.






[^ch06-fn009]: See his prepared statement, July Hearings, pp. 19-32. See also George C. Hildebrand and Gareth Porter, Cambodia: Starvation & Revolution, Monthly Review Press, 1976.






[^ch06-fn010]: In fact, Pike is a State Department propagandist whose effusions are often simply embarrassing. For some examples, see Chomsky, American Power and the New Mandarins, pp. 365-66.

[^ch06-fn011]: AP, Boston Globe, 22 August 1978. See also Washington Post, August 22; editorial, Boston Globe, August 23, reprinted in the Christian Science Monitor, August 28; Wall Street Journal, August 22 and editorial August 23; William F. Buckley, Boston Globe, 29 August 1978. The New York Times was on strike and not publishing.






[^ch06-fn012]: Congressional Record, 22 August 1978, S 14019.






[^ch06-fn013]: McGovern introduced the transcript into the Congressional Record, August 22, S 14020.






[^ch06-fn014]: Congressional Record, 25 August 1978, S 14397.






[^ch06-fn015]: We choose a factor of a hundred for illustration because of Jean Lacouture's observation, to which we return, that it is a question of secondary importance whether the number of people killed was in the thousands or hundreds of thousands.






[^ch06-fn016]: See note 53, this chapter. Given the wording McGovern used, it is likely that his actual source was a widely quoted allegation by Jean Lacouture that the regime was "systematically massacring, isolating and starving" the population and had "boasted" of having killed some 2 million people. See the reference of note 17. As we shall see, even after Lacouture published a correction, stating that there was no basis for the latter charge, it continues to be reiterated by people who are aware of the correction, along with his more general claim, for which he also provided no evidence that withstands inquiry.






[^ch06-fn017]: See his "The bloodiest revolution," New York Review of Books, 31 March 1977, a review of Ponchaud's Cambodge: année zéro, translated from Le Nouvel Observateur. See also his "Cambodia: Corrections," New York Review, 26 May 1977. Also his review of Barron-Paul, New York Times Book Review, 11 September 1977.






[^ch06-fn018]: Ponchaud, op. cit., p. xvi. His estimate of refugees is conservative as compared with some others. We noted earlier a recent estimate of 14,000 Cambodians in Thai refugee camps (others have already been resettled) in addition to an alleged 150,000 who have fled to Vietnam. According to Vietnamese sources, there have been 330,000 refugees and displaced persons from Cambodia since April 1975, including 170,000 of Vietnamese origin, almost all women, children and older people (UN High Commissioner for Refugees, Information Note, Hanoi, 31 July 1978). Based indirectly on this source, the U.S. press has given estimates of 500,000 refugees from Cambodia (Editorial, Boston Globe, 23 August 1978; the record will show that Hanoi sources have rarely been given such credence and publicity; in this case, the journal was unaware of the original source.) On the exodus of Vietnamese refugees from Cambodia, see Laura Summers, "Human Rights in Cambodia," paper delivered at the International Studies Association, Washington, D.C., February 1978. She estimates that the Vietnamese population of Cambodia was about 450,000 before the war in 1970 and 310,000 were expelled or fled (along with 20,000 detained) during "the racialist campaign against Vietnamese Kampucheans by Lon Nol's 'Khmer Republic'" (her source is the well-known demographer Jacques Migozzi, Cambodge: faits et problèmes de population, CNRS, Paris, 1973). See T.D. Allman, cited in Volume I, chapter 3, note 20. Note that this exodus of over 300,000 people during the racialist campaign by the government backed by the United States has been quietly absorbed by the propaganda system, and that Lon Nol is now apparently offered as a serious source for allegations backing a proposal for military intervention in Cambodia. We return to Lon Nol's earlier exploits.






[^ch06-fn019]: See chapter 2, section 2.






[^ch06-fn020]: Ponchaud, op. cit., p. xvi.






[^ch06-fn021]: Henry Kamm, "Cambodians, Held in Thai Police Cages for IJlegal Entry, Await Future Apathetically," New York Times, 10 May 1978. See also note 170 of this chapter. On Kamm's Pulitzer Prize, see p. 58, above.






[^ch06-fn022]: Op. cit., p. 211.






[^ch06-fn023]: Ibid., p. xiii.






[^ch06-fn024]: To be precise, Porter cites a similar comment from their Reader's Digest article, where they write that the "promising subjects" were selected with the "guidance" of the campleader. May Hearings, p. 23.






[^ch06-fn025]: Op. cit., p. 187.






[^ch06-fn026]: Richard C. Holbrooke, Assistant Secretary for East Asian and Pacific Affairs, Department of State, July Hearings, p. 23.






[^ch06-fn027]: July Hearings, p. 6.






[^ch06-fn028]: See the discussion in chapter 2, section 1.






[^ch06-fn029]: May Hearings, p. 22, citing CBS Evening News, 26 January 1976; Washington Post (8 April 1977). See also the letter to the Economist (London) by Torben Retbøll, 26 August 1978.






[^ch06-fn030]: 20 January 1978, in Washington. This is a private group supporting U.S. military build-up.






[^ch06-fn031]: Battleline, May 1978, publication of the American Conservative Union, featured in an issue devoted to atrocities in Cambodia.






[^ch06-fn032]: Excerpts appear in Worldview, May 1978.






[^ch06-fn033]: AIM Report, May 1978, Part II, reprinted as a full-page advertisement in the Washington Post (2 June 1978). Accuracy in Media, which publishes the AIM Report, is a well-financed right-wing group which is concerned that the media do not adhere to the doctrines of state propaganda with sufficient loyalty, and under the guise of defending "accuracy" exerts pressures of various kinds to overcome this unfortunate situation. The alleged failure of the media to give sufficient attention to "the Cambodian holocaust" is one of their staples.






[^ch06-fn034]: Le Monde, 7, 8 September 1977, 25 October 1977. There was, in fact, a CIA-run secret school in Laos for training Cambodian Army guerrillas that was closed down by the agency when a high-ranking officer who was an aide to the brother of Prime Minister Lon Nol was arrested by the Lao police for heroin smuggling. See Alan Dawson, Pacific Stars & Stripes, 12 October 1971.






[^ch06-fn035]: "Cannibalism in Cambodia doubted," Bangkok Post (24 January 1978).






[^ch06-fn036]: Neil Kelly, "Vietnamese refugee walked 350 miles across Cambodia to Thailand," London Times (30 January 1978).






[^ch06-fn037]: Note that he should have witnessed or learned directly of the worst excesses. According to Ponchaud, "the early months were those of blackest terror....The executions continued after the early months of the massive purge of the former regime's civilian and military cadres and the many recalcitrant elements, but they became less frequent and less summary" (pp. 64, 69). Other sources agree, as we shall see below. Even people who should be ranked among outright propagandists agree that there must have been "some diminution of the killings" (Leo Cherne, MacNeil/Lehrer Report; see note 53). Cherne explains this on the grounds that the population had been reduced from 8 to 5 million, so that there were just fewer people left to kill. On his source for the 5 million figure, see note 118.






[^ch06-fn038]: Aftenposten (Norway), 22 April 1978, translated in FBIS, 28 April 1978, Cambodia, H1-2.






[^ch06-fn039]: John Fraser, "Pushy Russian replaces Ugly American," Toronto Globe and Mail (27 November 1978).






[^ch06-fn040]: Michael Vickery, personal letter of September 24, 1977, which he has authorized us to cite. In this letter he expresses his pessimism about developments in Cambodia, along with a good deal of skepticism about finding out the truth.






[^ch06-fn041]: See, for example, Wall Street Journal, editorial (18 July 1978), which offers "Prof. Chomsky's heroic efforts to disprove the Cambodian bloodbath through textual criticism of witnesses' statements" as an example of "intellectual levitation" on a par with apologetics for Mao, scholastic debate over the Shaba incursion, or the "passionate" argument of specialists on Africa that "Mau Mau outbreaks in Kenya were a spontaneous response to colonial oppression." Putting aside these interesting examples, the fact is that apart from letters to journalists who have invented or spread known falsehoods, these "heroic efforts" reduce to the single article cited below (note 100), which notes that refugee reports "must be considered carefully" though "care and caution are necessary" for obvious reasons. No attempt whatsoever was made to "disprove the Cambodian bloodbath." The article states that "we do not pretend to know where the truth lies amidst these sharply conflicting assessments" cited by experts, of which the more extreme are selected (and distorted) by the press. Furthermore, these perhaps less than heroic efforts contain no specific discussion of witnesses' statements but rather document falsehoods and misrepresentations by those who have made use of these statements, as well as the continuing efforts by the Wall Street Journal and others to devise apologetics for atrocities within the U.S. sphere. Excerpts from a letter correcting these typical falsehoods appeared in the Wall Street Journal, 7 August.






[^ch06-fn042]: See, for example, Norman Peagam, "Good crops and grim terror in Cambodia," New Statesman, 4 August 1978, or his briefer report in the New York Times (19 July 1978). Peagam makes the important point that "refugees in Thailand and Vietnam give virtually identical accounts," which he reports graphically—and in this case, credibly.






[^ch06-fn043]: As noted above, p. 134, the Free Press preferred to ignore these reports too, though they were certainly known to editors of leading journals.






[^ch06-fn044]: Leo Cherne, "The Terror in Cambodia," Wall Street Journal (10 May 1978).






[^ch06-fn045]: Leo Cherne, "Why we can't withdraw," Saturday Review, 18 December 1965. On a government-sponsored study of how U.S. air and artillery attacks by causing "damages and casualties to the villagers" impel them "to move where they will be safe from such attacks...regardless of their attitude to the GVN," and the reaction by U.S. officials and apologists, see Chomsky, For Reasons of State, pp. 5, 142. In the same article, Cherne observes that "there should be no illusion about the consequences" of "an American withdrawal from Vietnam": "There will be a bloody purge of the non-Communist leaders and intellectuals."






[^ch06-fn046]: "Cambodia: Corrections." See note 17 of this chapter. The significance of his reference to "deciding exactly which person uttered an inhuman phrase" will be explained below.






[^ch06-fn047]: On Operation SPEEDY EXPRESS, see Volume I, chapter 5, section 1.3.






[^ch06-fn048]: As we shall see, the evidence he reported was seriously in error throughout, and the sources on which he relied prove to be quite dubious on further inquiry. Lacouture's corrections, which were partial and somewhat misleading, were published in the United States when the errors were brought to his attention here, but never in France, where the article originally appeared.






[^ch06-fn049]: See chapter 2, section 2. Recall the estimate by the "victim of the liberation," Pleyber-Grandjean, that the resistance had massacred 7 million people; quite evidently an exaggeration, though with some factual basis in tens of thousands of killings, but at least not widely disseminated as authoritative in the mass media of France and Germany, and not beyond correction.






[^ch06-fn050]: This quote from Lacouture appears on the cover of the U.S. version of Ponchaud's Cambodia: Year Zero.






[^ch06-fn051]: To illustrate the issues at stake, consider the following example of a very general phenomenon in the industrial West. A U.S. newspaper in 1978 ran a cartoon showing a picture of a confused Nicaraguan citizen with Somoza on one side and a guerrilla with a gun on the other. The caption defined the alternatives he faced: Somoza's corruption and oppression on the one hand, "liberation or worse" on the other. It is important in the current phase of the Western system of indoctrination to establish in the popular mind the principle that liberation is a terrible fate for subject peoples, a major reason for the current campaigns of abuse and deceit with regard to Indochina.






[^ch06-fn052]: Or, where possible, on independent evidence as to the credibility of those who present reports and interpretations.






[^ch06-fn053]: Here are some scattered examples. From the New York Times: (9 July 1975) editorial "scores genocidal policies of Cambodia's Khmer Rouge rulers," comparing them to "Soviet extermination of Kulaks or with Gulag Archipelago" and "says silence by US Cong[ress] members and UN must be broken" (quoted from index); (20 October 1975) editorial with similar content; (27 March 1976) editorial contends that Cambodia is a "vast slave labor camp" ruled by "fanatical Communist leaders"; (12 April 1976) article cites Time report that 500,000 Cambodians have perished since April 1975; (3 June 1976) citing a journalist of France Soir: "the figure of a million victims since April 17, 1975, the day of the 'liberation' of Phnom Penh, is plausible, if not certain"; David A. Andelman (2 May 1977) "The purges that took hundreds of thousands of lives in the aftermath of the Communist capture of Phnom Penh on April 17, 1975, have apparently ended, for the most part...; (27 July 1977) "Up to 1.2 million people may have been killed under the Communists in Cambodia, a high State Department official said today," citing Richard Holbrooke, who in fact testified that "Journalists and scholars...guess that between half a million and 1.2 million have died since 1975" (our emphasis, July Hearings, p. 2); C.L. Sulzberger (27 August 1977): "estimates of the number deliberately slaughtered by the Communist regime run from two hundred thousand to one million"; editorial (3 July 1978): "The estimates are that many hundreds of thousands, perhaps even 2 million Cambodians out of a population of 8 million, have been killed or allowed to die of disease and starvation." Christian Science Monitor: editorial (26 April 1977), "Reports put the loss of life as high as 2 million people out of 7.8 million total"; editorial (31 August 1978) citing State Department officials: "The U.S. government is confident that scores, probably hundreds of thousands of people have been killed." Washington Post, Don Oberdofer (20 April 1978) citing the former minister of Information of the Lon Nol government: "1 million Cambodians have been 'slaughtered' and another million 'appear to have perished from disease and starvation'"; Jack Anderson (2 May 1978): "Competent sources have offered estimates ranging from 1.8 million to 2.5 million...who...have died from mistreatment and execution"; Jack Anderson (3 May 1978): "The death toll from beatings shootings, starvation and forced labor may have reached 2.5 million victims ..."; Smith Hempstone (7 May 1978): "It appears certain that between 500,000 and 2 million Cambodians...have been executed, starved or worked to death, died of disease or been killed while trying to flee ..." Boston Globe: UPI (17 April 1977): "Most foreign experts on Cambodia and its refugees believe at least 1.2 million persons have been killed or have died as a result of the policies of the Communist regime...Some experts...believe as many as 3.5 million people—half of the total population—have been killed or have died in the past two years;" (12 September 1977): Lon Nol reports that "more than 2.5 million Cambodians have been killed since the Communist Khmer Rouge conquered his country." Business Week, 23 January 1978: "As many as 2 million may have died out of a population of 5.5 million." MacNeil/Lehrer Report (TV, 6 June 1978): "In the worst accounts some two million people are said to have been killed by the new Communist regime" (the government specialist Timothy Carney estimated the number of deaths, not by "mass genocide" but by "brutal, rapid change" at "hundreds of thousands"). Many similar examples can be given overseas; to select just two: Die Zeit, (23 April 1976): "500,000 to 1.5 million people have died, been executed or starved"; Izvestia, (9-10 December 1978) alleging 2 million "executions" in Cambodia (Le Monde, 12 December 1978).











We will return to a few other examples of the great many that might be cited from the fall of Phnom Penh to the present.






[^ch06-fn054]: AP, 22 August 1978. See note 11 of this chapter.






[^ch06-fn055]: July Hearings, pp. 4, 15.






[^ch06-fn056]: May Hearings, pp. 40-41.






[^ch06-fn057]: Ibid., p. 14.






[^ch06-fn058]: Ibid., p. 17.






[^ch06-fn059]: See Volume I, chapter 3, section 5.4, for discussion of his role.






[^ch06-fn060]: Kenneth M. Quinn, "Political Change in Wartime: The Khmer Krahom Revolution in Southern Cambodia, 1970-1974," Naval War College Review, Spring 1976.






[^ch06-fn061]: See note 108, this chapter.






[^ch06-fn062]: Le Monde, 8 September 1977.






[^ch06-fn063]: Compare the contemptuous remark of another refugee, who complained that "Now all village chiefs are selected from among the poorest and the most illiterate," cited by Laura Summers, "Defining the Revolutionary State in Cambodia," Current History, December 1976, from Le Monde, 18-19 April 1976. Such comments perhaps give some insight into Twining's "difficult question."






[^ch06-fn064]: The same is true of the fierce resistance to the full-scale Vietnamese invasion of December 1978-January 1979. See the preface to this volume. We will keep here to the time frame preceding this invasion, as throughout this chapter. On the border conflicts, see Heder's articles cited in note 19 of the preface.






[^ch06-fn065]: Washington Post (22 August 1978).






[^ch06-fn066]: See note 12 of this chapter.






[^ch06-fn067]: Philadelphia Inquirer (7 May 1978).






[^ch06-fn068]: Frederic A. Moritz, "Cambodia's surprising 'win' over Vietnam," Christian Science Monitor (28 March 1978).






[^ch06-fn069]: David Binder, "Cambodia-Vietnam Battles Spur U.S. Concern over 'Proxy' War," New York Times (25 December 1978). Note that this analysis, which appeared on the day that Vietnam stepped up its dry season offensive to a full-scale attack with 100,000 troops, appeared well after Vietnamese efforts to establish a Cambodian liberation front, with a program tailored to what are assumed outside of Cambodia to be the needs and concerns of the local population. See Nayan Chanda, "Pol Pot eyes the jungle again," Far Eastern Economic Review, 15 December 1978. Chanda points out that "None of the 14-member central committee of the KNUFNS [the Vietnamese-established front]...are nationally known figures." The one well-known Cambodian whom rumor had associated with KNUFNS, So Phim, "who was earlier reported to be leading anti-Pol Pot resistance, is dead." Chanda, FEER, 26 January 1979. As noted in the preface, the Vietnamese plainly do not believe that the KNUFNS can control the population without an army of occupation that far outnumbered the Pol Pot forces even before the massive Vietnamese assault that is reported to have destroyed a substantial part of the Cambodian army.






[^ch06-fn070]: Recall the experience of Russia during World War I, or even World War II, when Hitler succeeded in raising a substantial army in support of the invasion of Russia and, according to some analysts, might have achieved his ends if Nazi atrocities had not helped organize the massive resistance that played the major role in the ultimate allied victory. Or recall even the experience of Western Europe, where Germany had little difficulty in organizing local support after its conquests.






[^ch06-fn071]: Op. cit. (see note 11). He is referring to the unwillingness of a refugee who had allegedly seen nine members of his immediate family killed to support a foreign invasion.






[^ch06-fn072]: Op. cit., pp. 139-143. Recall some of Henry Kissinger's thoughts on the inability of people of the Third World to comprehend "that the real world is external to the observer" because their "cultures...escaped the early impact of Newtonian thinking," leading to a "difference of philosophical perspective" that is "the deepest problem of the contemporary international order." For discussion of these and comparable profundities, see Chomsky, "Human Rights" and American Foreign Policy, Spokesman, 1978, chapter 1.






[^ch06-fn073]: Lewis M. Simons, "Experts list disease as No. 1 killer in Cambodia today," Washington Post (24 July 1977). In congressional testimony, Twining questioned Simons's "source on this reevaluation" while agreeing with the contents of this "otherwise excellent article." Specifically, "I am convinced that the number of people who have died from disease and malnutrition has been even greater than those executed" (July Hearings, p. 8). On the number killed, he offers the estimate: "Certainly thousands or hundreds of thousands." Twining blames the government of Cambodia for the deaths from disease, claiming that they rejected drugs and medicines. Ponchaud reports that from August 1976, with the resumption of foreign trade, medicines have been imported, along with U.S.-produced DDT, including antimalaria drugs sent in 1976 from the AFSC (pp. 94-97, 116). See also the corrections to Twining's statement by Richard Holbrooke, July Hearings, p. 16; also the references of note 250, below.






[^ch06-fn074]: July Hearings, p. 2.






[^ch06-fn075]: Ibid., p. 23.






[^ch06-fn076]: MacNeil/Lehrer Report; see note 53.






[^ch06-fn077]: See Poole's remarks on the evacuation, p. 176 above.






[^ch06-fn078]: New York Times (9 May 1975).






[^ch06-fn079]: New York Times (14 July 1975).






[^ch06-fn080]: This is one of the arguments offered by Cambodian authorities for the forced evacuation of the urban centers. The second reason regularly advanced is the fear of CIA-backed subversion by groups left in Phnom Penh (cf. Ponchaud, op. cit., p. 19, citing a statement of September, 1975). These reasons are continually rediscovered by the U.S. press: e.g., New York Times (29 July 1978), reporting that "for the first time" the government alleged that "the revolutionaries considered the city to be full of agents, ammunition dumps and conspiracies to undermine the new regime, and therefore felt total evacuation to be necessary for defense." The second argument has more force than is commonly alleged. See Snepp, Decent Interval, pp. 339-40, who reports that the evacuation "left American espionage networks throughout the country broken and useless." As for the first motive, Ponchaud disputes it. We return to his reasons below, 313.






[^ch06-fn081]: See note 9 of this chapter. Quotes are from pp. 25-29. See pp. 30f. on the U.S. role in the politics of starvation for the mass of the population while the elite pursued the good life.






[^ch06-fn082]: May Hearings, p. 30. Porter cites a U.S. intelligence study on Cambodia leaked to the press by Henry Kissinger, discussed in the Washington Post (23 June 1975) and Far Eastern Economic Review, 25 July 1975. A U.S. AID report of April 1975 concluded that widespread starvation was imminent and "Slave labor and starvation rations for half the nation's people...will be a cruel necessity for this year, and general deprivation and suffering will stretch over the next two or three years ..." William Shawcross, Sideshow. Simon & Schuster, 1979, p. 375.






[^ch06-fn083]: On this matter, Laura Summers comments (op. cit., see note 63): "By all accounts, however, universal conscription for work prevented a postwar famine." This appeared in December, 1976. Perhaps by now one should write "by all serious accounts," or at least the vast majority of them. We have already cited Poole and Simons (with Twining's concurrence). Comparable judgments from sources by no means sympathetic with the regime will be noted below.






[^ch06-fn084]: "McGovern the Hawk," Wall Street Journal (23 August 1978). Note that it is only the end of the Indochina campaign that was "sordid," and that the Journal feels no need to observe the injunction of silence, after its disgraceful record of subservience to state power and apologetics for barbarism. Note also the suggestion of the editors that it was the critics who took us through the painful contortions of the Vietnam war, not the war managers. The Journal also pretends that the silence of the activists is of their own choice, rather than a case of simple refusal of access by the mass media.






[^ch06-fn085]: One of us (Chomsky) was approached by Time in the preparation of this article in a transparent effort to elicit a favorable comment from a "supporter of the Khmer Rouge." Instead, Time was offered a (very partial) record of fabrications with regard to Cambodia for which Time and other journals are responsible.






[^ch06-fn086]: In his review of U.S. wartime journalism, Peter Braestrup comments that "In 1962-66,...Time policy on Vietnam was hawkish, even euphoric" (Big Story Volume I, Westview Press, 1977, p. 45). While this study contains so many errors that little in it can be assumed to be true, in this case Braestrup is correct. See the references of note 22, chapter 2 of this volume. Later, Time policy was no longer euphoric, though it remained hawkish.






[^ch06-fn087]: Richard Dudman, "The Cambodian 'People's War,'" Washington Post (24 April 1975).






[^ch06-fn088]: Richard Dudman, Forty Days with the Enemy, Liveright, 1971. He reported here that "the bombing and shooting was radicalizing the people of rural Cambodia and was turning the countryside into a massive, dedicated, and effective revolutionary base," p. 69, referring to the U.S. attack, an insight that has been rapidly forgotten and is in fact denied in some of the more disreputable literature on postwar Cambodia.






[^ch06-fn089]: Lewis M. Simons, "The Unknown Dimensions of the Cambodian Tragedy," Washington Post (19 February 1978).






[^ch06-fn090]: It is worth noting that the northwestern areas were then subject to Thai-supported anti-Communist guerrilla sabotage activities (see Stephen Heder, "Thailand's Relations with Kampuchea: Negotiation and Confrontation along the Prachinburi-Battambang Border," mimeographed, Cornell University, December 1977). An internal Amnesty International paper of 14 June 1976 notes that in that region "there are still many aspects of civil war." During the period 1972-75 parts of this region were under Thai military domination in part sanctioned by agreements with the Lon Nol government, and there were also instances of land grabbing. The Thai had also annexed and plundered the region in collaboration with Japanese fascism in 1941-45. We are indebted to Laura Summers for this information. The CIA-supported Khmer Serei also operated in this area from Thai bases for many years. As we shall see below, Lon Nol conducted brutal attacks on the peasants of the region in the early 1950s. Thus there is a long historical background that helps explain why this region should be the focus of violent revenge.






[^ch06-fn091]: July Hearings, p.22.






[^ch06-fn092]: Cf. Poole, p. 176, above, and the evidence cited on pp. 182f.






[^ch06-fn093]: See the Economist (London) 21 October 1978, reviewing the effects of the floods in Southeast Asia: "As usual, there is no reliable information about what goes on inside Cambodia, but agricultural experts say it could be the worst hit of all. At one time, most of the country looked like a gigantic lake. Much of the vast Tonle Sap-Mekong basin is still under water. There seems little doubt that the waters have brought new hardships to this unhappy country." To the surprise of most observers, the grim prediction does not appear to have been realized, though we have yet to read a comment on this fact or its import in the major media.






[^ch06-fn094]: See p. 239 below. Also, FEER Asia 1979 Yearbook.






[^ch06-fn095]: Presumably, he has in mind Lacouture's remark on the relative insignificance of a factor of a hundred and his original allegation that the regime had "boasted" of having killed some 2 million people.






[^ch06-fn096]: During the U.S. war in Vietnam, it was common for reporters and others to comment on the curious "xenophobia" of the Vietnamese, which makes it so hard to deal with them. Apparently it is a curious trait of peasant culture, as yet unexplained by contemporary scholarship, to react with a demonstration of xenophobia when foreign powers drop cluster bombs on villages after many years of colonial domination. Yet another aspect of the mysterious Asian mind.






[^ch06-fn097]: See below, p. 250.






[^ch06-fn098]: Berkeley, 25 April 1977.






[^ch06-fn099]: Douglas Z. Foster, "Photos of 'horror' in Cambodia: fake or real?" Columbia Journalism Review, March/April 1978. No date is given. Foster also reviewed the basic facts briefly in More (February 1978).






[^ch06-fn0100]: N. Chomsky and E.S. Herman, "Distortions at Fourth Hand," Nation, 25 June 1977.


