## Chapter 6.2 {.unnumbered}

TIME printed that photograph of a Khmer Rouge execution (if indeed that is what it is) in good faith. We were assured of its authenticity by the Sygma agency who provided us with it: they say they obtained it from a Cambodian refugee now living in Paris, whose name did not appear in the credit for fear of endangering his family in Cambodia. We note that the authenticity of the photograph has been questioned, but it seems to us that there is no way of proving it one way or the other. However, we do thank you for alerting us to the problem.



Not to be outdone, Newsweek leaped into the fray in its issue of January 23, 1978. The executioner and his victim appear on the cover of the international edition, and two other faked photos appear within, one with the caption "The executioners: For the condemned, a swift, primitive and brutal death," and the other, "Life under the Khmer Rouge: Armed guards supervise forced labor in the fields."






In a February 16, 1978, story filed by the Pacific News Service, Douglas Foster added some further details. He cites a State Department intelligence source who labels the photos a fake and said in an interview that he was "appalled" and "shocked" to see the photographs in the press. Foster also interviewed the director of the Sygma agency which had been distributing these intelligence fabrications to eager customers. She claims to have alerted Time to the possibility that the photos were propaganda plants, but held that the photographs were useful anyway, regardless of their authenticity, on the following grounds: "...As the people at Newsweek told me, if the photograph hasn't been absolutely proved false, (the questions) don't matter. Besides that, the Khmer Rouge do these things, like blowing people's heads off. So the photos are like drawings ..."






Foster notes that the photos have appeared widely in the U.S. and Western Europe (also in Australia), and comments: "No Western publisher who has used the photos has yet alerted readers that the pictures may well be bogus."[^ch06-fn101]






The reaction of the Washington Post, Time, Newsweek, the Sygma agency, and others who have been engaged in this little exercise of atrocity fabrication,[^ch06-fn102] recalls some of George Orwell's remarks on the Stalinist press:






When one considers the elaborate forgeries that have been committed in order to show that Trotsky did not play a valuable part in the Russian civil war, it is difficult to feel that the people responsible are merely lying. More probably, they feel that their own version was what happened in the sight of God, and that one is justified in rearranging the records accordingly.[^ch06-fn103]






Putting aside the manifest dishonesty, suppose that the photographs had been authentic. We might then ask why people should be pulling plows in Cambodia, as one of the faked photographs claims to show. The reason is clear, though unmentioned in this propaganda exercise. The savage U.S. assault on Cambodia did not spare the animal population. The Cambodian government reports that the attack on rural Cambodia led to the destruction of 50-60% of livestock in some areas, 30-40% in others.[^ch06-fn104] One can learn from the reports of refugees that "they had to pull the plows themselves because there were no oxen."[^ch06-fn105] Some died from the exhausting work of pulling plows. Who is responsible for these deaths? The U.S. press did not have to resort to propaganda plants to depict the facts. A hundred-word item buried in the New York Times cites an official U.N. report that teams of "human buffaloes" pull plows in Laos in areas where the buffalo herds, along with everything else, were decimated (by the U.S. bombing, although this goes unmentioned in the Times in accordance with postwar taboo).[^ch06-fn106] Much the same is true in Vietnam, as already noted. Quite possibly the U.N. or the Laotian Government could supply photographic evidence, but this would not satisfy the needs of current propaganda.






Let us now turn to the second example that Simons cites, namely, the interview in which Cambodian premier Khieu Samphan is alleged to have conceded a million deaths at the hands of the Khmer Rouge. This is the most widely-circulated "crucial evidence" offered of the barbarity of the regime—we have already given several examples—and is regularly cited by academic specialists, intelligence analysts, and Cambodia watchers. Frank Snepp, one of the top CIA analysts for Indochina, writes the following, with regard to the atrocities of the Khmer Rouge—which typically, he claims have been ignored in the West:






Khieu Samphan himself has provided perhaps the most reliable estimate of the casualties. During a conference of nonaligned countries in Colombo in August 1976 he admitted to an Italian journalist that the population of Cambodia had dropped by a million since the end of the war. When asked what had happened to all these people, he replied, "It's incredible how concerned you westerners are about war criminals."[^ch06-fn107]






Similarly, Timothy Carney, a State Department specialist on Cambodia,[^ch06-fn108] testified before Congress, without qualifications, that "in a 1976 interview with an Italian magazine, Khieu Samphan said that there were 5 million people in Cambodia."[^ch06-fn109] Given roughly 1 million killed or wounded during the war (a "close" estimate, according to Carney), and a prewar population on the order of 7-8 million, we have over a million postwar deaths (i.e., victims of the Khmer Rouge, with a little further sleight-of-hand). As Carney notes, the alleged estimate of 5 million by Khieu Samphan contradicts the estimate by the Cambodian government that the population is 7.7 million, but he offers no explanation for the discrepancy.






Simons reports that the alleged interview was "supposedly given by head of state Khieu Samphan to an obscure Italian Catholic journal, Famiglia Cristiana, in September, 1976, and subsequently referred to in the New York Times Magazine," though its authenticity is denied by Ponchaud, "a French Catholic priest who is a bitter opponent of the Cambodian Communists," who wrote in August, 1977 that he knows "for certain" that the interview never took place. These statements are correct, but are only part of the story. To add some further detail, in the New York Times Magazine,[^ch06-fn110] Robert Moss (extreme right-wing editor of a dubious offshoot of Britain's Economist called "Foreign Report," which specializes in sensational rumors from the world's intelligence agencies) asserts that "Cambodia's pursuit of total revolution has resulted, by the official admission of its Head of State, Khieu Samphan, in the slaughter of a million people." Moss offered no source for this "official admission." We speculated that his source was probably the Reader's Digest, that noteworthy journal of cool and dispassionate political analysis, and Moss informed us in a personal letter that that suspicion was correct. Turning back to Moss's source, we read in the Barron-Paul book, expanding their Reader's Digest article:






Khieu Samphan, as Cambodian chief of state, attended the Colombo Conference of nonaligned nations in August 1976 and while there was interviewed by the Italian weekly magazine Famiglia Cristiana. "Those traitors that remained have been executed," the magazine quoted him as saying. It further quoted him: "In five years of warfare, more than one million Cambodians died. The current population of Cambodia is five million. Before the war, the population numbered seven million."[^ch06-fn111]






Barron and Paul then write that in response to a query as to the fate of the missing one million people, Khieu Samphan replied: "It is incredible how concerned you Westerners are about war criminals." They conclude that "if quoted accurately, Khieu Samphan indicated that between April 17, 1975, and the time of the interview in August 1976 roughly a million Cambodians died."






Note that even if Khieu Samphan had "indicated" that a million Cambodians had died, that is not quite the same as an "official admission...[of]...the slaughter of a million people" as a "result" of Khmer Rouge policy, as in Moss's rendition, which he saw no need to correct when the discrepancy was pointed out to him.






Ponchaud's denial of the authenticity of the interview was in a letter of August, 1977.[^ch06-fn112] The denial is particularly pertinent because Ponchaud is cited as the sole independent (nongovernmental) expert source in Barron and Paul's book. Furthermore, both Barron and Paul refer to their close association with Ponchaud.[^ch06-fn113]






In the light of these facts, we have repeatedly asked Ponchaud in personal letters to present publicly the details of this matter, in view of his expressed devotion to the "search for truth about the events in Cambodia"[^ch06-fn114] and the fact that the alleged interview is not only widely circulated and used as a basis for conclusions about Cambodian atrocities, but had even been offered as grounds for military intervention.[^ch06-fn115] In response to these requests, Ponchaud sent a letter to John Barron stating what he knew of the facts. Unfortunately, he has refused permission to quote from this five-page French letter unless it is quoted in its entirety, a requirement that in effect keeps it from the public domain. We are therefore unable to offer his information about the alleged "interview" or other relevant matters.






The matter is taken up by William Shawcross in a review of Barron-Paul.[^ch06-fn116] He points out that journalists who were present at Colombo, the site of the alleged interview with Paola Brianti, "say that none of them was ever able to get anywhere near Khieu Samphan...Two reporters have asserted flatly that she could not have gotten the interview and that it is a fake," though "she sticks by her story."






Note that in their book Barron and Paul qualify their comment by saying "if quoted correctly ..." The qualification is certainly in order, if only because they misquote the Famiglia Cristiana interview (it was the interviewer, not Khieu Samphan, who is alleged to have offered the 7 million figure). Furthermore, as they and others fail to note, Khieu Samphan explicitly denied the massacre reports in the "interview." There is every reason to be skeptical as to whether there was such an interview, or if there was, whether the "quotes" are anywhere near accurate.






It is doubtful that the journalists and others who have referred to Khieu Samphan's "admission" of a million deaths (or a million "slaughtered") have ever seen the original article in Famiglia Cristiana, which is hardly a well-known source on international affairs. In fact, not a single copy of this journal is to be found in a library in the United States. The journal is a weekly published by the Pauline sisters and is primarily found in churches. It has apparently not occurred to the journalists, scholars, Cambodia specialists, intelligence analysts and congressmen who have quoted or misquoted this "interview" to wonder why Khieu Samphan, at a time when the Cambodian government was not making extraordinary efforts to reach out to the Western World, should have chosen Paola Brianti and Famiglia Cristiana as the medium for approaching Western public opinion. Nor has it occurred to them to be skeptical about a chain of transmission that proceeds from Famiglia Cristiana to the Reader's Digest and then to the international community, or to wonder why Khieu Samphan should have offered a figure of 5 million Cambodians when his government was estimating the population at about 7.7 million.[^ch06-fn117]






The Famiglia Cristiana "interview" has not only been picked up by the U.S. press, congressmen, and intelligence analysts, but also by the foreign press and the scholarly literature.[^ch06-fn118] For example, the Economist gives the following version:






When the Khmer Rouge leader, Khieu Samphan, was confronted by these stark statistics last summer—a 7m population in 1970, an estimated 1m killed during the war, a presumed 5m people left in 1976—he replied blandly, "It's incredible how concerned you westerners are about war criminals." What is incredible is how little foreign outrage these figures provoke.[^ch06-fn119]






What is perhaps incredible is that the Economist should place such reliance on this "interview."






No less incredible is the review of the Barron-Paul book in the Far Eastern Economic Review by Donald Wise,[^ch06-fn120] which begins as follows:






Scene: The Non-Aligned Nations Conference, Colombo, August 1976.






Then comes the Barron-Paul mistranslation of the probably fabricated Famiglia Cristiana interview, plus the inevitable comment that the world "is not concerned about the genocide in Cambodia" (his emphasis).






Turning to the scholarly literature, Kenneth M. Quinn writes that the figure of 7.7 million offered by the Cambodian government "was revised downward to five million by Khieu Samphan in an interview he gave to the Italian magazine Famiglia Christiana [sic]."[^ch06-fn121] Again, no qualifications and no question about the source. The Quinn account is perhaps independent of Barron-Paul, given the dates and the fact that it does not offer the standard mistranslation by Barron-Paul, contenting itself with misspelling and misrepresentation of the contents. Quinn, who is described in Asian Survey as a State Department representative on the National Security Council Staff, is one of the experts who Barron and Paul cite as having made data available to them and having "guided us to other sources,"[^ch06-fn122] including, perhaps, this one.






A year later, Professor Karl D. Jackson surveyed the situation in Cambodia once again for Asian Survey.[^ch06-fn123] Attempting to reconcile apparently conflicting claims about the grain problem, he suggests as one possibility that although food production has still not reached prewar levels, it may suffice "to feed a substantially reduced population, i.e., the five million people cited by Khieu Samphan in 1976, rather than the eight million cited by various officials including Pol Pot." His reference for Khieu Samphan's "estimate" is Donald Wise's review in the Far Eastern Economic Review which begins by citing the Barron-Paul mistranslation of the alleged Famiglia Cristiana interview, which, to compound the absurdity, had already been cited in Asian Survey a year earlier by a State Department analyst who may well have been the source for Barron-Paul. No doubt the next reference to Khieu Samphan's "admission" will appear in an article by Quinn citing Jackson.






A few months after Khieu Samphan's now famous "admission" that his regime was responsible for the deaths of about one-sixth of the population of Cambodia, Indonesian Prime Minister Adam Malik admitted that 50-80,000 people, close to the same percentage of the population, had been killed in East Timor in the course of what the Indonesian propaganda ministry and the New York Times call the "civil war"—that is, the U.S.-backed Indonesian invasion and massacre—though one could not have discovered this fact from the U.S. media.[^ch06-fn124] While Khieu Samphan's "admission" was concocted by the media and scholarship on the basis of a fanciful interpretation of remarks that quite possibly were never made, Malik's admission, by contrast, was clear and explicit. A comparison of media reaction to the actual admission by Malik and the concocted "admission" by Khieu Samphan gives some insight into what lies behind the machinations of the Free Press.






These examples, far from exhaustive, reveal how desperate Western commentators have been to find "evidence" that could be used in the international propaganda campaign concerning Cambodia. The credible reports of atrocities—and there were many—did not suffice for these purposes, and it was necessary to seek out the most dubious evidence. It hardly needs emphasis that journals of the quality and renown of Famiglia Cristiana (or, for that matter, the Reader's Digest) in the enemy camp would be regarded with the utmost skepticism, if not dismissed outright, were they to offer comparable "evidence" about Western atrocities.[^ch06-fn125]






In this case, the Famiglia Cristiana "interview" bears all the earmarks of an intelligence fabrication of the type that the CIA is known to have indulged in repeatedly.[^ch06-fn126]






Before turning to the next example cited by Simons, let us consider further the Wise review of Barron-Paul in the Far Eastern Economic Review, cited above. To conclude the review which began with the Barron-Paul mistranslation of the probably fabricated interview, Wise offers the following quote from a Cambodian official transmitted by Barron and Paul:






...to rebuild a new Cambodia, 1 million men is enough. Prisoners of war (people expelled from the cities and villages controlled by the Government on April 17) are no longer needed, and local chiefs are free to dispose of them as they please.






Surely this is a damning indictment of the Khmer Rouge, on a par with Khieu Samphan's "admission." So let us therefore examine it, to determine whether it has any more credibility than the "interview" that has been so widely exploited to prove Communist iniquity, by Wise among others. As we pursue the trail, we enter into a curious comedy of errors.






Wise's quote is from Barron-Paul:






Francois Ponchaud, the noted French authority on Cambodia, reports that on January 26 an Angka official in the Mongkol Borei district declared: "To build a democratic Cambodia by renewing everything on a new basis; to do away with every reminder of colonial and imperialist culture, whether visible or tangible or in a person's mind; to rebuild our new Cambodia, one million men is enough. Prisoners of war [people expelled from the cities and villages controlled by the government on April 17] are no longer needed, and local chiefs are free to dispose of them as they please."[^ch06-fn127]






Apart from an insignificant error, Wise reproduces Barron-Paul correctly. Barron-Paul give no source, but the source must be an article by Ponchaud in Le Monde[^ch06-fn128] where he asserts that a Khmer Rouge military chief made this statement in a directive to local authorities of the district on January 26, 1976. The accuracy of the translation has been challenged, but we will ignore this matter, since far more serious doubts arise.[^ch06-fn129]






Before turning to these, let us look into the identification of "prisoners of war." Barron-Paul quote the interpolated remark accurately from Ponchaud. In an article in Le Monde on the preceding day Ponchaud makes the same point. He says that refugees distinguish two categories of people: "the 'old people' from the regions liberated before 1975, and the 'new people' liberated on April 17, 1975. These 'new people' are always considered as 'prisoners of war' and have no rights." The allegation appears in a somewhat different form in Ponchaud's subsequent book. Here he writes that Khmer Rouge soldiers had "more than enough to eat and refused themselves nothing; they had rice, meat, and fish in plenty," but they were withholding food from workers who "were literally dying of hunger"[^ch06-fn130]: "Their reasoning was simple enough: 'You are prisoners of war. We went hungry for five years. Now it's your turn!'"[^ch06-fn131] No source is given for the latter quote, and no evidence is cited suggesting its general applicability. As we shall see, Ponchaud uses the device of quotation with considerable abandon, so that skepticism is in order about this particular case.






Turning now to the quote given by Wise from Barron-Paul, who cite Ponchaud, note that they say Ponchaud attributes it to "an Angka official" on January 26, 1976. In fact, he attributes it to a Khmer Rouge military chief who issued a directive to local authorities on January 26. In his subsequent book, which one would expect to be more careful and considered than a newspaper article, Ponchaud does not give the quote at all. The sentiment surfaces only in the following quote: "Il suffit de 1 ou 2 millions de jeunes pour faire le Kampuchéa nouveau,"[^ch06-fn132]—literally: "One or two million young people are enough to build the new Cambodia." Not only have the numbers changed—from one million men to 1-2 million young people—but so has the source. The quote is now attributed not to a Khmer Rouge military commander on January 26, 1976, but is rather given (still in quotes) as "the formidable boast" of the Khmer Rouge. The full context is this: "The Khmers Rouges are coldly realizing their formidable boast: '...'" ("Les Khmers Rouges réalisent froidement leur redoutable boutade: '...'"). This statement closes the chapter entitled "The Calvary of a People."






Ponchaud's statement in the book plainly implies that the Khmer Rouge are in the process of eliminating all but one or two million young people—that is, a total of some 5-7 million people, including all who are not young, out of a population that he estimates at 8 million in 1970. A few lines earlier Ponchaud gives estimates of war deaths (600-800,000) and "peace deaths" (note: not killings but deaths) ranging from 800,000 to 1,400,000, the higher estimates allegedly from U.S. sources. The difference between approximately a million deaths and the elimination in process of some 5-7 million people a few lines later would seem significant. It is typical of the way that Ponchaud and others use numbers and their care with the distinction between killing and dying (e.g., from disease and malnutrition caused by the war); recall the prediction from U.S. government sources that the numbers who would die from such causes would be on the order of one million.[^ch06-fn133]






Elsewhere, Ponchaud gives the alleged quote as follows. After stating that the number of postwar dead "certainly exceeds a million," he writes: "In the view of the revolutionaries, such a slaughter is no catastrophe: 'one or two million resolute young people are enough to reconstruct Cambodia,' is a boast [boutade] frequently used by cadres during meetings."[^ch06-fn134] Here again the implication is that the revolutionaries would not be overly concerned with the massacre of many millions of people, the overwhelming mass of the population. In another publication from the same period, Ponchaud gives still another version of what appears to be the same "quote." He writes: "A Khmer Rouge stated: 'If there should remain in Cambodia only 20,000 young people, we will build the new Cambodia with these 20,000."[^ch06-fn135] The numbers have changed once again, this time substantially, and there is no specific source. In this case, Ponchaud does not imply that the revolutionaries are in the process of eliminating all but 20,000 young people.






We now have a number of versions of the alleged quote, which Ponchaud evidently regarded as of some significance, given its prominence in his writings in 1976-1977, and the conclusions he drew from it. In only one of these sources (Le Monde) is the quote specifically attributed: to a Khmer Rouge military commander issuing a specific directive on a specific date, who says that "one million" are enough—the rest can be "disposed of" (the Barron-Paul translation, which Paul claims was approved by Ponchaud). Ponchaud gives the entire "quote" from this commander in italics in a separate paragraph in this Le Monde article, emphasizing its significance. The context, as well as the Barron-Paul rendition, suggest that he must have had some text or other document. In other articles written at the same time and in Ponchaud's subsequent book, the context and the quote disappear. There is no reference to the alleged directive. Rather, a "formidable boast" of the Khmer Rouge is given without attribution but in quotes: "one or two million young people" will be enough to build the new society. Nothing is said about disposing of the remainder, but it is implied that the Khmer Rouge are eliminating them.






In his review of the book, Lacouture gives still a different version: "When men who talk of Marxism are able to say, as one quoted by Ponchaud does, that only 1.5 or 2 million young Cambodians, out of 6 million, will be enough to rebuild a pure society, one can no longer speak of barbarism" but only "madness."[^ch06-fn136]






We mentioned the discrepancy between the Le Monde account and the book in the review-article cited in note 100, adding that "this is one of the rare examples of a quote that can be checked. The results are not impressive."






In his letter commenting on this article,[^ch06-fn137] Ponchaud explained that the original Le Monde reference was based not on any text but rather on a report by a refugee who said that he had heard this remark from the chief of the Northwest region of Cambodia at a meeting; in our view, it would have been a good idea to state the source accurately in the original article. Ponchaud writes that he subsequently heard similar reports from refugees with numbers ranging from 100,000 to 2 million, and "in a spirit of truth," gave a more qualified account in his book, without a specific source. Ponchaud interprets the alleged statements:






not as a firm wish to reduce...Cambodia to 1 million people, but as expressing a resolution to purify Cambodia without taking into account people's lives. It is therefore more a "redoutable boutade" [a formidable boast] than an explicit affirmation of intention.






We wonder whether under this interpretation, it is still proper to imply, as Ponchaud clearly did in his book, that the Khmer Rouge are in the process of eliminating 5-7 million people in accordance with this "formidable boast." We continue to be unimpressed. This seems to us a curious way to use the device of quotation. Recall that this is one of the very few cases where an alleged quote can be checked, because in this instance it was reported in at least two separate sources (we will see that other quotes that are subject to verification fare no better, on inquiry). To our minds, it raises serious questions about the authenticity of the quotations that are offered in what is, we again emphasize, the most serious of the critical work on postwar Cambodia. The reader will observe how this rather vague report of what someone is alleged to have said, subject to a qualified interpretation, has been transmuted into a firm declaration of genocidal policy in its long voyage from refugees, to Ponchaud, to Barron-Paul, Lacouture and Wise.






Apparently Ponchaud has since had still further thoughts about the reference. It is deleted entirely from the American edition of his book, the one from which we have been quoting.[^ch06-fn138] But the long and dubious chain of transmission has left it as part of "history."






We mention specifically here the "American translation" because, curiously, the quote remains intact in the simultaneous British translation, where the last paragraph of chapter 4, "The Calvary of a People," reads as follows:






A large part of the deported population appears to have been sacrificed. Its role in the history of Democratic Kampuchea will thus have been to build up the country's economic infrastructure with its own flesh and blood.[^ch06-fn139]Now a country of the pure should arise. 'One or two million young people are enough to make the new Kampuchea!' was the blood-chilling boast of the Khmers Rouges, which they are now grimly turning into a reality.[^ch06-fn140]






The two sentences that we have italicized are omitted in the American edition. The British translation is, perhaps, a bit free, but both the French original and the British translation do clearly imply that the Khmer Rouge are in the process of cold-bloodedly eliminating something on the order of 5-7 million people.






In the British Penguin edition, a slightly different version of Lacouture's misstatement of this "quote," or "boast," or whatever it may be, attributing it to "men who talk of Marxism" and concluding that it goes beyond barbarism, appears on the book's cover. In the American translation, it is entirely deleted from the book, along with the claim that some 5-7 million people (including all but the young) are being eliminated to build "a country of the pure." We leave it to the reader to decide what to make of all of this.[^ch06-fn141]






Some further skepticism about this "quote" or "boast" is aroused by the Congressional testimony of State Department expert Charles Twining:






The Khmer Rouge sometimes on a local level will tell villagers that, "we can afford to lose 1 million or even 2 million people." You hear this story often enough from enough places to make you think it has been handed down from on high.






We can lose 1 million or 2 million if we must to create the new Cambodia...[^ch06-fn142]






The reference is suspiciously familiar. In this case, the 1-2 million are not those who will be left (the others cold-bloodedly eliminated by the Khmer Rouge, according to Ponchaud's rather fanciful construction which he has withdrawn), but rather those who may be "lost." And the quote is not attributed; rather Twining surmises that it has been "handed down from on high." It is a reasonable suspicion that this is a residue of the same alleged "boast." At this point, one must really belong to the faithful to believe that there is anything at all to the whole story. And our trust in those who transmit it without qualification in various forms correspondingly diminishes.






Yet another source for this garbled report is suggested by a Phnom Penh radio broadcast on military problems in which it is explained how Cambodia can defeat the Vietnamese even though much outnumbered:






Using these figures, 1 Kampuchean soldier is equal to 30 Vietnamese soldiers...If we have 2 million troops, there should be 60 million Vietnamese. For this reason, 2 million troops should be more than enough to fight the Vietnamese, because Vietnam only has 50 million inhabitants. We do not need 8 million people. We need only 2 million troops to crush the 50 million Vietnamese; and we still would have 6 million people left.[^ch06-fn143]






Again the statement is suspiciously familiar. It may well be that if there is any source at all for these various accounts, it is some sort of patriotic slogan, formulated with various rhetorical flourishes.






Wise is clearly much enamoured of this "quote." In the same issue of the Far Eastern Economic Review in which he reviewed Barron-Paul,[^ch06-fn144] Wise has an article on Cambodia in which he explains that "the new regime is too harsh for the formerly fun-loving, easy-going Cambodians."[^ch06-fn145] As evidence for the harshness, he writes that "a senior Khmer Rouge official was quoted as saying that Cambodia needs no more than 1 million people to get started on its new course and all prisoners—that is, people from zones unoccupied by the Khmer Rouge at the April 1975 ceasefire—are no longer required and may be disposed of as local commanders think fit." In a review of the English (British) translation of Ponchaud's book, he cites it once again, in the following context:






Nobody can suggest a reliable figure for the "peace-dead," says Ponchaud, "but it certainly exceeds a million." Yet the Khmers Rouges boasted: "One or two million young people are enough to make the new Kampuchea."[^ch06-fn146]






The implication is that the "peace-dead" are victims of the Khmer Rouge who "boast" of this massacre because one or two million people are all that are needed. Notice again how the facts, if any, have been skillfully transmuted in their passage through the Western propaganda system. In the first place, there is a serious question as to how many of the "peace-dead" fall to the Western account, rather than that of the Khmer Rouge. There is the further question whether the victims for whom the West does not bear direct responsibility are the victims of peasant revenge or a coordinated policy of massacre. Finally what of the "boast" of the Khmer Rouge—which stands in dramatic contrast to their persistent denial of massacres and expressed commitment to building up the population to 15-20 million? This "boast" is Wise's version of Ponchaud's version of a variously-attributed remark that has dissolved upon inquiry. Note again that it is a central element of his review of both Barron-Paul and Ponchaud, and that he also cited it in a separate article. It apparently never occurred to him to wonder why the "quote" he repeats is given and attributed differently in these two sources, or to inquire further into its authenticity on these grounds. In such ways as these the Western system of indoctrination spins its web of deceit.[^ch06-fn147]






Recall Lacouture's question whether it is important to decide "exactly which person uttered an inhuman phrase." The example just mentioned was one of the cases under consideration—in other cases to which we return the distortion was still more flagrant. It is also one of the examples that Lacouture did not rectify in his "Corrections," and that he continues to use long after Ponchaud had recognized that it had no basis.[^ch06-fn148] Lacouture used the "quote" to show that men who talk of Marxism are going "beyond barbarism." In fact, it turns out that there was no quote but only a remembered "boast" of dubious import, variously presented by Ponchaud and sufficiently questionable to have been eliminated from the American (though not British) edition of his book after inquiry, and suspiciously similar to a remembered slogan of quite different import attributed to many refugees by the State Department's leading expert. The example is perhaps not particularly important in itself, but gains significance in the light of the publicity accorded it and the fact that it is one of the rare cases of a "quote" for which independent verification is even possible.






It is also worth mentioning that these "quotes," which have a curious habit of disappearing on analysis, form the most substantial part of the evidence behind one crucial element in the thesis to which the propaganda machine is committed: that the Khmer Rouge leadership was committed to systematic massacre and starvation of the population it held in its grip, that is, to "autogenocide." It would be of little use to contemporary Western ideology it if were to be shown that peasant revenge, undisciplined troops and similar factors (still worse, the legacy of the U.S. attack) were responsible for deaths and killings in Cambodia. It is crucial to establish in the public consciousness, whatever the facts may be, that a centralized and carefully-planned program lay behind the atrocities. As we have seen, one cannot appeal to the refugee reports for this purpose. Therefore "quotes," "boasts," "slogans," "interviews," and similar documentation are of vital significance, as demonstrations of intent and recognition. It is therefore interesting to see how flimsy is the basis on which such elaborate constructions are founded, again, a useful insight into the mechanism and goals of current Western propaganda.






The examples just discussed, which are among the most widely diffused in the Western media and the springboard for many impassioned accusations, are by no means atypical. Let us turn now to the next observation by Simons, namely, that Western governments that have maintained direct contacts with Cambodia and have sent visiting delegations "generally refuse to accept the genocide allegation." One would think that with the intense concern over the internal affairs of Cambodia, evident from the extensive press coverage and denunciations despite repeated laments to the contrary, and the difficulty of obtaining information from a country virtually closed to the outside world, the reports of Western visitors would have received considerable notice. Such visitors would have been interviewed in depth, one might suppose, and their writings eagerly perused and circulated. That has not quite been the case, however. Their trips were sometimes reported, though just barely, and there was little effort to follow up beyond the first news conference. And Simons's interesting observation, which should have immediately sparked some doubts among journalists with a modicum of skepticism, occasioned no further inquiry.






By late 1978, the regime was beginning to open its doors more widely to foreign visitors. UN Secretary-General Kurt Waldheim was invited in October,[^ch06-fn149] and two U.S. reporters—Richard Dudman and Elizabeth Becker—visited in December, along with the British specialist on Southeast Asia Malcolm Caldwell, who was assassinated on the final day of their visit. Another group of visitors from the United States (including one member, Stephen Heder, a specialist on Cambodia, who had lived in Phnom Penh and is fluent in Khmer) had reached Peking when the Vietnamese invasion closed off access to the country in January 1979, and other invitations had been issued. As we noted in the preface to this volume, some observers regard the improvement in the international image of the regime as perhaps the major factor in the timing of the Vietnamese invasion. With large parts of the country under military occupation, there will be no further opportunity to observe at first-hand the social order that had been constructed or to evaluate the picture presented in the West on the basis of refugee reports, selected and transmitted in the manner we have been discussing. Therefore, it is a matter of some interest to review the material that could have been exploited, the leads that could have been followed up by journalists and others concerned to establish the truth about postwar Cambodia. It is obvious that visitors on guided tours, like refugees selected on guided tours to refugee camps, can only present a partial and perhaps misleading picture, but their reports certainly offer a view of the social reality that would have been carefully investigated by anyone seriously concerned with the truth. We will divide this review into two sections, considering first the visitors who preceded the two U.S. reporters, then turning to their reports.






The Swedish Ambassador to Peking, Kaj Bjork, led a delegation on a two-week visit to Cambodia in February-March, 1976. The visit was quite newsworthy, for one reason, because it coincided with an apparent bombing in Cambodia of disputed origin. (Cambodia claimed that the United States was responsible, a charge dismissed in the West but apparently not in the Third World).[^ch06-fn150] Ambassador Bjork was taken to the site of the bombing. His account of his trip received some notice, including a front-page story in the New York Times.[^ch06-fn151] Ambassador Bjork, the Times reported, "described Cambodia as a nation under tight military control and led by nationalistic Marxist intellectuals whose goals are more revolutionary than those of the leaders of China." He found no private ownership, no money or wages, no private shops. "Mr. Bjork said that he saw no signs of starvation[^ch06-fn152] and attributed this to the controversial decision of Cambodia's leaders to force people out of the cities to work in the rice fields"—a conclusion that is, as we have seen, apparently consistent with the judgment of State Department experts and others. He was struck by the emptiness of Phnom Penh, where he was not permitted to walk freely, though he noticed more activity in the outskirts. In the countryside he saw "total mobilization" to construct water control and irrigation systems and develop agriculture, the basis for all other progress.






As for popular attitudes, Ambassador Bjork said that "around Phnom Penh you could see youngsters marching, all of them with a hoe and a spade, some of them also carrying a gun. I got the very strong impression that the regime has active support from this kind of young person." The leadership are men who returned from study in Europe with "a great deal of knowledge, a good deal of Marxist theory, and came back to Cambodia and reacted very strongly to existing social conditions. They have very strong collectivist and egalitarian ideas with a very strong overtone of nationalism." Khieu Samphan, in particular, "gives the impression of being an intellectual of quality"—compare the contemptuous and disparaging account in the best-seller on Cambodia by Barron and Paul of the Reader's Digest.






It might have been interesting to hear more about the impressions of this Swedish delegation, but the press was not interested. Scholars and reporters so assiduous as to discover Famiglia Cristiana might have learned something more, with a little enterprise. The Swedish journal Vietnam Bulletinen carried an interview with Jan Lundvik, who accompanied the Swedish Ambassador.[^ch06-fn153] His eyewitness report is quite different in character from the picture that dominates the media. Lundvik described the massive efforts to reconstruct the agricultural and irrigation systems, all by hand because there is no equipment. He reports two "lasting impressions" from his visit. The first is "the very strong patriotism" in a population that had been colonized and had not enjoyed complete independence for centuries, patriotism that "expresses itself in a very strong drive for independence—in all domains." The second lasting impression is the incredible destruction: "One can barely imagine how destroyed are the agricultural areas. Phnom Penh is like an island in a land destroyed by bombing." Virtually everything seen on a trip from Phnom Penh to Kompong Tham was destroyed.[^ch06-fn154] In Phnom Penh there were 100-200,000 people, he reports.[^ch06-fn155] The evacuation of the cities in April 1975, he believes, was not "as noteworthy for the Kampuchean people as had been represented in the West," because Cambodia is an agricultural country; he also cites historical precedents. The revolution represents "the victory of the countryside over the city," in a country that is overwhelmingly agrarian—or was, prior to the forced urbanization caused by the U.S. bombing.






Lundvik reports schooling until age 12—at which time children join in production—and severe shortages of medical supplies. He speaks of a great effort to increase the population from the present 8 million to 15 million. He then adds the following comment:






In this connection I want to point out that the articles that are being written about a "bloodbath" in Kampuchea rely on assumptions that have been misunderstood or falsely interpreted. When the Kampucheans say that they can make do with 1 million inhabitants, they mean that they can achieve every task no matter how few they are, not that one is about to liquidate the remainder. The lack of labor power is a problem, and on this account they are trying to achieve a high birthrate.






Quite possibly, Lundvik has in mind here the Ponchaud "quote" in Le Monde which we have just discussed. Lundvik's comment supports Ponchaud's more qualified observations in personal correspondence, cited above, though not the various and mutually inconsistent published accounts. It is evident not only from these comments but from his observations on what he saw that Lundvik gives little credence to the stories, then already circulating widely, on genocide.[^ch06-fn156]






In general, Lundvik's description of popular commitment and patriotism in a land ravaged by war and passionately committed to independence and development is positive and strikingly different in tone from the reports that were designed for a mass audience in the West. It is relevant to the "difficult question" that troubled Twining and others. It is noteworthy that a Swedish visitor does not feel compelled to evade what seems to be a plausible answer to this question: that the regime had support among the peasants.






The Swedish ambassador to Thailand, Jean-Christopher Oberg, visited Cambodia in December, 1977. He said "that he saw no sign of oppression or cruelty...[and]...discounted refugee reports that about one million people had died or been killed since the takeover." He also "said he saw very few armed Cambodians"—in fact, he saw four, "including one girl"—and "saw nothing to corroborate reports that the Cambodians were working under armed threats."[^ch06-fn157]






Ambassadors from Sweden, Finland, and Denmark visited Cambodia again in January, 1978. A Reuters report from Peking on their trip appeared in the Washington Post and in an abbreviated version in the New York Times,[^ch06-fn158] with a second-hand account of what they are said to have told "Nordic correspondents" on their return to Peking. There seems to have been no effort to pursue the matter further. This single second-hand report is uninformative. The Danish Ambassador is quoted as saying that Phnom Penh resembled a "ghost town" (a comment since widely circulated) and the Swedish Ambassador as having said that more land was under cultivation than in 1976 and that "traces of the 1970-1975 war were still considerable" though they have decreased. "There were no signs of starvation." Little else was reported.






Inquiries to the Swedish Embassy in Washington in an effort to obtain further information about the latest trip have been rebuffed on grounds that the ambassador's report is not available to the public. What the explanation for this curious response may be, we do not know, and apparently no journalist has been sufficiently intrigued to pursue the matter further.






The Foreign Minister of Thailand spent four days in Phnom Penh in early 1978. The fifth paragraph of Henry Kamm's story in the New York Times, which we quote in its entirety, gives this account of what he saw:






Reporters at the airport were struck by Mr. Uppadit's effort to say nothing unkind about Cambodia. He volunteered a comment that reports about conditions in Cambodia since the Communist victory might have been exaggerated. Asked about his impressions of life in Phnom Penh, Mr. Uppadit said it had seemed like a normal city. Scandinavian ambassadors who visited the Cambodian capital last month described it as a "ghost city."[^ch06-fn159]






The Thai government, of course, is extremely right-wing and passionately anti-Communist, but Uppadit's comments might be treated with skepticism on grounds that he had returned from an attempt to improve relations with Cambodia.






In April 1976, a Japanese newsman, Naoki Mabuchi, who had remained in Phnom Penh until May 1975, reentered the country and was held in detention in the border town of Poipet for a week. "While in detention, he said, he was free to watch activities in Poipet from the balcony of his room and even to wander outside the building, although he did not stray far." He "says he speaks the Khmer language well enough to carry on casual conversation." Mabuchi said that "the people he saw all appeared to be well-fed and in good health. He said his observations convinced him that reports in the Western press 'placed too much stress on the dark side' of life in Cambodia under Khmer Rouge rule." The Bangkok press reported that as he crossed into Cambodia he was beaten, later tortured, by Khmer Rouge soldiers. On his return to Thailand, he denied these reports: "I was not beaten or tortured. I was treated by the Cambodian officials very nicely. They gave me the same food they had, and I think I gained some weight."[^ch06-fn160]






Michael Vickery adds an interesting personal observation based on the story of the Japanese newsman, which has some relevance to the kind of reporting offered concerning Cambodia. He visited the border in Aranyaprathet shortly after the Japanese reporter had crossed into Cambodia. During the next two days that he spent in that town, he heard repeated "eye-witness" reports that the newsman had been "beaten with rifle butts," "probably killed," and then "definitely killed," the last being the accepted account when he left the town. A few months later, Vickery discussed the incident with a member of the U.S. Embassy in Bangkok, with a special interest in Cambodia, who claimed that the Japanese newsman had obviously lied and had indeed been badly beaten. Why did he lie? To protect future Khmer-Japanese relations or in hopes that he would be invited back, Vickery was informed. The evidence that he had lied was "eyewitness reports." But what of the eyewitness reports of his death? "Shrug of shoulders." The U.S. official further admitted that he had not tried to meet the reporter or to judge the credibility of his report. Vickery comments:






No, his possibly true story was of no interest, although, obviously, the rumours of his mistreatment or death were highly interesting. I think this is characteristic of an irresponsible attitude among those who are directly concerned with the manufacture of many of the stories about Cambodia which have been circulated.[^ch06-fn161]






Vickery emphasizes correctly that whatever the facts might have been about the experience of the Japanese newsman, they would tell us little about contemporary Cambodia. It is, nonetheless, interesting to trace the fate of the story.






Four Yugoslav journalists visited Cambodia in March 1978, and reported on their visit in the Belgrade press. U.S. readers could find a translation of excerpts in the radical-pacifist journal Seven Days.[^ch06-fn162] They estimated the population of Phnom Penh at no more than 20,000, contrary to official estimates of 200,000. Money had been eliminated and the basis of social life was a system of cooperatives, one of which they visited. There they were told that work-related payment had been abolished and "complete equality prevails." "We didn't get the impression that the Kampuchean countryside is suffering any food shortages." They described newly constructed buildings, workers "bustl[ing] past the wavy palms" in Phnom Penh, some "carelessly" carrying arms (the same was true throughout Cambodia, they report, "probably a carryover from the revolutionary days"; there were some armed supervisors of work groups, "although that was not a striking phenomenon"). They visited schools and "huge" construction projects which they found "impressive," where construction crews work an 8½ hour day with three free days a month devoted to lectures and discussion of work problems. Among the workers, primarily young, were small children, former Buddhist monks and "students from the now-suspended high schools and universities who, carried away by enthusiasm for their work, were forgetting their French but acquiring other skills." They report an interview with Prime Minister Pol Pot,[^ch06-fn163] who expressed the hope that the population (which they report to be 7-8 million) will quickly grow to 15-20 million. They were struck by the absence of civil government or other organizations ("with the exception of unions on the factory and enterprise level") and "the absence, even in mild form, of political indoctrination." The most striking features of the society were its "egalitarianism," "fundamentalist radicalism in interpreting the concept of relying on one's own resources," and "the very evident sense of national pride" which "is reminiscent of the behavior of a quiet and introverted person whose opinions were hardly ever taken into account earlier, but who now speaks out, unexpectedly, but invariably passionately."






More extensive excerpts appear in the BBC summary of world broadcasts, from a six-part report by Slavko Stanic.[^ch06-fn164] The former residents of the cities, Stanic reports, are now "mainly members of mobile brigades, which go from one building site to another to build new earth dams or construct artificial lakes," or they live in cooperatives. He reports a 9-hour work day and writes that "we had the opportunity to convince ourselves that there is definitely no longer any hunger in Cambodia." He describes a school for skilled electricians in a Phnom Penh suburb where "the lecturers were former workers who had passed through the 'school of the revolution,'" and an agricultural school where the lecturers "were skillfully applying science to the production of seeds for new varieties of rice." "The hospitals seemed to be in the hands of the old renowned Phnom Penh doctors." Stanic reports that there are great differences among the cooperatives. "In the rich Province of Battambang and wherever there were villages before, private plots around the houses are much bigger, the peasants have cows and pigs and other livestock in private ownership," and "there are not many of the pre-fabricated barracks which serve as common canteens in which all members of the co-operatives and their families eat." In the "newly established economic zones where the former inhabitants of the cities live" conditions are harsher, and "thousands of families live in dwellings on stilts or in improvised barracks," while it is planned that by the end of 1979 every family should have a house. "The chief concern of the new authorities in Phnom Penh is the construction and rehabilitation of the villages, an increase in the standard of living of the peasants and the growth of the population." The suburbs of Phnom Penh, he was told, have about 220,000 people. He believes the current "policy of empty towns is a part of the strategy of the country's defence." New economic installations (e.g., a shipyard) are being installed in the vicinity of towns and their workers housed in the towns, which Stanic assumed would be slowly resettled.






Stanic also comments on the attitude of the regime towards Buddhism. He quotes Yun Yat, the Minister of Culture, Information, and Propaganda: "She told us that 'Buddhism is incompatible with the revolution,' because it was an instrument of exploitation...Buddhism was dead, and the ground had been cleared for the laying of the foundations of a new revolutionary culture." Stanic also reports that at Angkor Wat, "some of the members of our escort hurried as a sign of respect to touch images of Buddha carved in stone. Some high ranking Party cadres also greeted us in the Buddhist manner when they met us, and one of the Buddhist priests who has replaced the robe with the revolutionary uniform disagreed with Minister Yun Yat. He told us that Buddhism and communism had the same humane goals, and that there was no great antagonism between them."






Reports of the Yugoslav visit appeared in the U.S. press. Michael Dobbs, in a report from Belgrade,[^ch06-fn165] emphasized the abandonment of Phnom Penh and the "new order...based on the village ..." and on the cooperative and mobile brigade. "The Yugoslavs do not appear to have raised the controversial question of the hundreds of thousands of people believed to have been killed by the Khmer Rouge shortly after their victory," Dobbs writes in a typical reference to what "is believed"; "The only allusion to such massacres was made by the Politika correspondent, Ranchic, who said: 'We were inclined to believe the statement of our guides that the class enemy has been relatively quickly eliminated in Cambodia.'" The more favorable impressions that appear in the actual report are ignored or underplayed.






Citing the Yugoslav visit, AP reported that "Cambodia is training boys and girls as young as 12 to replace the industrial working class that was swept away after the Communist takeover three years ago."[^ch06-fn166] The reference to the "industrial working class that was swept away" by the Communists and is now being "replaced" is an embellishment of the Yugoslav report by AP. In fact, the "industrial working class" was very small and there is no indication in the Yugoslav report that it was "swept away." Refugees from the Battambang area, for example, report that in general workers remained in their jobs in a jute processing plant outside Battambang after the war.[^ch06-fn167] Perhaps AP has confused its dates and the agent of destruction; it is true that some of the few Cambodian industrial installations, and presumably workers and their families as well, were "swept away" by U.S. bombers, without noticeable indignation in the media. Programs of vocational training for 12-year-olds are, furthermore, not generally regarded as an atrocity in a poor peasant society. The anti-Communist Sihanouk regime, for example, took pride in its programs of technical and vocational training in "model primary schools" and featured pictures of young children working with industrial machinery in its information publications, noting that the youth must not "take refuge in administrative careers" but must "have the ideal of productive labor."[^ch06-fn168] We do not recall protests in the West over such savagery.






The AP report also describes work-study programs and a nine-hour work day with evenings "set aside for alternating classes of political indoctrination and technical education." Again, a nine-hour work day hardly seems a major atrocity in a country of the economic status of contemporary Cambodia, and the Yugoslav report actually noted "the absence, even in mild form, of political indoctrination," as we have seen.






The New York Times carried a report of the Yugoslav visit by David A. Andelman from Belgrade.[^ch06-fn169] He repeats Ranchic's comment, cited above, and the report of the abandonment of Phnom Penh (he reports the Yugoslav journalists as writing that the population was about 200,000, "though most seem to live in the surrounding area and only about 10,000 downtown"). He also reports their account of work brigades with the comment that "it was clear that they were impressed labor," without explaining how this was clear. He too downplays or ignores the more favorable impressions conveyed, for the most part. Henry Kamm cited the Yugoslav visit in a column devoted to refugee reports.[^ch06-fn170] He tells us that one of the Yugoslav journalists "reported that they were appalled by much of what they saw, although, restricted by the conventions of Communist fraternalism, they said so only implicitly in their dispatches."[^ch06-fn171] As evidence, he cites their report of "child labor in rigorous agricultural tasks" which the Cambodians urged them to film despite the alleged statement of a Yugoslav TV reporter that this "would make a bad impression on the outside world."[^ch06-fn172] Kamm claims that the Yugoslav reports bear out the refugee accounts of "continuing bloodletting, even among factions of the ruling party, and starvation, nationwide forced labor and regimentation," with a work day beginning at 4 a.m. and lasting often until 10 p.m. How he derived these conclusions from published accounts or the reports concerning them in the U.S. press he does not say.






François Rigaux of the Center for International Law of the Catholic University of Louvain was a member of a delegation of the Association Belgique-Kampuchea who spent two weeks in Cambodia in mid-1978, covering 2,000 km. in several regions of the country and engaging in discussion with representatives of regional and municipal administrations, cooperatives, factories, workers groups, schools, hospitals and government. He has written a very detailed factual and analytic report of his experiences, which presumably would be available to journalists and others interested in his impressions of what he found.[^ch06-fn173]






Initially struck by the apparent emptiness of Phnom Penh, Rigaux discovered after a few days that quite a few sections were settled and that people appeared to be engaged in normal urban existence. The surrounding industrial sections were more densely settled, and again, life seemed quite normal. The most striking feature of the cities was the complete absence of commerce.






In the countryside, people appeared to be well-fed, quick to enter into conversation, jokes and laughter, and in general engaged in normal activities with good-will, as far as he could determine. Rigaux was struck by the extreme decentralization and the progress in agricultural development. Schools combined study with light work (raising animals, cultivating fruits and vegetables, etc.), and the same was true in a secondary school that he visited. In a Phnom Penh factory, too, he found that workers were raising their own pigs, poultry, and vegetables. Cadres and administrative personnel participated in productive labor as well as taking responsibility for cleaning offices and so on.






Like other visitors, Rigaux was taken to the Ang Tassom collective. He reports that the work force was divided into three categories: people under 35 were responsible for heavy work, and those who were unmarried were assigned work in more remote areas; those in the 35-55 age bracket and young mothers carried out lighter work near their homes; and such activities as weaving and basketwork were reserved for people over 55. The cooperative had a medical center and primary school with four hours of instruction a day for children and some adult education. Each family had its own house with an adjoining area for raising tobacco, fruit, etc.






In the area of family life, his own professional specialty, Rigaux reports that he found a picture not unlike that of Western European villages before the industrial revolution, with a strong emphasis on family life. Children over a year of age had collective care during the work day, and he reports efforts to arrange for married couples and families to share related occupations where possible. With the extreme decentralization and local arrangements for personal affairs, bureaucracy appeared to be reduced to a minimum.






Rigaux takes the "political objective" to have been "to place the entire population under the conditions of life and work of the poorest, the peasants." What there was, was shared equally. Children of 15 years of age were expected to devote themselves to productive labor, a situation that should, he writes, be "compared to the fate of a great number of children of third world countries of the same age who are beggars or prostitutes [or, we may add, the 52 million child laborers, including 29 million in South Asia, whose fate evokes no outrage], rather than to the privileged condition of well-educated adolescents of the industrialized societies." Similarly, medical care is not concentrated in the cities and reserved for the elite but is distributed through the most backward regions with an emphasis on preventive medicine and hygiene.






"The best propaganda for the new regime," Rigaux writes, was the attitudes and behavior of the older peasants whom he came upon by chance during his travels. To Rigaux, they appeared to have acquired dignity, serenity, and security after a lifetime of oppression and violence.






Rigaux also reports on the discussion meetings for arranging work schedules and other tasks at various levels and the methods for selecting administrative personnel. He believes that factories, schools, cooperatives, and other organizations permitted a substantial degree of free exchange of opinion and popular decision-making. He notes the absence of the rights taken for granted in Western industrial societies, but points out that not only is the level of economic development incomparable, but also there were, he believes, elements of control over work and supervisors that are foreign to the industrial democracies.






Rigaux remains unconvinced by the explanations offered by the regime with regard to repressive policies after liberation, including severe punishment and execution. He notes, however, that the conditions described with horror by many of the refugees (which he believes have "considerably improved") are "those of the majority of the Khmer peasants, conditions of which [the refugees] were unaware during the period when their privilege permitted them to keep at a distance" from the lives of the poor.






Rigaux believes that "relative to what it was before liberation, or compared to that of the peasants of Bangladesh, India or Iran..., the condition of the Khmer peasant has improved notably." For urban or Western elites, the results are "shocking," in part because of the deliberate insistence on equality, which requires that all share in "the conditions of work to which the immense majority of the world's population have been subjected for millenia." Now everyone faces "the exalting task of cooperating in the progressive improvement of the conditions of life of the entire population." "Conceived in a very poor country ravaged by war, the economic and political system of Cambodia does not pretend to be a model for an advanced industrial society, but it would be foolish to judge it in accordance with the needs and experiences" of such societies.






No doubt Rigaux, like other visitors, was shown what the regime wanted him to see. The picture he presents in his detailed observations should be worth some attention, one might imagine, and in fact might help explain both the apparent commitment of significant parts of the population to the new regime and the horror and indignation of others at its practices. As he notes, he had no opportunity to assess the veracity of the many stories of massacre and cruel oppression, but again, we note that there is no direct inconsistency between these stories and the quite different impression obtained by visitors in a country that is, by all accounts, highly decentralized and perhaps quite varied from place to place.






There were many other visitors to Cambodia from the Scandinavian countries, some from Communist groups, some non-Communists from "friendship associations," some journalists. Their reports appeared in the mainstream press and journals in Sweden and Denmark, but have yet to be mentioned in the United States, though the sources are hardly obscure and some of the visitors (e.g., Jan Myrdal) are quite well-known in the United States. We will not review their reports, which are in general quite favorable though often qualified by the observation that while they personally witnessed scenes throughout the country of people engaged in productive work with apparent contentment and enthusiasm (working a 9-hour day, but according to Gunnar Bergstrom, at a slower pace than is typical in Europe), they do not speak Khmer and cannot comment on what they were not shown. These visitors too report no indications of starvation or malnutrition.






A Japanese delegation from the Peking embassy visiting in the fall of 1978, reported that the regime was stable and "the people did not seem undernourished" ("there were plenty of vegetables and fruit, and the peasants' diet could be supplemented by pork"). An economist who had been in Cambodia during the Lon Nol regime "observed that rice production and irrigation are now better organised." Phnom Penh "is a desolate city by day" but "a delegation member said he saw large numbers of people returning to the city in the evening from small-scale industries located outside."[^ch06-fn174] U.S. readers, deluged with reports about Cambodian horrors at exactly this period (as before), were thoughtfully spared any exposure to the reports of the Japanese embassy delegation.






To our knowledge, that exhausts the accounts on the part of visitors who might, conceivably, be taken seriously in  

 the West, prior to the visit of the two U.S. reporters in December 1978.[^ch06-fn175] There were others. A visit by a group led by an "editor of a Chicago-based Marxist weekly" received a 38-line notice in the New York Times[^ch06-fn176] reporting only that they "painted a glowing picture of life under the Communists" and denied atrocity claims. Daniel Burstein, editor of the Communist Party Marxist-Leninist newspaper The Call (Chicago) was interviewed on the MacNeil/Lehrer Report (see note 53), where, again, he denied these claims on the basis of interviews with "average people" in the cities and countryside. Their account will naturally be given little credence in the West, since it is taken for granted that this Maoist group, with their ideological preconceptions, will report favorably on their visit. Skepticism is no doubt in order, though for accuracy, we should add that exactly the same is true in the case of reports by John Barron and Anthony Paul in the Reader's Digest of stories allegedly told them by "promising subjects,'' to whom they were "guided" by Thai officials, or reports by Henry Kamm of what he claims to have heard from a Cambodian in a cage in a Thai police station. If refugee reports transmitted by these highly dubious sources are given any attention, there could be no good reason to ignore the eyewitness reports of the only U.S. citizens to have visited Cambodia prior to December 1978. It should come as no surprise, however, that the accounts of the U.S. Marxist-Leninists were ignored or ridiculed in the press, while journalists and scholars greeted  

 Barron-Paul, Kamm, et al., as unbiased seekers after the truth.






There is more to the Burstein story. Given the uniqueness of his visit, major media enterprises had offered to publish photographs and text to be provided by Burstein. Specifically, he received payment for submitted material from Time, Newsweek, ABC television, and the Washington Post. Many months later, the first three stalwarts of the Free Press had definitely rejected the text artd photographs (refusing suggestions to rewrite, etc.), while the fourth was still mulling the question over. It is noteworthy that Time, Newsweek, and the Washington Post[^ch06-fn177] all had featured the faked photographs discussed earlier long after the fabrication was exposed, refusing to publish letters stating the unquestioned facts or to print retractions.






Visitors and refugees transmit quite different pictures. Refugees were brutalized, oppressed or discontented; otherwise they would not be refugees. Visitors are offered only a partial view, and they were for the most part initially sympathetic. We should anticipate, then, that visitors' accounts will be more favorable than those of refugees—though, as we have noted, and will see again, refugee accounts are not so uniform as the media barrage depicts. Note again that when we correct for the factors mentioned, conflicts between the refugee and visitor accounts need not be taken as indicating that one or the other must be dismissed; all might be accurate, in a country that presents a mixed picture with considerable local variation. That, in fact, would appear to be a fair conclusion from the full range of evidence so far available.






The media, however, pursue a different course. A highly selected version of what refugees have reported under quite unfavorable conditions was transmitted by observers of evident bias and low credibility, and given massive publicity as unquestionable fact. Reports of visitors were ignored or distorted. This was not an absolutely uniform picture, but it was a fairly general one. We have given a number of examples in the course of the exposition. A look at the material featured in the press in the fall of 1978, at the end of the period under review, confirms this picture.






The New York Times Magazine carried a major story by Henry Kamm in November entitled "The Agony of Cambodia."[^ch06-fn178] We have already investigated examples of Kamm's reporting on Timor and Vietnam, noting his extreme bias and unreliability.[^ch06-fn179] We have also seen how he distorted the account by the Yugoslav reporters. In the case of Vietnam, as we saw in chapter 4, Kamm pretended for a long period that there was no source of information apart from refugee reports, an obvious falsehood. By November 1978, Kamm evidently recognized that the pretense must also be dropped in the case of Cambodia. By that time U.S. journalists and other non-Communist observers had received invitations, and there were many reports available (outside of the Free Press) such as those we have surveyed. Kamm therefore describes the sources available as follows:


With the country almost hermetically sealed off from the world, except for rare and carefully guided tours for carefully selected visitors, refugees who cross the heavily mined and closely guarded borders to Thailand and Vietnam are the only reliable source of information about life in Cambodia since the Khmer Rouge troops strode into Phnom Penh on April 17, 1975.






In short, we can continue to dismiss the reports of visitors—as Kamm proceeds to do—and rely solely on what Kamm claims to have heard from the refugees he interviewed under the circumstances already described, or reports transmitted from Vietnam, which is at war with Cambodia. These reports are "reliable"; others are not.






Kamm then proceeds to outline what he says he heard from refugees. Much of it is inconsistent with what visitors have reported, from their own direct experience. But this fact deserves no comment, since the visitors have already been dismissed as unreliable. Thus, Kamm says that the Phnom Penh radio "is not listened to by the people of Cambodia, who have no radios." In contrast, Gunnar Bergstrom of the Swedish-Kampuchea Friendship Association (non-Communist, but sympathetic to the regime) reports that peasants had radios in the cooperatives he visited and listened to the radio regularly.[^ch06-fn180] Kamm also claims that the refugee reports are "told with striking similarity of detail in hundreds of refugee interviews." As we have seen, and will again see below, the reports vary considerably, as attested by qualified and independent observers. Kamm does not comment on the conditions of his interviews—though once again he describes an interview in a Thai police station—or what these conditions imply. He describes a regular work day of 13 hours with a half-hour break, again without reference to reports of visitors that explicitly contradict this account. His major conclusion is that "Cambodia's people labor to exhaustion, but they do not eat the rice they grow." "In a country once abundant with food, where hunger was the one human misery almost unknown, Cambodians go hungry all the time." This he describes as a "mystery." There seems to be adequate rice production, and little is exported, but the people are starving. He concludes that "rational explanations have perhaps never been the surest guide to understanding" Cambodia. Rational explanation is indeed difficult when dubious premises and preconceived conclusions must be reconciled with recalcitrant facts, a problem familiar to propagandists everywhere. Kamm does not tell us whether rational explanations are a surer guide to understanding the behavior of a superpower that pounded Cambodia to dust, or the practice of journalists who try to conceal the long-term impact of that not insignificant fact, perhaps because he knows that rational explanations do suffice in this case, unfortunately.






Kamm's belief that hunger was "almost unknown" in prewar Cambodia is in flat contradiction to analyses of the peasant society by specialists, who conclude that hunger and even starvation were common. His report that the people are now starving is in flat contradiction to the eyewitness testimony of non-Communist visitors, including the Swedish and Japanese embassy delegations as well as others. A possible resolution of his "mystery" is that the accounts he claims to have gathered in Thai police stations or under similar conditions of surveillance and coercion are inaccurate, and that even accurate refugee accounts give only a partial indication of a more complex reality. Even if we grant that Kamm is transmitting accurately what he heard, that would seem a plausible solution, but it is one that he is incapable of considering on ideological grounds, leaving him no alternative but to conclude that "what happens to the rice of Cambodia is one of the many mysteries enveloping the country."






Kamm's account is presented in the New York Times as "fact," not as the reactions of a highly biased observer of limited credibility. And it is taken as simple fact by others who have been trained to rely on the press without critical standards. Thus Mary McGrory, a liberal syndicated columnist who was strongly opposed to the U.S. war in Indochina, writes that "except for a Yugoslav television crew that was admitted by the government, the People's Republic of Kampuchea, as it is now called, has been cut off from the outside world. The ghastly accounts of its existence come from refugees all of whom tell the story...,"one of unrelieved misery and massacre: "In a recent article in the New York Times, Henry Kamm pointed out that while rice production is up, the Cambodians are on near-starvation rations."[^ch06-fn181]

On the same day that the New York Times published Kamm's article on Cambodia, the Boston Globe published a front-page feature story with a headline running across the entire top of the front page: "Cambodia now a 'slaughterhouse,' say refugees."[^ch06-fn182] The report, by Michael Parks, is reprinted from the Baltimore Sun, and was also given front-page coverage elsewhere.[^ch06-fn183] It is unclear why this story, which repeats material that has been presented in abundance in the press, adding nothing new or particularly topical, merits a screaming front-page headline. Parks relies almost entirely on refugee accounts; he does not indicate whether he heard these accounts himself or is transmitting them from some other source. These accounts, he writes, "vary little" and provide a ''uniform catalogue of horrors that verges on genocide." He repeats examples of the sort that have been widely publicized in the West since mid-1975.

Parks also refers to Japanese visitors to Cambodia, whom he does not identify, including "a Japanese correspondent" and "sympathetic visitors." He states that their description of cooperatives was "almost as grim" as the refugee stories of virtual genocide. This description he presents as follows: "With 5,000 persons, it had just brought rice production up to 1975 levels. The first efforts were just being made to build simple houses; a reopened elementary school had 190 children." Since he does not identify his source, we cannot judge whether his reference to "1975 levels" is correct; "prewar levels" seems more likely, considering what is known of 1975 levels, and Parks is silent on why it was necessary to try to achieve earlier levels of rice production. It is, perhaps, less than obvious that the description just quoted is "almost as grim" as a story of virtual genocide. This comment gives some insight into the way he evaluates the data available to him, however.






Parks also quotes the unidentified Japanese correspondent who writes ("nonetheless"): "We received the impression that these people [in the cooperative] had adjusted well to their new environment. In many ways the leisurely relaxed atmosphere peculiar to rural areas in the tropics had survived the political changes" (perhaps it is this remark that is "almost as grim" as a description of virtual genocide). Parks notes that the Japanese visitors asserted "that the peasants were well fed," but claims that they calculated the average diet at the cooperative as only 7 or 8 ounces of rice a day, far below other estimates; lacking any reference, his claim cannot be checked.






Parks is outraged by the report he attributes to the Japanese visitors that "Khmer Rouge leaders in Phnom Penh were living in luxury." Henry Kamm, in his story on the same day, also observes scornfully that government leaders "look remarkably well-fed, in splendid health and at ease in comfortable surroundings," while the population, he claims, is starving. Note again that visitors have reported that the population seems well fed, while at least some refugees and the leading U.S. government specialists have denied that Khmer Rouge cadres receive privileged treatment.[^ch06-fn184] But let us suppose that Park and Kamm are correct. If so, then Cambodia is similar in this respect to the other countries on their regular beat, where a minority lives in fabulous luxury while the peasants and urban slum dwellers subsist in misery. This fact, however, elicits no outrage beyond Indochina (the one region where there is reason to believe it is untrue).[^ch06-fn185]






We mentioned earlier William Shawcross's lengthy article on Cambodia in New Times, in which he expresses great concern over child labor—in Cambodia.[^ch06-fn186] Shawcross observes that Cambodia has been visited by Yugoslav journalists, "delegates from friendly Maoist parties in the West and trade groups from various Southeast Asian countries." He too states that in Cambodia "before the war, there was (in Southeast Asian terms) little hunger and no famine" and "the way of life was indolent"; so it may have appeared from a visit to Phnom Penh. He gives what appears to be a paraphrase of the Yugoslav report, but with a marked difference in tone. The Cambodians, he writes, "have developed the concept of the mobile Gulag," referring to the fact reported by Stanic and others that work teams move to wherever their labor is required. Furthermore, "Quite apart from shortages of food, life in the new cooperatives is hard. Work begins at 5 A.M. and lasts for at least nine hours," and there is often another shift at night. He does not explain how he knows that the work teams are a "mobile Gulag" rather than an attempt to rebuild a country destroyed by war. Nor does he comment on the apparent success of these efforts in overcoming the devastating effects of the U.S. war, which he describes, including the destruction of the agricultural system. He also fails to explain why he is so offended by a 9-hour work day in an impoverished peasant country. If indeed the cooperatives have managed to reduce working hours to a 9-hour day with occasional extra shifts, that would seem to be a considerable accomplishment. Such a work schedule was not at all unusual, for example, in Israeli kibbutzim a few years ago, to take an example from a far richer country receiving enormous aid from abroad, where such efforts were not denounced as evidence of the extraordinary harshness of the regime. For some Western journalists, a 9-hour work day may seem a major atrocity. Peasants, or for that matter farmers and workers in advanced countries, might have a rather different view.






Shawcross also states that "an estimated two million people, nearly one quarter of the population, have been killed in war and in internal purges." Since less than a million were reportedly killed in the war, Shawcross is asserting that over a million have been killed "in internal purges" since, a figure about ten times as high as the estimates by Barron-Paul or Ponchaud. He cites no source for this "estimate." But this is again typical of the numbers game in the case of Cambodia.






Shawcross observes that the numbers are less important than the question "whether or not the government has used murder and terror as deliberate acts of policy." He writes: "The evidence is overwhelming that it has done so. Madness of this nature defies rationalization." He does not, here or elsewhere, present evidence that the use of terror is systematic and deliberate policy, though he does relay reports of refugees who have recounted gruesome tales of terror. Presumably, he concludes from these reports that the policy of the regime was one of deliberate murder and terror. Perhaps his conclusion is correct, despite his failure to construct a case.[^ch06-fn187] Again, it is noteworthy that neither the quality of his evidence, its selection, the demonstrated lack of credibility of his major sources (of which he was by then aware, at least in part), or the vast gap between his evidence and his conclusions seems to him to require any discussion.






Here as elsewhere Shawcross is quite careful to discuss the effects of U.S. military and diplomatic intervention. Others are less scrupulous in this regard. Thus Jack Anderson, interviewing Lon Nol ("a sad symbol of the serene little country of Cambodia, which he once ruled") presents the pre-1975 history as follows:






The Cambodians are a gentle if emotional people. They wanted only to live in peace in their lush kingdom, with its rich alluvial soil, washed by the pelting rains. But with the collapse of U.S. power in Southeast Asia, Lon Nol gave way to a fanatic regime that has brutalized the populace. Hundreds of thousands have been murdered by their new rulers, and other thousands have fled in terror.[^ch06-fn188]






Anderson is one of the country's major liberal syndicated columnists, who has devoted many columns to Cambodian atrocities, beginning with a report on June 4, 1975, alleging that the Khmer Rouge "may be guilty of genocide against their own people."[^ch06-fn189] He has ample staff and resources, and surely knows that it was not simply "the collapse of U.S. power in Southeast Asia" that is responsible for starvation, disease, destruction, and revenge in Cambodia. But it is appropriate, in the current phase of imperial ideology, to excise from history other major factors with which he is quite familiar (as well as others that he may know nothing of, such as the realities of peasant existence), and to speak of Cambodia as a "serene little country" of "gentle people" plunged into disaster and misery by the "collapse of U.S. power."






In discussing Sihanouk's characterization of Communist Cambodia in the preface to this volume, we pointed out that he presented a dual picture, with aspects that were, from his point of view, both positive and negative. The reports of visitors tend to substantiate the picture he presented on the basis of the very limited evidence available to him. But their reports were either ignored, or else generally reinterpreted in the Free Press to conform to the required negative image. The two U.S. reporters who visited in December 1978, Richard Dudman and Elizabeth Becker, were able to reach an unusually large audience with their own words.[^ch06-fn190]


The New York Times dismissed their visit in a line. Bernard Weinraub, in the 11th paragraph of a 13-paragraph story on reported purges in Cambodia, remarked that their visit "produced no substantial surprises since the visitors saw only what the government wanted them to see."[^ch06-fn191] It is true enough that their visit produced no substantial surprises, at least for people who were not restricted to the Free Press for their information. In fact, what Dudman and Becker observed was not very different from what had been reported by earlier visitors. But it was markedly different from what the New York Times and other journals had been offering as standard fare, as we see at once when we compare their eyewitness reports with the version of postwar Cambodia that had been offered by the Reader's Digest, the New York Times, the New York Review of Books and other mainstream Western sources.



Richard Dudman, an experienced foreign correspondent with excellent credentials, commented that although "the visit amounted to a conducted tour...there was plenty of opportunity for observation in tours of 11 of the 19 provinces." His conclusions conform to the dual picture that emerges from consideration of the range of evidence previously available:




It seemed evident throughout this reporter's visit to Cambodia before the recent Vietnamese attack that the new Cambodia's version of Communism had no place in it for anyone who wanted to read, write, or even think independently, or for anyone who wanted to own more than a bare minimum of personal property.






At the same time, the physical conditions of life may well have improved for many peasants and former urban dwellers—possibly for the vast majority of the population, as the regime claimed.






Apart from the "austere standard of hard manual labor" and restrictions on "the freedoms accepted or at least professed by most of the rest of the world" that Dudman observed, his inability to make contact with former urban residents tended to confirm the dark picture of repression and atrocities conveyed by the refugee accounts that have been publicized. "The new Communist Cambodia," Dudman wrote, "became one huge work camp, but its people were clearly not being worked to death and starved to death as foreign critics often charged":






What I have found in two weeks of touring Pol Pot's Cambodia—under strict government supervision but with a good opportunity for observation—was a regimented life of hard work for most Cambodians, leavened, however, by much improved housing, regular issuance of clothing, and an assurance of apparently adequate food. I did not find the grim picture painted by the thousands of refugees who couldn't take the new order and fled to Thailand or Vietnam. In this lull between wars, those who remain appeared to be reasonably relaxed at the height of the busy harvest season. They sometimes leaned on their hoes like farm workers everywhere. And they often stared and then smiled and waved at the rare sight of Western faces. Workers usually appeared to be operating under their own direction. There were no signs of government cadres giving orders or armed guards enforcing the working hours, although individuals seemed to know what was expected.






The work day, Dudman found, lasted from about 6 a.m. to 11 a.m. and again from 1 p.m. to 5 p.m. Dudman found the housing program ("one of the world's great housing programs") particularly impressive, "a sudden mass upgrading of the individual family homes from the standard that has existed for centuries," which "probably meant better living, too, for the hundreds of thousands of country people who were driven into the cities by the five year war ..." as well as for the peasants who remained on the land. Until the Vietnamese invasion, prospects for economic development "appeared bright." Cambodia was feeding itself and had resumed rice exports, and the crucial water-control programs of the postwar years appeared to have been generally a success. He saw no evidence of starvation, contrary to standard claims in the U.S. media, and found the country "to be flourishing and potentially prosperous—at least until the Vietnamese invaders moved in." U.S. specialists, Dudman wrote, "have acknowledged that the Cambodian claim of reviving rice production to the point of resuming exports would, if true, be a spectacular achievement." It may well have been true.






Dudman also describes "a wide range of industrial growth—concentrated more in tiny and primitive cottage industries such as brick-making, silk spinning, and local blacksmith shops, but including also a fairly sophisticated rubber factory..." Development was decentralized and aimed for a high degree of local self-sufficiency. He describes "a progressive industrial growth plan" that seemed not unrealistic, judging by the account that he and earlier visitors have given. He also gives a brief account of the organization of the cooperatives.






Recognizing that the peasant population probably did not regard the "austere standard of hard manual labor" (specifically, a nine-hour work day) as an onerous imposition of the regime, and may not have been overly concerned that privileged urban sectors were compelled to share the hard but improving life of the poorer peasants, one might reach the conclusion that much of the population may well have supported the regime, particularly if it is true, as Dudman was informed but could not establish, that "decisions were taken collectively" in the cooperatives and even the army.






Elizabeth Becker's six-part series in the Washington Post covers much the same ground in less depth, and is in some ways more revealing about the character of U.S. journalism than it is about Cambodia. She found the development program generally incomprehensible: "no one seems able to offer a coherent philosophical basis for the extreme upheaval that has taken place." She does not go into how this alleged failure compares, say, with the "philosophical basis" for the developments in far more favored Thailand discussed in the preface to this volume, or comparable phenomena in other regions where a dependency model has been imposed. She writes that she is ''forced to conclude" that the economic system "seems to be working," revealing plainly the initial bias that colored all of her observations. It is also remarkable to see how uncritically she accepted Cambodian charges which, she claims, supported U.S. positions during the Vietnam war. She writes that she was given "a remarkable new document"—namely the Cambodian government Livre Noir of September 1978,[^ch06-fn192] which had in fact been on sale in New York well before she left for Cambodia—which "confirms" U.S. claims and "discloses" that there were 200,000 to 300,000 Vietcong in the northeast region of Cambodia, including the Central Committee of the Vietnamese Party (COSVN), when Nixon ordered the 1970 invasion. It estimates the total number of Vietcong in Cambodia in 1970 at 1.5-2 million.[^ch06-fn193] The Livre Noir, which is a bitter attack on the Vietnamese Communists, is certainly worth reading, but surely no serious commentator would accept uncritically a propaganda document produced in the midst of an ongoing war. U.S. reporters have rarely paid attention to material from comparable sources "confirming" or "disclosing" alleged facts that contradict positions taken by the U.S. government.[^ch06-fn194]






We have already noted the New York Times dismissal of the Dudman-Becker visit. Newsweek ran an uninformative article by Becker[^ch06-fn195] and Time reviewed their visit in an article that simply repeated its familiar rhetoric about "the shroud of terror and darkness" of a regime that was attempting to "counteract its worldwide image as a merciless, anonymous and genocidal regime," systematically avoiding the direct observations that Dudman (and, in part, Becker) had reported, in particular, those that were positive.[^ch06-fn196]






Malcolm Caldwell was assassinated on the final day of the visit, in Phnom Penh. According to Dudman, "Caldwell expressed general sympathy with the Cambodian brand of Communism prior to the Vietnamese invasion" and "the report that he was experiencing a change in views was not true," as Dudman knew from conversations throughout the two-week trip "up to a few hours of his death." In these conversations, "Caldwell remained sympathetic to the Cambodian revolution, without blinding himself to its faults," likening it to early stages of the industrial revolution in England. It "seems out of the question," Dudman writes, that the Cambodian government, which "had everything to lose from the incident," could have had anything to do with the assassination, contrary to speculations that have been rife. Dudman's conclusion seems well-founded. The true story will probably never be known, but the consequences of the assassination are clear enough. It is most unlikely that Caldwell's account of what he had seen would have reached any segment of international opinion apart from the left. And for the left, judging by what he had written in personal letters and articles before his trip and by the fact that "he remained fully sympathetic to the Cambodian revolution" (Dudman), his message would have tended to support the Pol Pot regime and to undermine the justification for the Vietnamese invasion that was being presented in the Western and Soviet bloc press.[^ch06-fn197]






As we have seen, refugee accounts are not as uniform as accounts in the press suggest. A further look bears out the conclusion. The most extensive published report of a refugee interview, to our knowledge, is a study based on conversations with Peang Sophi, who escaped from Cambodia in January, 1976, and arrived in Australia three months later.[^ch06-fn198] "His account of life under the revolutionary regime," Chandler comments,






differs in two important ways from others readily available in the West. Firstly, he spent over six months working actively—and rather happily—under revolutionary guidance; unlike many refugees, he was not punished by the regime for having roots in the "old society." Secondly, from about September onwards, he enjoyed considerable responsibility, as the "economic" foreman of an 800-man rural work team.






Chandler also observes that his experiences may not be typical. He lived in a province with "a unique (but recent) revolutionary tradition" and unusual prosperity, where "revolutionary cadre...may have been especially vengeful and undisciplined, too; certainly most tales of atrocities told by refugees refer to events in Battambang" [Sophi's province].[^ch06-fn199] Sophi reports that the Khmer Rouge cadre were "thin and pale," mostly young peasants. They admitted that in the early stages of liberation "they were subject to 'uncontrollable hatred'" and that "in this mood" conducted executions of Lon Nol officials and destroyed military equipment. They were "real country people, from far away" (Sophi's emphasis), illiterate, unfamiliar with urban amenities and frightened even of tin cans. "One speaker allegedly said: 'We were so angry when we came out of the forest that we didn't want to spare even a baby in its cradle.'" But Sophi reports that the executions were ordered halted shortly after. The cadres had no special privileges and were friendly in their relations with villagers and workers. Their program was successful because it seemed attractive, with a special appeal to youth. "Although he remained unconvinced by the totality of Khmer Rouge teaching, Sophi was impressed by the integrity and morale of many cadre, and by the ideology embodied in official directives and revolutionary songs." Their goals were a vast increase in the population, distribution of power and responsibility to people with poor peasant background,[^ch06-fn200] hard work (though working conditions, he says, were not particularly severe, hours were flexible, and rations usually sufficient), "the moral value of collective labour," and true independence based on self-reliance. Differences in status were obliterated, along with "begging and arrogance," and there was a consistent "puritanical strain" in regulations. Obviously unhappy with the new society, Sophi nevertheless offers an account that is not unsympathetic—and that has yet to be reported in the mass media, to our knowledge. His account also suggests an answer to the "difficult question," though one too unwelcome to be reported.






[^ch06-fn101]: We are concentrating on fabrications and distortions in the U.S. press, but it should be noted that the phenomenon is worldwide. For some documentation on fabrications in the French press and television, which elicited no comment or explanation when they were exposed, see Pierre Rousset, "Cambodia: Background to the Revolution," Journal of Contemporary Asia, vol. 7, no. 4, 1977. See also note 48.











Another example is a widely published photo taken by the West German journalist Christopher Maria Froder, showing a Khmer Rouge soldier brandishing a weapon, according to the photographer, to prevent looting of shops in Phnom Penh after its liberation on 17 April 1975. The picture appeared in the Far Eastern Economic Review, 14 April 1978, with the caption "Khmer Rouge takeover: Savage Repression." The Review refused to publish a letter by Torben Retbøll noting that after the photo had appeared in Die Welt (West Germany, 9 May 1975) with the claim that the soldier was looting, and in Der Stern (29 April 1976) with the caption: "After the victory, there followed the revenge against the rich," the photographer protested the falsification on German TV (the facts were correctly reported in the West German Befreiung). But on 15 August 1976, the Sunday Telegraph (London) again published the photo as an illustration of Khmer Rouge brutality as did Newsweek in the issue just cited. Retbøll's appeared in News from Kampuchea (Australia), vol. 2, no. 2, November/December 1978, to an international audience of 500 people. The same picture appeared in the Washington Post (9 May 1975, with the caption: "Khmer Rouge soldier angrily orders Phnom Penh shopkeepers into streets"), and again in the New York Times Magazine (Henry Kamm, "The Agony of Cambodia," 19 November 1978), this time with the caption: "Conquering Pnom [sic] Penh in 1975, a Khmer Rouge soldier rounds up merchants," illustrating that a good piece of propaganda never dies.






[^ch06-fn102]: There are many others. For example, one of the fabricated photographs appears in the Soviet journal Literaturnaja Gazeta, 4 October 1978, in an article devoted to atrocities in Cambodia that quotes extensively from the U.S. press. Torben Retbøll has informed us of a number of Western European examples: Der Spiegel, 30 January 1978, who refused to print a letter of correction, like their U.S. counterparts; the Danish journal Ekstra Bladet, on three separate occasions (3 May 1976, 28 December 1977, and 4 January 1978); the London Observer (30 October 1977) on the front page.






[^ch06-fn103]: George Orwell, "Notes on nationalism," 1945. In Sonia Orwell and Ian Angus, eds., The Collected Essays, Journalism and Letters of George Orwell, vol. III, Harcourt Brace & World, 1968, p. 371.






[^ch06-fn104]: Communiqué du Ministre de l'information et de la propagande (Hu Nim), 31 March 1976. Hildebrand and Porter (op. cit., p. 70) cite a government report of 15 April 1976 alleging that several hundred thousand draught animals were killed in rural areas. Whatever the actual numbers may be, they are surely not small. As we have seen, the same is true throughout Indochina.






[^ch06-fn105]: Ponchaud, op. cit., p. 55. See also chapter 5, on similar conditions in Laos.






[^ch06-fn106]: New York Times (14 June 1976).






[^ch06-fn107]: Op. cit., p. 340n. As noted earlier, this is only one of several cases where Snepp offers evidence based on what may very well be intelligence fabrications.






[^ch06-fn108]: Richard Holbrooke informed the Congressional Committee in the July Hearings that Twining, Carney and Kenneth Quinn, "form to my mind, the American core of expertise on Cambodian affairs today in the U.S. Government" (p. 2). As we shall see, Quinn also refers to this alleged interview, and may well be the source of its wide dissemination. Twining, when asked what public statements the Cambodian government has made about executions, replied: "The little that has been said publicly, when Khieu Samphan was in Colombo, for example ..." (p. 12). It is not clear whether he is referring to the "interview" or to Khieu Samphan's statements at the Colombo meetings. Thus of the three specialists who form "the American core of expertise on Cambodian affairs today in the U.S. Government," two cite this "interview" as genuine, perhaps three, depending on what Twining had in mind in this reference.






[^ch06-fn109]: July Hearings, p. 22.






[^ch06-fn110]: 1 May 1977.






[^ch06-fn111]: Barron and Paul, op. cit., p. 202. In their article in the Reader's Digest, February 1977, the story is reported slightly differently. For a full discussion of the various versions and their authenticity, see Torben Retbøll, "Cambodia—the Story of a False Interview," unpublished ms., 1978. Retbøll, a Danish historian, is one of the small number of people in the West who care enough about the facts to pursue the details and write to journals that print false or dubious information, and like others, has been regularly subjected to vilification and abuse for this unwelcome commitment to the truth.






[^ch06-fn112]: This was a personal letter to Chomsky commenting on the article cited in note 100.






[^ch06-fn113]: Barron says: "Ponch [sic] assisted us extensively in our interviews in France. He compared data with us, criticized our work, and challenged in some cases our findings." May Hearings, p. 48. Paul cites a letter from his research colleague on the book who claims to have been "in almost daily contact with Father Ponchaud." (FEER, letter, 9 December 1977). We cannot comment on the authenticity of these remarks for reasons discussed below.






[^ch06-fn114]: Cambodia: Year Zero, p. xvi. Ponchaud cites one of these letters in his note for the American translation, p. xiii. See below, p. 318.






[^ch06-fn115]: See p. 158, above.






[^ch06-fn116]: William Shawcross, "The Third Indochina War," New York Review of Books, 6 April 1978.






[^ch06-fn117]: See among others, Ieng Sary (interviewed in Der Spiegel, 9 May 1977, by Tiziano Terzani), who estimated the population at 7,760,000 and explicitly denied the reports by Barron-Paul and others of massacres (it is curious that one constantly reads that the Cambodian government had not denied these claims). In the May Hearings, after Porter had questioned the Famiglia Cristiana "interview" (noting that the Cambodian government has repeatedly estimated the population at 7.7 million), John Barron attempted to defend his use of the alleged interview, with the following claims: (1) "other Cambodian officials at approximately the same time had stated that there were 5 or 5.2 million inhabitants of Cambodia"; (2) "The figure of 7.7 million mentioned by Mr. Porter I have seen stated one time, and that was in a claim made shortly after the first anniversary of the revolution" denying massacre claims; (3) "I don't know of anybody in the world who has ever contended that the population of Cambodia ever was that large." As for (1), Barron cites no examples and we know of none. As for (2), he was probably referring to the Ministry of Information communique cited in note 104, which estimated the population at 7.7 million, a figure that has been repeated often. But the most surprising claim is (3). Ponchaud, Barron's major nongovernmental source, writes that "in 1970 the population of Cambodia was usually estimated at 8 million" (including 400,000 Vietnamese); op. cit., p. 70. The UN estimated the population in mid-1974 at 7.89 million (see below, p. 264) and in mid-1976 at 8.35 million (cf. UN Monthly Bulletin of Statistics, February 1978). Swedish visitors to postwar Cambodia have reported that the population is 8 million and that efforts are being made to increase it to 15 million. Estimates in the 7-8 million range are standard. In their book, Barron and Paul write that "no one heretofore had contended that the prewar population of Cambodia was more than seven million ..." (p. 202n.)






[^ch06-fn118]: It has also been cited on television, e.g., by Leo Cherne of the International Rescue Committee, on the MacNeil/Lehrer Report (see note 53). He claims that when Khieu Samphan "was asked what is the population of Cambodia, he said five million. The population of Cambodia used to be 8 million." Cherne notes that this estimate of five million is inconsistent with a population estimate offered by Pol Pot in "Peiping" (the name used for Peking by Dean Rusk, Leo Cherne and others of their political persuasion). This "disparity in the population of Cambodia" is offered as the sole example of "the most remarkable revelations" by Pol Pot. It is, of course, only a "remarkable revelation" to someone who relies on such sources as Famiglia Cristiana for his knowledge of international affairs. Recall that it is this "remarkable revelation" that Cherne relied upon to explain why executions have diminished (see note 37, this chapter). The above appears to be the intended sense of some rather confused remarks by Cherne. We rely on the written transcript, Library no. 702, Show no. 3242, 6 June 1978.






[^ch06-fn119]: Economist (London), 26 February 1977.






[^ch06-fn120]: FEER, 23 September 1977.






[^ch06-fn121]: Kenneth M. Quinn, "Cambodia 1976: Internal Consolidation and External Expansion," Asian Survey, January 1977. Torben Retbøll has brought to our attention that in this article, Quinn claims that Khieu Samphan "offered a partial explanation" for the reduction in population on grounds of war dead and the return of "600,000 ethnic Vietnamese" to Vietnam. But in fact nothing of the sort appears in the cited "interview." If this "interview" is indeed an intelligence fabrication, as appears not unlikely, it may be that it went through several versions before being placed in Famiglia Cristiana, to be picked up by the world press.






[^ch06-fn122]: Op. cit., p. 212.






[^ch06-fn123]: "Cambodia 1977: Gone to Pot," Asian Survey, January 1978.






[^ch06-fn124]: See Volume I, chapter 3, section 5.4.






[^ch06-fn125]: To add an unnecessary little extra, the same issue of Famiglia Cristiana contains an insert on Sihanouk, referring to "a suspicion, expressed in Le Monde August 8, that the entire family of the Prince has been exterminated." Retbøll (op. cit.) points out that the reference is to a fabricated "appeal" published in good faith by Le Monde with the signatures of well-known French leftists. Two days later, Le Monde published an apology when it discovered that the signatures were forged—a fact not mentioned in the Famiglia Cristiana report. This fact alone might have suggested that this journal is hardly a trustworthy source, had the question been of any concern.






[^ch06-fn126]: See chapter 2 of this volume, p. 29-30, for one of many examples. It is difficult to imagine that the CIA, with its long history of deception in Indochina, has suddenly ceased its disinformation campaigns. Ed Bradley of CBS news, asked on the MacNeil/Lehrer Report to comment on the "allegation that there is a disinformation network at work spreading these allegations" of Cambodian atrocities, responded: "I don't have any doubts that there is some element of truth in it...," a plausible surmise. The alleged "interview" is not found in the regular FBIS translations though it does appear in a special "For Official Use Only" supplement to the Daily Report for Asia and Pacific. Thus it is not available to regular library subscribers, but presumably is available to selected individuals to whom it can be "leaked." We are indebted to Stephen Heder for this information.






[^ch06-fn127]: Barron and Paul, op. cit., p.197.






[^ch06-fn128]: 18 February 1976.






[^ch06-fn129]: Paul defends the translation in a letter to the Far Eastern Economic Review, 9 December 1977, citing the research colleague who claims to have been in almost daily contact with Ponchaud (see note 113, this chapter). He ignores the question of the actual source of this alleged quote, to which we turn directly—something that should have been known to a person in almost daily contact with Ponchaud, who allegedly approved this specific translation.






[^ch06-fn130]: Such claims, for which no specific evidence is offered, are emphatically denied by at least some refugees. See below, p. 243. They are also denied by the State Department's leading specialist, Charles Twining. See July Hearings, p. 21. See also Quinn's comment on the austerity of the cadres, above, p. 178.






[^ch06-fn131]: Op. cit., pp. 60-61.






[^ch06-fn132]: Op. cit., p. 97 of the French original; see note 2, this chapter.






[^ch06-fn133]: See the references in note 82, this chapter, and the text at note 82.






[^ch06-fn134]: Ponchaud, "Cambodge: deux ans après la libération," Revue d'Etudes comparatives Est-Ouest, Volume 8, no. 7, 1977, pp. 143-156.






[^ch06-fn135]: Ponchaud, Cambodge Libéré. Dossier no. 13, Echange France-Asie, January 1976, p. 17.






[^ch06-fn136]: See note 17, this chapter. In Nouvel Observateur, 2 October 1978, Lacouture gave the same wording as a quote, attributed to Khmer Rouge cadres: the new generation charged with the building of Cambodia "needs only a million and a half to two million Cambodians to construct the country," (his emphasis). This article is an excerpt from Lacouture's October 1978 book Survive le peuple cambodgien!, Seuil, 1978. As we shall see directly, this reference appears in print over a year after Ponchaud, a close associate of Lacouture's, had withdrawn the quote and his interpretation of it as apparently without credible source.











Quite apart from the discrepancy of source and the changes in numbers and text (not to speak of the dubious source, to which we return), it is hardly clear that Khmer Rouge military commanders or whoever might have been the source for this remark, if anyone, "talk of Marxism." Specialists have noted that the Khmer Rouge leadership tended to stress independence, nationalism, manual labor, equality, etc., but not Marxism. According to Carney, Marxism-Leninism made its appearance in domestic radio broadcasts only in 1976. Timothy M. Carney, "Continuity in Cambodian Communism," in Carney, ed., Communist Party Power in Kampuchea (Cambodia), Data Paper number 106, Southeast Asia Program, Department of Asian Studies, Cornell University, January 1977, p. 23.






[^ch06-fn137]: See note 112, this chapter.






[^ch06-fn138]: See note 2, this chapter.






[^ch06-fn139]: Something unknown in the history of industrialization in the West or elsewhere in the "developing world," of course.






[^ch06-fn140]: Our emphasis. Penguin, 1978, p. 92.






[^ch06-fn141]: The subsequent (1978) Norwegian translation (Kambodsja Ar Null, Tiden Norsk Forlag, p. 84), retains the quote and the implication that the "formidable boast" is being put into execution. This translation was evidently supervised by Ponchaud, since there are some revisions of the French original as well as new material. See note 395, this chapter.











Skepticism about the source of this alleged quote had already been expressed by Gareth Porter (May Hearings, pp. 51-52), properly, it is now clear. Ponchaud's qualifications in his letter regarding the quote are noted by Malcolm Caldwell (Manchester Guardian, 8 May 1978). He comments: "Yet, without a move on Ponchaud's part to correct the misuse, the construction of threatening a systematic massacre is the one still put on it by authors determined to slander Kampuchea at any cost to honesty and integrity." This comment takes on added weight now that Ponchaud has deleted from the American edition both the "quote" and the inference drawn from it.






[^ch06-fn142]: This passage is given separately in small print, apparently indicating that it is a quote, or standard report of refugees, or something of the sort. July Hearings, p. 12.






[^ch06-fn143]: FBIS Daily Report, Asia and Pacific, 12 May 78, p. H3.






[^ch06-fn144]: 23 September 1977.






[^ch06-fn145]: This egregious comment is typical of the colonialist mentality. While the friends and associates of Westerners in Phnom Penh may have been "fun-loving" and "easy-going" as they enjoyed themselves at the expense of the peasant population, the latter appear to have endured a rather different existence, a matter to which we return.






[^ch06-fn146]: FEER. 25 August 1978. Note that Wise is reviewing the British edition.






[^ch06-fn147]: In the same review, Wise claims that Ponchaud dismisses the excuse that Phnom Penh was emptied to avoid famine as "rubbish" because "there was enough stocked rice to feed between 2.5 million and three million people ..." Compare what Ponchaud actually wrote: This explanation for the evacuation, "given as the essential one, is not fully convincing." The "more than 1.5 million peasants" who had been driven into Phnom Penh "were all eager to return to their homes without being forced to go" and as for the rest of the population, stocks of rice on hand "might have fed it for two months, with careful rationing" (at which point, presumably, they would have starved to death). Op. cit., pp. 20-21. Note further that on inquiry Ponchaud concedes that his estimate may have been exaggerated. See below, p. 312. But for Wise, Ponchaud has shown the explanation to be "rubbish." This explanation was, as Ponchaud states, commonly given as the essential one. See the comments by Ieng Sary, reported from Tokyo, AP, Washington Post (14 June 1978) for one example.











Wise also makes the following curious remark: Ponchaud "eloquently smothers the naive theories of alleged experts who—even before Ponchaud's book appeared—had decided there were no massacres after the communists took Phnom Penh in 1975 ..." (his emphasis). He cites no such "experts." Note also Wise's curious implication that prior to the appearance of Ponchaud's book in January 1977 it was somehow illegitimate to draw conclusions—at least, the unauthorized ones—about Cambodia.






[^ch06-fn148]: See note 136, this chapter.






[^ch06-fn149]: AP, "UN chief invited to Cambodia," Christian Science Monitor. (14 October 1978). See also Frederic A. Moritz, "Critics crack Cambodia's closed door," ibid., 16 October 1978, noting also the visit of a "left-wing China-oriented Hong Kong" newspaper reporter in September, one of the many whose reports received no coverage in the Western media.






[^ch06-fn150]: See New York Times, 7 March 1976, and for a review, Laura Summers, "Defining the Revolutionary State in Cambodia." Cambodia circulated photographs of the incident, but they do not seem to have been published in the U.S. press, which much prefers faked photos produced by Thai intelligence to illustrate alleged Khmer Rouge atrocities. See Heder, "Thailand's Relations with Kampuchea," pp. 27-28, 77-79 (cited in note 90, above).






[^ch06-fn151]: Ross H. Munro, "Envoy Touring Cambodia Finds a No-Wage System," New York Times, (9 March 1976), dateline Peking.






[^ch06-fn152]: Elsewhere, he is quoted more positively as saying that he had seen "enormous numbers of children who looked quite healthy and quite lively." Toronto Globe and Mail, (8 March 1976), cited by Porter in the May Hearings, p. 28. In the Times account he is quoted as saying, in response to a query about starvation: "How can I judge? I saw no signs of starvation."






[^ch06-fn153]: Number 2, 1976. We quote from the German translation in Befreiung, June 1976.






[^ch06-fn154]: Similar impressions can be derived from a reading of Ponchaud's book, though rarely from the secondary references.






[^ch06-fn155]: The official Cambodian government estimate was 200,000. See Ieng Sary's interview in Spiegel (cited in note 117.) It is probable that this estimate was intended to include the suburbs, which according to visitors were more populated than the city itself.






[^ch06-fn156]: Recall that according to Ponchaud's 1978 book, the worst terror was over by the time of Lundvik's trip; see note 37.






[^ch06-fn157]: Sydney Morning Herald (Australia, 30 December 1977); cited in News from Kampuchea, Vol. I, no. 5, December 1977. The Committee of Patriotic Kampucheans, which published the journal, at that time included Ben Kiernan, an Australian specialist on Cambodia; Shane Tarr, a New Zealander who lived in Cambodia until April 1975; and a group of Cambodians in Australia, three of whom lived in areas under Khmer Rouge administration in 1970 and 1975. In keeping with the theory of the Free Press, it was not subject to censorship and the information it presented about Cambodia was available to the Western reader, journalists included. In further confirmation of the same theory, its documentation and positive accounts of postwar Cambodia reached an audience of about 500 people throughout the world.






[^ch06-fn158]: Both on 23 January 1978.






[^ch06-fn159]: Henry Kamm, New York Times (3 February 1978).






[^ch06-fn160]: Lewis M. Simons, "Cambodians Reported to be Well-Fed," Washington Post, (28 April 1976).






[^ch06-fn161]: See note 40 of this chapter.






[^ch06-fn162]: 19 May 1978.






[^ch06-fn163]: The text appears in News From Kampuchea, vol. 2, no. 1, May 1978.






[^ch06-fn164]: SWB, Far East, 5801/B, 3-9, 29 April 1978.






[^ch06-fn165]: Michael Dobbs, "The New Cambodia: Phones, TV, Cars on Rubble Heaps," Washington Post, (23 March 1978).






[^ch06-fn166]: AP, Boston Globe (29 March 1978).






[^ch06-fn167]: See the reference in note 198 below and Ponchaud, op. cit., p. 113.






[^ch06-fn168]: Cambodge, published by the Ministry of Information of the Royal Government of Cambodia, Phnom Penh, 1962, p. 116.






[^ch06-fn169]: "Yugoslavs, After Rare Tour, Tell of a Primitive Cambodia," 24 March 1978.






[^ch06-fn170]: Henry Kamm, "Cambodian Refugees Depict Growing Fear and Hunger," New York Times, 13 May 1978. As both the Post and Times correctly reported, the Yugoslav journalists said they saw no signs of food shortages. Once again Kamm notes that some of the refugees he interviewed were in a "small cage" in a police station, others in a "disused prison" and refugee camps, where "their bearing and comportment recall concentration camp survivors in the Europe of 1945"—a fact that conceivably relates to the conditions of their detention. See p. 162 above.






[^ch06-fn171]: The same "implicit restrictions" prevented them from raising questions about atrocities, he explains. Kamm's remarks on "communist fraternalism" are no doubt appropriate, though Yugoslavia has been known on occasion to exhibit some slight degree of independence, one recalls. But more to the point, Kamm neglects to mention the "implicit restrictions" imposed by "capitalist fraternalism." For example, those that enable a Pulitzer-Prize winning specialist on the misery of refugees to inform his reading public that refugees in Timor are fleeing from the mountains where they have been "forced to live" by FRETILIN guerrillas; this apparently on the authority of a kindly Indonesian general, not—perish the thought—interviews with refugees. Unlike Cambodian refugees in Thai prisons, these unlucky souls are not proper subjects for a reporter of such independence of mind. See Volume I, chapter 3, section 5.4.






[^ch06-fn172]: William Shawcross also reports that "The Yugoslav journalists were shocked by the extent of child labor," and reports the same account of the filming. "Cambodia Today: a Land of Blood and Tears," New Times, 13 November 1978. The subheading of this story (which is featured on the front cover) includes the statement that "Cambodia today is a 'hell on earth.'" As the story itself indicates, this is a quote from Hanoi radio, which has rarely been regarded as a reliable source in Western journalism, but is taken quite seriously when it provides negative information about Cambodia in the midst of a bitter war. See note 18, above.











The concern of Western journalists over child labor is rather selective. A rare report on the topic filed from Thailand received little publicity in the United States and aroused no noticeable outrage: Amport Tantuvanich, AP, "Slavery the fate of these children," Boston Globe (24 September 1978). The report describes children working in Thai factories "hour after hour without a break around furnaces that generate 1450-degree heat. Their arms and hands bear scars from burns and cuts..." There are tens of thousands of illegally employed children, some "sold by their parents to factory owners" and working as "virtual slaves." "A recent survey by the International Labor Organization in Geneva showed that of 52 million children under age 15 at work around the world, 29 million are working in South Asia." Many of the Thai laborers are under 10. "Labor specialists say that a combination of wide-open free enterprise and a lack of labor-union power contributes to the child labor problem. Under laws laid down by Thailand's military government, strikes and other labor union activities are forbidden." On the U.S. role in creating this situation, see Volume I, chapter 4, section 2. See also the preface to this volume.











Another example is the notable exploitation of child labor from the occupied territories in Israel. At the "Children's Market at the Ashkelon junction" one finds children aged six or seven trucked in by labor contractors at 4 a.m. to work on the private or collective farms in the vicinity, helping to make the desert bloom for their prosperous employers who pay them "a meager subsistence wage" though "often they are cheated even on that." Ian Black, "Peace or no peace, Israel will still need cheap Arab labor," New Statesmen, 29 September 1978. The miserable conditions of child labor (and Arab labor from the occupied territories in general) have been discussed and deplored in Israel (see, for example, Amos Elon, "Children's market at the Ashkelon junction," Ha'aretz, 2 August 1978), with no effect on the practice, however. The matter has yet to be discussed in the mainstream U.S. press, to our knowledge, surely not by those who are so deeply offended by child labor in Cambodia, a major atrocity that evokes memories of Hitler and Stalin.











Visiting Cambodia in the summer of 1978, Gunnar Bergstrom reports that he saw children working in the fields, mixing work with play in a manner not unfamiliar in peasant societies. See note 180, below. See also the reports cited in note 190, below.






[^ch06-fn173]: François Rigaux, "Un socialisme à la spartiate: le Kampuchéa démocratique," mimeographed, Centre Charles de Visscher pour le droit internationale, College Thomas More, Louvain, 1978.






[^ch06-fn174]: Denzil Peiris, "Phnom Penh's long march back," Far Eastern Economic Review, 13 October 1978. See the Asia 1979 Yearbook for further discussion of "the apparent achievements of Cambodian agriculture."






[^ch06-fn175]: There were Third World visitors, but their reports are unknown or discounted. Several reports can be found in News from Kampuchea. See also Summers, "Defining the Revolutionary State in Cambodia." See also note 149 of this chapter.






[^ch06-fn176]: "US Leftist Editor Says Cambodians Are Thriving," New York Times (12 May 1978). Six months later, a column by Burstein appeared on the Op-Ed page of the Times ("On Cambodia: But, Yet," 21 November 1978), two days after the New York Times Magazine published a major story by Henry Kamm, to which we return. Burstein's brief statement based on what he says he saw is "opinion"; Kamm's lengthy account of what he says he heard from refugees is "fact." Professor David Sidorsky of Columbia University denounced the Times for printing this "propagandistic opinion on questions of fact," (letter, 5 December). He did not criticize the Times for publishing Kamm's article with its faked photos, allegations about starvation taking no account of direct testimony to the contrary by visitors, etc. Nor did he criticize the Times for withholding evidence provided by visitors. Rather, his criticism was limited to the Burstein Op-Ed statement for not presenting factual evidence, as was obviously impossible in the space provided him.











In contrast to the coverage in the United States, visits by Danish Communists received substantial publicity in the Danish press, we are informed by Torben Retbøll. (Note that some of the visitors whose reports were suppressed in the Free Press were non-Communists, and there is little doubt that they would have been treated rather differently had their reports conformed to the propaganda line.) A detailed report by these visitors appears in The Call (P.O. Box 5597, Chicago Ill. 60680), May 15, 22, 29, June 5, 12, 1978; The Young Communist, June/July 1978; Class Struggle, Summer 1978. There was also a report in the Guardian (New York, 7 June 1978). See also Kampuchea Today, Call Pamphlets, December 1978, and a "photo-record" of their visit by David Kline and Robert Brown, The New Face of Kampuchea. Liberator Press, 1979. They say their trip covered 700 miles with frequent stops and discussions with government leaders and others.






[^ch06-fn177]: We regret that we cannot comment here on television news, since we have no records. We have cited the MacNeil/Lehrer Report on Cambodia on the basis of a transcript. Burstein informs us privately that lower-echelon reporters and editors were helpful and sympathetic, but that the idea was apparently killed at a higher level, a process not exactly unfamiliar to us personally. See the prefatory note to Volume I.






[^ch06-fn178]: Henry Kamm, "The Agony of Cambodia," New York Times Magazine, 19 November 1978. See note 101 on the accompanying illustrations.






[^ch06-fn179]: See Volume I, chapter 3, section 5.4; this volume, chapter 4. Note that his distortions are systematic; his extreme bias is consistently towards service to the U.S. government propaganda system, whether he is dismissing the testimony of refugees and other victims in Timor and relying on Indonesian generals, or dismissing the testimony of visitors to Cambodia and relying on what he claims to hear from refugees in Thai police cages, or grossly misrepresenting the available evidence from Vietnam.






[^ch06-fn180]: We rely on an hour-long taped interview in English, readily available to enterprising reporters, no doubt. Bergstrom has a number of interesting things to say, and seems careful and qualified in his account. For example, he visited areas where there was alleged to be insurrection, but saw no signs of disturbance and no security presence. Reports by U.S. journalists to the same effect many months later were front page news. As already noted, the work pace seemed to him moderate by European standards. He gives many details of the life he observed, and in general, reports a peasant society rebuilding with some success from the ruins, noting, however, that his access was limited.






[^ch06-fn181]: Mary McGrory, "Slow reaction to Cambodia bloodbath," Boston Globe, 27 November 1978. As the title indicates, the central point is that "for a while, Cambodia was hardly discussed," though finally, by mid-1978, it is receiving some attention. The statement is totally false, but, as we have seen, in keeping with the constant pretense of writers who send this message to their mass audience in the Reader's Digest, TV Guide, and the major journals, or in the more select periodicals.






[^ch06-fn182]: Boston Globe, 19 November 1978. On the same day, the Globe reports that "the Inter-American Human Rights Commission yesterday accused the Nicaraguan National Guard of murdering scores of unarmed civilians" in September, charging that "entire families were machine-gunned to death in their homes," that unarmed youths "were allegedly forced to dig their own graves before they were executed," along with other atrocities. This story made page 78. The preceding day a brief AP report noted that "despite pleas from the Nicaraguan opposition the Carter Administration has decided against trying to prevent Israel from supplying light arms to the regime of Nicaraguan dictator Anastasio Somoza Debayle, Administration sources said yesterday." None of this is major news, however and it elicited no editorial or other comment. On November 18 the New York Times reported (also not prominently, and in this case with no descriptive detail at all) that the Commission had accused the Nicaraguan Government "of flagrant, persistent abuses of human rights, including summary executions, torture, arbitrary detention, indiscriminate bombing of unarmed civilians and obstructing the humanitarian efforts of the Red Cross"; the government's "practices had victimized all sectors of the population but particularly the poor and people between the ages of 14 and 21." Nothing is said about the long-standing relation between the United States and Nicaragua. See Volume I, chapter 4, section 5.2.






[^ch06-fn183]: Cf. Philadelphia Inquirer (19 November 1978).






[^ch06-fn184]: See note 130.






[^ch06-fn185]: The New York Times is also not noted for outraged denunciations of gross differences in living standards in the United States. In New York City, for example, one can easily discover wealth that surpasses description only a short distance away from hovels where a grandmother stays awake through the night with a club to prevent rats from killing a child who will go to school the next day without breakfast.






[^ch06-fn186]: See note 172, above.






[^ch06-fn187]: It is not clear that he understands what is required to establish his case. See the serious error in logic discussed below, p. 322-23.






[^ch06-fn188]: Jack Anderson, "Lon Nol in Exile: Sad Symbol of Cambodia," Washington Post (1 October 1978). Some of Lon Nol's exploits in this "serene little country" in the 1970s are well-known. See, for example, Volume I, chapter 3, section 2. Anderson's mythical picture of prewar Cambodia is a very common one. Among many examples, an advertisement for a CBS news special on Cambodia reads: "Once, Cambodia was a very special place. Lively, Happy, Peaceful." New York Times (1 June 1978). The myth provides a useful backdrop for the picture of merciless horror and madness. See note 232, below.






[^ch06-fn189]: Cited in Jack Anderson, "In Cambodia, Obliterating a Culture," Washington Post (2 May 1978).






[^ch06-fn190]: Richard Dudman published an edited version of his series in a special supplement to the St. Louis Post-Dispatch (15 January 1979): "Cambodia: A land in turmoil." Elizabeth Becker's series appeared in the Washington Post, December 26, 27, 28, 29, 30, 31, 1978 (along with a December 24 story on Malcolm Caldwell's assassination in Phnom Penh). These accounts were serialized in many journals in the United States and elsewhere as they appeared in late December. Our quotes from Dudman are from the edited version cited.






[^ch06-fn191]: Bernard Weinraub, "High-Level Purge in Cambodian Regime Reported," New York Times (29 December 1978). Weinraub attributes this opinion to "American analysts." Times ideologists continued to disregard the reports by the U.S. journalists, just as they had dismissed earlier testimony from reputable non-Communist observers that was unacceptable on doctrinal grounds. Thus Dudman reports that "with good opportunity for observation" he found "an assurance of apparently adequate food" and no signs of malnutrition, confirming the reports of earlier visitors. But for Henry Kamm it is a matter of dogma that Communist policy has caused starvation ("Although the growing of rice was declared the supreme national objective and almost the entire nation was set to work at this task, the Cambodian people, for the first time in their history, learned hunger"—and contradicting himself in the very next sentence: "Until the war disrupted their lives, [hunger] was perhaps the one scourge of life that Cambodians had always been spared," which is false as well as inconsistent with what precedes). To maintain the dogma with its accompanying "mystery" already noted, it is necessary to ignore the reported facts, as Kamm does, in this article written a month after the accounts by the visiting U.S. journalists were widely circulated. Henry Kamm, "The Cambodian Dilemma," New York Times Magazine, 4 February 1979, an "analysis" with accompanying moral lecture that merits no further comment.






[^ch06-fn192]: Livre Noire, Faits et preuves des actes d'agression et d'annexion du Vietnam contre le Kampuchéa, Phnom Penh, September 1978.






[^ch06-fn193]: Becker states that the information in the Livre Noir "closely paralleled US intelligence estimates" of 1970. We know of no evidence that U.S. intelligence estimated in 1970 that there were 1.5-2 million "Vietcong" in Cambodia. Similarly, much of the other material in it does not parallel U.S. intelligence estimates, at least so far as the public record indicates. See Nayan Chanda, "The Black Book of Hatred," Far Eastern Economic Review, 19 January 1979, for some discussion of the Livre Noir and also of conflicting Vietnamese claims in the two-volume Kampuchea Dossier published in Hanoi. See Heder's articles cited in note 19 of the preface to this volume for detailed discussion of the background, including the longstanding conflict between Vietnamese and Cambodian Communists.






[^ch06-fn194]: They do, however, regularly accept documents and assessments produced in Hanoi and Phnom Penh prejudicial to the adversary, in the midst of a bitter conflict, on the principle that any negative information concerning a Communist regime, however questionable the source, must be accurate. See notes 18, 172 of this chapter.






[^ch06-fn195]: Elizabeth Becker, "Inside Cambodia," Newsweek, 8 January 1979. Her story deals only with Caldwell's assassination, the border war, the alleged support of the Livre Noir for U.S. intelligence estimates, atrocity stories from refugees, and the condition of Angkor Wat. It studiously avoids any report on what she actually observed of life in Cambodia.






[^ch06-fn196]: "Cambodia: Silence, Subterfuge and Surveillance," Time, 8 January 1979.






[^ch06-fn197]: See the preface to this volume.






[^ch06-fn198]: David P. Chandler, with Ben Kiernan and Muy Hong Lim, "The Early Phases of Liberation in Northwestern Cambodia: Conversations with Peang Sophi," Working Papers, no. 10, Monash University (Melbourne), undated (1976 apparently).




[^ch06-fn199]: We have already commented on the localized nature of atrocity reports noted by a number of analysts, Twining included. Chandler observes that the reason may be that conditions elsewhere are better, or that it is more difficult to escape from other areas. Ponchaud (in his author's note for the English translation) states that most of his reports come from the provinces near the Thai border, though "quite a few came from further away" (p. xv.). In an article published in January 1976 (N.B. after the worst atrocities; see above, note 37), Ponchaud wrote that Battambang-Siem Reap (i.e. the Northwest) is a region of "bloody violence more than any other"; cited by Porter, May Hearings, p. 24.




[^ch06-fn200]: See Summer's report, note 63.





