## Chapter 6.4 {.unnumbered}

After their "conjecture" that the awful fate visited upon postwar Cambodia results from the "chronic impotence" of Khieu Samphan, Barron and Paul add the following explanation of the success of the Khmer Rouge despite their terrorizing the countryside:






But what is in doubt is not so important as what is certain. Khieu Samphan and a few kindred people, who neither by achievements nor by ideas had ever attracted any substantial following, absconded into the jungles, assumed leadership of an insignificant, ineffectual little guerrilla force, captured control of a political coalition and through it absolute control of an entire society.[^ch06-fn301]






Sheer magic.[^ch06-fn302]






The "impeccable documentation" in this major work omits the many published sources that explain how the Khmer Rouge were recruited by the U.S. bombardment of the civilian society, a factor that the authors would have us believe is as irrelevant to an understanding of postwar Cambodian history as the actual situation in the countryside or the history of internal conflict.[^ch06-fn303]






Apart from their historical comments, there is a possibility of independent verification of Barron-Paul's evidence only in the case of the occupation of Phnom Penh, when many reporters were present at first in the city itself and later confined in the French embassy. We will therefore consider perhaps the most striking claim that they put forth from this period.






Barron and Paul claim that there was a major bloodbath. In Phnom Penh, they assert, some people saw "summary executions" and






virtually everybody saw the consequences of them in the form of corpses of men, women and children rapidly bloating and rotting in the hot sun. The bodies, sometimes grotesquely contorted in agony, yielded a nauseating, pervasive stench, and they had a transfiguring effect on the hundreds of thousands of people being exiled...[turning them into]...a silent, cowed herd...[^ch06-fn304]






Evidently, something so dramatic would be hard to miss, so one would indeed expect "virtually everybody" to have seen it.[^ch06-fn305]






Their supporting documentation falls into the two familiar categories: (1) a list of names of Cambodians; (2) verifiable documentation, namely: "Sunday Times (London), May 8, 1975; Mirror (London), May 9, 1975, AP dispatch from Bangkok, May 8, 1975."[^ch06-fn306] Turning to the verifiable documentation, consider first the Sunday Times, May 8. There is no such document. Presumably, they are referring to Jon Swain's report in the Sunday Times, May 11. Assuming so, we turn to Swain's account. There is no doubt of his fury over the "enormity and horror" of what he describes in gory detail, but he seems to have missed the consequences of summary executions described so eloquently by Barron and Paul as he was walking through Phnom Penh or observing from the embassy. He does not report having seen any signs of summary executions. He does transmit stories he heard about killings by soldiers, but that is all.






One of these stories is cited by Barron-Paul, with a little embellishment, as an example of a "summary execution." Swain presents it as follows:






A newly-arrived French teacher says that at 8:30 this morning he was on his way to the embassy when a Khmer Rouge patrol ran out of an alley and cut a line of refugees in half, splitting a family. When the parents protested the leader raised his rifle and shot them in the chest.






This second-hand report, if correct,[^ch06-fn307] would serve as a second-hand example of a "summary execution" under a broad interpretation of this concept, but provides no support for the far more dramatic claim that virtually everybody saw the consequences that Barron and Paul so vividly describe. Furthermore, this example does not support the major thrust of their argument, that the "summary executions," here and elsewhere, were commanded from on high as part of a systematic policy of genocide, perhaps a consequence of Khieu Samphan's "chronic impotence." Rather, it appears to be a case of a murderous act by soldiers of a conquering army, horrifying no doubt, but unfortunately all too common—for example, the "robbery and murder" committed by U.S. troops occupying Japan or their participation in mass murder of members of the anti-Japanese resistance in the Philippines, to take a case where the armed forces in question and the society from which they were recruited had not suffered anything remotely like the savagery that the Khmer Rouge had endured.[^ch06-fn308]






Actually, Swain does discuss the matter of bloodbaths, though Barron and Paul do not refer to these remarks. Commenting on the assurance by U.S. diplomats "that the revenge would be dreadful when the Khmer Rouge came," he writes:






I can only say that what I have heard and seen provides no proof of a bloodbath (and I would question the reliability of reports of mass executions that almost from the start have circulated outside Cambodia)...What has taken place, though equally horrific, is something different in kind. My overriding impression—reinforced as we journeyed through the countryside en route to the Thai border—was that the Khmer Rouge military authorities had ordered this mass evacuation not to punish the people but to revolutionise their ways and thoughts. Many thousands will no doubt die. But whatever else, this does not constitute a deliberate campaign of terror, rather it points to poor organisation, lack of vision and the brutalisation of a people by a long and savage war.






In this connection, Swain has something to say about a bloodbath that escaped the attention of Barron and Paul completely:






The United States has much to answer for here, not only in terms of human lives and massive material destruction; the rigidity and nastiness of the un-Cambodian like fellows in black who run this country now,[^ch06-fn309] or what is left of it, are as much a product of this wholesale American bombing which has hardened and honed their minds as they are a product of Marx and Mao...The war damage here, as everywhere else we saw, is total. Not a bridge is standing, hardly a house. I am told most villagers have spent the war years living semi-permanently underground in earth bunkers to escape the bombing. Little wonder that this peasant army is proud of its achievements...The entire countryside has been churned up by American B-52 bomb craters, whole towns and villages razed. So far I have not seen one intact pagoda.[^ch06-fn310]






His final thoughts are also perhaps worth quoting:






In the last five years, Cambodia has lost upwards of half a million people, 10 per cent of its population, in a war fueled and waged on its soil by outside powers for their own selfish reasons. The people who run, live in and try to reconstruct the heap of ruins they have inherited in Cambodia today deserve the world's compassion and understanding. It is their country and it was their sacrifices. They have earned themselves the right to organise their society their own way.






In brief, Barron and Paul are careful not to cite Swain for what he does actually say, though it is highly relevant to their alleged concerns.[^ch06-fn311] Furthermore, this source lends no support to their claim that "virtually everybody" saw the hideous consequences of summary executions, or that the "summary executions" were a matter of government policy.






Perhaps we will do better with Barron and Paul's second source: "Mirror (London), May 9, 1975, AP dispatch from Bangkok, May 8, 1975." The Daily Mirror, May 9, contains no AP dispatch (this journal contains little international news). There is, however, a report by an unidentified Mirror reporter, nestled amidst such items as "My secret agony, by girl's mum," and "Men's Lib at the Altar." This story is based on reports by evacuees from the French embassy and refugees. The reporter does not seem to have been in Cambodia, so he could not have witnessed the scene described by Barron-Paul. Nor did the people he interviewed. But he does have this to say: "The refugees heard reports of wholesale executions of Cambodians. But they never saw any themselves."






So much for the second bit of impeccable documentation.






Perhaps Barron and Paul, in the somewhat misleading citation quoted above, had in mind an AP dispatch from another source. There is, in fact, an AP dispatch from Bangkok (May 8, 1975) filed by Jean-Jacques Cazaux and Claude Juvenal on their arrival after evacuation from Cambodia.[^ch06-fn312] They say nothing about executions in Phnom Penh and report that "not a single corpse was seen along our evacuation route, however."[^ch06-fn313]






Perhaps there are other May 8 Bangkok AP reports relevant to the Barron-Paul claim quoted above,[^ch06-fn314] but the sources they cite plainly are not. Rather, these sources either say nothing about a bloodbath that should have been hard to miss on their account, or express skepticism about bloodbath reports. There is no shred of evidence from this documentation in support of their claim about what "virtually everybody saw" or even in support of their general claim that the government was responsible for "summary executions." We are left with the unverifiable documentation: alleged interviews with Cambodians.






Other sources that Barron-Paul cite in a related context also do not bear out their claims about the signs of a bloodbath that virtually everybody saw. They cite Cazaux (AFP, Hong Kong, May 8, 1975) under the related heading "Transformation of Phnom Penh into a wasteland." We have been unable to locate this report and doubt that it exists, but there is an AFP report filed by Cazaux on May 8 from Bangkok, where he actually was. Here he says that there were rumors that 200 heads were lying in the marketplace and thousands of bodies rotting along Highway 5 leading north, "but latecomers to the embassy said that nothing of the kind [i.e., massacres] had taken place."[^ch06-fn315] Similarly, Sydney Schanberg, whom they cite under "Evacuation of Phnom Penh," notes "unconfirmed reports of executions of senior military and civilian officials" and the prospect that many will die on the march to the countryside; "But none of this will apparently bear any resemblance to the mass executions that had been predicted by Westerners." He cites reports of executions, "but none were eyewitness accounts." He saw bodies on the road from Phnom Penh but says "it was difficult to tell if they were people who had succumbed to the hardships of the march or simply civilians and soldiers killed in the last battles."[^ch06-fn316]






Still another lengthy account (which Barron-Paul do not cite) was given by Patrice de Beer of Le Monde.[^ch06-fn317] De Beer urges caution with refugee or secret service reports ("how badly mistaken they were is only too well known"). He is skeptical about the reports of executions. "One instance cited is that of Oudong, which we went through on April 30, and where we saw nothing of the sort." He is also skeptical of monitored radio messages, "when you recall that the day after Phnom Penh fell a clandestine transmitter on the Thai border announced that a score of journalists had been killed by the Khmer Rouge, when in fact they were all alive." He describes "an unknown world" in the countryside, peaceful despite the devastation, turning to the task of reconstruction.






We hardly find here an "impeccably documented" account of how "virtually everybody" saw the horrendous scenes that Barron-Paul describe. In fact, their documentation reduces to category (1): unverifiable reports of alleged interviews with refugees.[^ch06-fn318] The fact appears to be that virtually nobody whose reports can be checked, including sources that they are clearly aware of since they cite them in related contexts, saw the scenes that they describe.






The fact that their claim was undocumented was noted by Torben Retbøll in letters commenting on the reviews of the Barron-Paul book in the Economist and the Far Eastern Economic Review. Barron and Paul have each responded.[^ch06-fn319] Each produces the obligatory insults ("one of the world's few remaining apologists for the Cambodian communists," etc.), with a touch of hysteria that stands in marked contrast to Retbøll's letters, which quietly point out errors in the book and express skepticism about its claims. We will not review their huffing-and-puffing in an effort to evade the issue, but the upshot is that the claim to which Retbøll referred, which we have just discussed, is not supported by the verifiable documentation that they cite. It is, furthermore, a fairly sensational claim, and one of the few that is subject to possible verification. Furthermore, even the second-hand story of an atrocity that they cite more or less accurately lends no support to their thesis about the "summary executions," as we have seen.






Perhaps this is enough to indicate that Barron and Paul's impeccable documentation and exhaustive and meticulous scholarship, which has so impressed reviewers, will not withstand scrutiny. The historical comments are worthless and their effort to document what might have been observed reduces to the testimony of refugees, that is, unverifiable testimony. They do offer what to the superficial reader may appear to be "documentation," but we discover on analysis that it is irrelevant or contrary to their claims, where it exists. Recall that this is apparently the best that could be achieved with the ample resources of the Reader's Digest. In the case of reporters of demonstrated integrity, reports of what refugees are alleged to have said must surely be taken seriously. In the present case, the very framework of analysis makes it clear that this is not a serious piece of work. At any point where their contribution can be evaluated, it is found seriously wanting if not entirely absurd. People who are willing to place their trust in what Barron and Paul report where no supporting documentation is available (i.e., essentially all the crucial cases) merely reveal that their preconceived bias overwhelms any critical judgment. Nevertheless, their work, both in the Reader's Digest with its mass international circulation and in this widely-reviewed and much-praised book, remains the major source of evidence on which the Western media and the general public have relied, a remarkable bit of evidence in support of the theory of the Free Press that we have been elaborating here.






Ponchaud's book, the second major source for Western audiences on postwar Indochina, is a more serious work and deserves more careful study and critical analysis. Before discussing it, a word about its reception and impact is in order. In fact, it is not quite accurate to say that Ponchaud's book itself has been a major source despite the numerous references to it: rather, the impact of this book has been through the medium of reviews and derivative commentary, primarily, a very influential review by Jean Lacouture, who has compiled an outstanding record as a historian and analyst of contemporary affairs in Vietnam and the Middle East, apart from other important work. The English translation of Lacouture's French review appeared shortly after the Barron-Paul Reader's Digest article, followed within a few months by their book and his corrections.[^ch06-fn320] The already quite extensive press commentary on Cambodia, which had been denouncing the Cambodian horror chamber and Gulag since the war's end, reached a crescendo of outrage and indignation at this time—always coupled with an agonized plea to "break the silence" that could barely be heard above the din of protest. The congressional hearings of May and July followed immediately. This escalation of the already high level of protest was caused, no doubt, by this "one-two punch"; Barron-Paul for the masses in the Reader's Digest, and Lacouture for the intellectual elite in the New York Review of Books. To appreciate how unusual all this is, compare the reaction to benign and constructive bloodbaths, as in the case of Timor.






As we have already mentioned, it is rare—indeed, unprecedented—for a French book on Indochina to receive such rapid and wide notice in the English-speaking world. Lacouture's book on postwar Vietnam was neither translated nor, to our knowledge, ever mentioned in the press, though it was an eyewitness account based on long-demonstrated expertise; in contrast his version of a report by a hitherto unknown French priest concerning a country with which Lacouture had considerably less familiarity became a major literary and political event. Similarly, earlier French studies that give much insight into the developments that have led to the present situation in Cambodia have never been translated and were only mentioned far from the mainstream.[^ch06-fn321] And postwar French publications that give a more positive view of the Khmer Rouge are unnoticed and untranslated.[^ch06-fn322]






It would be difficult to argue that Ponchaud's book has been translated and so widely discussed because of its unique excellence as a work of scholarship or interpretation. Whatever its merits, one would hardly maintain that it is in a class by itself in this regard. Nor is the reason for its uncommon fame that it records horrible atrocities; the same was surely true of the work of Pomonti-Thion and Meyer, for example, who dealt with the U.S. war. Nor can the reason be humanitarian concern, since the latter books were far more relevant than Ponchaud's (all questions of merit aside) on any moral scale, for reasons that are simple and obvious: the information that they conveyed could lead to direct action that would impede or halt ongoing atrocities, while it is difficult to see what Westerners could do to improve the lot of those who were subjected to repression or worse in Cambodia, as specialists have commonly observed.[^ch06-fn323] To "speak out" about Cambodian atrocities in the West, joining the chorus of protest, is easy enough—as easy as it would be for a Russian intellectual to condemn the atrocious acts of U.S. imperialism.[^ch06-fn324] It cannot be that some moral imperative affords Ponchaud's book its unique fame.






In fact, it is clear enough why this study has been singled out for special attention: its message, accurate or not, happens to conform perfectly to the needs of current Western ideology.[^ch06-fn325]






These comments are no criticism of the book, of course. Rather, they relate to its remarkable reception, and thus are relevant to our primary concern: the workings of the Western propaganda system.






Ponchaud's book appeared in France in January 1977. A review by Jean Lacouture in Nouvel Observateur was immediately translated and appeared in the March 31 issue of the New York Review of Books, probably a record for speed in reviewing a French book. Lacouture's review had a considerable impact. Ponchaud himself writes that it ''provoked considerable reaction in all circles concerned about Asia and the future of socialism."[^ch06-fn326] Our own interpretation of the impact would be a bit different. Most of those who reacted to Lacouture's review in the media by lauding the contribution of the book that they had never seen had shown little concern for the future of socialism; or for Asia, except in the sense that a fox is concerned with a brood of chickens.






Others have also commented on the influence of Lacouture's review, which has indeed been unprecedented. William Shawcross writes that it had "enormous impact particularly because it was written by a former supporter of the Khmer Rouge (he issued a mea culpa) for a paper which had consistently opposed the war. It was taken up by dozens of papers ..."[^ch06-fn327] In its review, the London Economist wrote that Ponchaud's book "gained considerable notoriety because of an extraordinary review in the New York Times [sic] Review of Books written by Jean Lacouture, a French journalist."[^ch06-fn328] Lacouture's corrections (a "bizarre episode")[^ch06-fn329] "added—a bit illogically—to the controversy that was already well advanced over whether the book itself was adequately researched and the refugees' evidence viewed with sufficient scepticism."






These comments bring out several interesting themes which, as we have seen, crop up constantly in discussion about postwar Indochina. Consider the Economist's reference to the "controversy that was already well advanced" over Ponchaud's book. There was no controversy. It was quite impossible for there to have been a controversy at the time when Lacouture's review appeared. The book itself had just appeared; for all we know there was not a single person in the English-speaking countries who had read the book, let alone engaged in controversy over it, at that time (and precious few afterwards, when the unread book was having its "enormous impact" on the press); nor was there any controversy "well advanced" in France a few weeks after publication. Furthermore, there has been very little controversy over the book since. Reviews have been consistently favorable, our own review in the Nation included, as Ponchaud remarks in the author's note to the American translation,[^ch06-fn330] though we raised several questions about it. But it is, as we have seen, a staple of media coverage of postwar Cambodia to pretend that a major intellectual battle is in progress, comparable perhaps to the debate over Stalinist crimes years ago. Such pretense provides a useful backdrop to the incessant plea that the story is "untold," everyone remains silent, etc., a performance that would have an air of low comedy were it not for the seriousness of the subject.






Shawcross's observation that part of the impact of the review was due to Lacouture's former support for the Khmer Rouge and the fact that the New York Review had consistently opposed the war is very much to the point. But the matter deserves a closer look. In fact, much has also been made of Ponchaud's early sympathy for the Khmer Rouge as evidence that his criticism has unusual force.[^ch06-fn331] Lacouture does describe himself as someone "who supported the Khmer Rouge cause,"[^ch06-fn332] and "advocated the cause of the Khmer Rouge in their struggle against the corrupt Lon Nol regime."[^ch06-fn333] His previous writings indicate, however, that he was a supporter of Sihanouk, who was a bitter enemy of the Khmer Rouge until they joined forces against Lon Nol in 1970 and whose subsequent relations with the Khmer Rouge are not at all clear.[^ch06-fn334] In fact, it is difficult to see how a Westerner could have supported the cause of the Khmer Rouge, since virtually nothing was known about it. One should beware of the "God that failed" technique.[^ch06-fn335] It is a common error, as we have pointed out several times, to interpret opposition to U.S. intervention and aggression as support for the programs of its victims, a useful device for state propagandists but one that often has no basis in fact. As for the New York Review, it is true enough that it consistently opposed the war and was at one time open to writers connected with the peace movement and the U.S. left (along with a wide range of others), but it rejoined the liberal consensus in these respects years ago. It may be that the impact of Lacouture's review derived in part from the fact that it appeared in the issue immediately following the André Gelinas article on Vietnam that we discussed in chapter 4. This too was influential, and its impact was enhanced, as we have seen, by the pretense that the journal in which it appeared had been an "organ of celebration" for the Communists, a typical lie of the propaganda institutions.[^ch06-fn336]






Finally, as concerns Ponchaud, it is quite true that he writes that he listened to Khmer Rouge proposals "with a sympathetic ear," since "I come of peasant stock myself."[^ch06-fn337] As far as we know, however, during the years Ponchaud lived in Cambodia he never publicly expressed this sympathy and also apparently felt that no purpose would be served by any public comment or protest over the war—specifically, the foreign attack—while it was in progress; we are aware of nothing that he wrote on the war apart from several articles and his book all after the war's end. Furthermore, he describes nothing that he did that might have been to the benefit of the peasants of Cambodia.






It apparently has not been noticed by the many commentators who have cited Ponchaud's alleged sympathy with the Khmer peasants and the revolutionary forces that if authentic, it is a remarkable self-condemnation. What are we to think of a person who is quite capable of reaching an international audience, at least with atrocity stories, and who could see with his own eyes what was happening to the Khmer peasants subjected to daily massacre as the war ground on, but kept totally silent at a time when a voice of protest might have helped to mitigate their torture? It would be more charitable to assume that Ponchaud is simply not telling the truth when he speaks of his sympathy for the Khmer peasants and for the revolution, having added these touches for the benefit of a gullible Western audience or for the benefit of apologists who can then write that the atrocity stories have "impressed even those such as François Ponchaud,...who was sympathetic to the Communists when they first took over."[^ch06-fn338]






In short, neither Lacouture, nor Ponchaud, nor the New York Review had ever, to our knowledge, identified with the Khmer Rouge or their "cause." While it is true that the impact of Lacouture's review of Ponchaud's book in the New York Review derives in part from such loose associations as those just mentioned, that is more a commentary on the media than on the facts.






Lacouture's review has indeed been extremely influential. The corrections, in significant contrast, have been little noted.[^ch06-fn339] Two samples from the national press illustrate the media response.






Basing themselves on a review of a book that they had never seen, by an unknown author, the editors of the Christian Science Monitor published an editorial stating that "the loss of life" had been reported to be "as high as 2 million people out of 7.8 million total." They quote Lacouture's rhetorical question: "What Oriental despots or medieval inquisitors ever boasted of having eliminated, in a single year, one quarter of their own population?"[^ch06-fn340] Surely enough time had passed to enable the Monitor editors to do what several private individuals had done upon reading Lacouture's review: namely to check his source for this remark, and find that it did not exist. The Monitor also cites the faked photographs discussed above (the fakery had been publicly exposed a year earlier), noting merely that they "have not been positively verified." They quote Lacouture's conclusion that "Cambodia's leaders have been 'systematically massacring, isolating and starving city and village populations whose crime was to have been born when they were,'" never troubling—here or elsewhere—to inquire into the evidence for this allegation, or to ask what curious aberration might impel Cambodia's leaders to systematically starve and massacre the population of the country, or how a small group of leaders might be able to achieve this strange purpose. They conclude that "for the outside world to countenance such barbarism and remain officially silent about it, in a sense diminishes respect for humanity and its rights everywhere." To fully appreciate their reaction one would have to review the shabby editorial record of this journal[^ch06-fn341] in countenancing the barbarism of the United States over many years.[^ch06-fn342]






Lacouture, like Ponchaud, takes note of the brutality of the U.S. war, surely a major factor in what followed. These references disappear from the Monitor editorial, which like Barron-Paul pretends that the current suffering in Cambodia takes place in a historical vacuum, a mere result of Communist savagery. We have already quoted their earlier editorial based on Barron-Paul, which avoids any reference to U.S. responsibility, though there is much moralizing about those who are allegedly indifferent to Khmer Rouge terrorism against the "engaging people" of Cambodia.[^ch06-fn343]






To mention a second example, the liberal columnist of the New York Times, Anthony Lewis, devoted a column to Lacouture's review.[^ch06-fn344] Lewis was an outspoken and effective critic of the U.S. war from 1969 and has since explained that "by 1969 it was clear to most of the world—and most Americans—that the intervention had been a disastrous mistake"[^ch06-fn345]—not a crime. He commented on the "painful honesty" of Lacouture's article which "lends ghastly conviction to its terrible conclusions." He then quotes Lacouture's conclusions: the new rulers "have invented something original—auto-genocide," a new and more horrible form of genocide: "After Auschwitz and the Gulag, we might have thought this century had produced the ultimate horror, but we are now seeing the suicide of a people in the name of revolution; worse: in the name of socialism." Apparently a greater horror than Auschwitz or the Gulag, not to speak of the Indonesian massacre of 1965-1966 or the U.S. massacres in Indochina (but then, as Lewis has explained, these were only a "disastrous mistake"). Lewis also quotes approvingly Lacouture's claim that the "group of modern intellectuals, formed by Western thought, primarily Marxist thought" are systematically massacring and starving the population, and his further claim that these monsters "boast" of having "eliminated" some 2 million people, along with other citations that happen to be inaccurate. As distinct from the Monitor, Lewis cites Lacouture's reference to the U.S. role, and like his colleagues warns that "to remain silent in the face of barbarism as enormous as Cambodia's would be to compromise our own humanity"—as if there had been silence, as if it is "our own humanity" that is at stake, as if we do not compromise our own humanity by describing "American decisions on Indochina" as "blundering efforts to do good" (see note 345) after having remained silent about them apart from timid queries during the period of the worst barbarism. "In today's world," he concludes, "we ignore mass murder anywhere at our own peril."






The allegations that Lewis quotes are severe indeed. As a legal scholar, he might have troubled to inquire into the source of the allegations that he is reporting from a book he had never seen by an author of whom he knows nothing, before broadcasting them in such a manner to a mass audience. Had he done so, he would have quickly discovered that his specific citations had no basis in the text of the book, as we shall see. And for all his expressed concern about compromising our own humanity, it is only "our own peril" that concerns this moralist (who concedes "that there is not much hope of affecting the Cambodian government"), not the consequences for Third World peoples who are potential victims of the hysteria that he is helping to inflame with his unexamined charges based on misquotations and errors.






The Monitor was unwilling to print corrections of the false statements in its editorial or the conclusions based on them, despite evidence provided to them that established the falsity beyond question. They did, however, publish (prominently) a letter correcting some of these errors[^ch06-fn346]; retraction would have been the honorable step. After Lacouture's corrections had appeared, Lewis (who had also had in hand for several weeks the documentary evidence showing that his quotes were baseless) noted them at the end of a column.[^ch06-fn347] His corrections were only partial, and he did not make clear that full corrections eliminate entirely the evidentiary basis for the conclusions he proclaimed. Nor did he indicate whether this fact bears on the "ghastly conviction" lent to Lacouture's "terrible conclusions."[^ch06-fn348]






Since the media have relied heavily on the contents of Lacouture's review, regardless of the corrections,[^ch06-fn349] it is important to see exactly what kind of information they are offering to the reading public. We are not concerned here with Lacouture's interpretation of what he read, but rather with the evidence that was available to the many journalists who made use of this evidence without troubling to investigate its character and accuracy. Such evidence, plainly, consists of Lacouture's more or less explicit references to the book. These references turn out to be false or highly misleading in every instance. Hence the journalists were writing on the basis of no serious evidence whatsoever. Furthermore, subsequent inquiry has revealed that some of the material in the book that was the basis for Lacouture's distorted account was quite dubious at best—again, a pattern that we have noticed earlier; evidence about Cambodia has a way of crumbling when one begins to look at it closely, a fact that should raise some questions about the examples that have not been investigated because of their lesser prominence in the international campaign. What reached the public was a series of reports by journalists of Lacouture's misreading of statements by Ponchaud that are themselves questionable in some instances (even forgetting the additional link in the chain of transmission, namely, the refugee reports). It is therefore of some interest to review these cases one by one.






The review contains the following references that can be related to something that appears in the book itself:






(1) "What Oriental despot or medieval inquisitors ever boasted of having eliminated, in a single year, one quarter of their own population?"






(2) Ponchaud "quotes from texts distributed in Phnom Penh itself inciting local officials to 'cut down,' to 'gash,' to 'suppress' the 'corrupt' elites and 'carriers of germs'—and not only the guilty but 'their offspring until the last one.' The strategy of Herod." [Lacouture's emphasis]






(3) Ponchaud "cites telling articles from the government newspaper, the Prachachat,...which denounced the 're-education' methods of the Vietnamese as 'too slow.' 'The Khmer method has no need of numerous personnel. We've overturned the basket, and with it all the fruit it contained. From now on we will choose only the fruit that suit us perfectly. The Vietnamese have removed only the rotten fruit, and this causes them to lose time.' [Lacouture's emphasis.]






"Perhaps Beria would not have dared to say this openly; Himmler might have done so. It is in such company that one must place this 'revolution' as it imposes a return to the land, the land of the pre-Angkor period, by methods worthy of Nazi Gauleiters."






(4) "When men who talk of Marxism are able to say, as one quoted by Ponchaud does, that only 1.5 or 2 million young Cambodians, out of 6 million, will be enough to rebuild a pure society, one can no longer speak of barbarism [but only] madness."






These quotes exhaust the alleged evidence available to the journalists on whom this review had such a powerful impact, and provide the basis for their further commentary.






Let us now review the status of this evidence. We have already discussed case (4), noting that the source, if any, is so unreliable that Ponchaud deleted the reference from the American edition. Case (1) is simply false, as Lacouture points out in his corrections.[^ch06-fn350] There was no Khmer Rouge boast reported, and no figure of one quarter of the population "eliminated" or even an allegation of that number of postwar deaths.






Turning to case (2), as Lacouture acknowledges in his corrections, the source is not texts distributed in Phnom Penh but something much more vague; this is true not only of the single case he discussed in the "Corrections," namely, the injunction to suppress "their offspring until the last one," but also of the others cited.[^ch06-fn351] The one case that Lacouture discusses in his corrections is presented, as he says, as a "leitmotif de justification" in the French text. The other examples we are unable to locate in Ponchaud's French text, though similar quotes are offered as "slogans used, both on the radio and at meetings." What their status may be is not made clear. The radio reports are not identified (others are elsewhere in the book), so they are perhaps refugee memories. Plainly this must be true of the slogans reported. Thus what we have is memories transmitted at second-hand by Ponchaud, modified by Lacouture, and presented as texts distributed in Phnom Penh.






What of the one example that Lacouture corrects, which expresses "the strategy of Herod"? Does this judgment still hold if it is a "leitmotif" without explicit source rather than an official text? Without pursuing that question, we note that the American translation of Ponchaud's book softens the reference still further. There is no quote given at all; rather, the text reads: "the theme that the family line must be annihilated down to the last survivor is recurrent in such reports." The relevant "reports" are identified only as "several accounts"—presumably, refugee memories. Ponchaud's paraphrase of a theme that several refugees have allegedly reported does not seem to us to provide very powerful support for denunciation of a regime as employing "the strategy of Herod."[^ch06-fn352]






We are left with one single bit of evidence, namely case (3). This case turns out to be rather interesting. In his "Corrections," Lacouture acknowledges that Prachachat is not a Cambodian "government newspaper" but rather a Thai newspaper—a considerable difference, which suffices to undermine the comment that he appends to this quote. In the corrections he writes that this Thai paper, in its issue of June 10, 1976, "carried an interview with a Khmer Rouge official who said, as Ponchaud writes, that he found the revolutionary method of the Vietnamese 'very slow,' requiring 'a lot of time to separate the good people from the counter-revolutionaries.'" It was the Thai reporter, he adds, who drew the conclusion he quoted that the Khmers had "overturned the basket ..."[^ch06-fn353]






This is a fair rendition of what Ponchaud reports.[^ch06-fn354] Ponchaud writes: "In an interview in the Thai newspaper Prachachat of 10 June 1976 a Khmer Rouge official said that the Vietnamese revolutionary method was 'very slow,' and that 'it took a great deal of time to sort out the good from the counter-revolutionaries.'"[^ch06-fn355] Ponchaud then cites the conclusion of the reporter of Prachachat, and adds this final comment as a separate paragraph, closing the chapter: "This is the 'Great Leap Forward' of the Khmer revolution.''






The American version is a bit different. The final ironic comment is deleted entirely. Furthermore, he says here that the interview with the Khmer Rouge official was "cited" in Prachachat; that is, there is still another link in the chain of transmission. Note that this interview and the Thai reporter's comment are considered rather significant; the chapter heading is: "The Overturned Basket."






When we first read Ponchaud's original, we assumed that the Thai journal Prachachat must be a right wing journal giving a criticism of the Khmer Rouge. That is what Ponchaud's account suggests, in particular his final ironic comment, now deleted in the American edition. We wrote in the Nation (25 June 1977) that the chain of transmission was too long to be taken very seriously and we raised the following question: "How seriously would we regard a critical account of the United States in a book by a hostile European leftist based on a report in Pravda of a statement allegedly made by an unnamed American official?" (Correspondingly, how seriously should we regard a critical account of Cambodia in a book by Ponchaud based on a report in Prachachat of a statement allegedly made by an unnamed Khmer Rouge official?) The answer is: not very seriously. Whatever one thinks of this, it is evident that the basis for the extreme criticisms that Lacouture appends to this "quote" disappears when it is properly attributed: to a Thai reporter, not a Cambodian government newspaper.






Several people (Heder, Ponchaud, Vickery) have pointed out to us that we were mistaken in assuming that Prachachat was a right wing newspaper critical of the Khmer Rouge. The fact is that it was a left wing newspaper, and the actual text[^ch06-fn356] is not a criticism of the Khmer Rouge, but a defense of the Khmer Rouge against foreign criticism, something that could hardly be guessed from Ponchaud's account and is certainly worth knowing, in this context. Furthermore, it turns out that there is indeed another link in the chain of transmission; Ponchaud's revision of his French text in the American (but not British) translation is correct. Prachachat did not interview a Khmer Rouge official. Rather, it cites a report by a person described as "a neutral individual" in Paris who says that "a Khmer official of the new government, residing in Paris, said to me ..." Here, then, is an improved version of our original analogy: How seriously would we regard a critical account of the United States in a book by a hostile European leftist based on a report in Encounter[^ch06-fn357] of comments by a "neutral person" who reports statements of an unnamed American official? Again, not very seriously.






Note that the unnamed Khmer Rouge official in Paris is quite possibly a member of the pro-revolutionary Cambodian community in Paris, whose information is itself second or third-hand (perhaps through Peking), as Heder points out.[^ch06-fn358] Furthermore, given the context it is not so clear what interpretation to give to the comment about the Vietnamese methods being "very slow." Lacouture's reference as well as Ponchaud's text suggest that what is intended is that the methods are too slow in eliminating people (at least, that is how we read them). The full context of the original article in Prachachat, however, suggests that what is in fact meant is that the Vietnamese method is too slow in returning former collaborators (including professionals and even former military men) to normal lives to help build the new society; again, a vast difference. The gist of the article seems to be a call for rapid proletarianization of the urban bourgeoisie—who, as every rational observer agrees, had to be moved to productive work in a country that had no economy,[^ch06-fn359] and had no way of feeding millions of people who had been driven into the cities by U.S. "forced-draft urbanization." No one could guess from Ponchaud's citation that this may well be the intended sense of these remarks.






Furthermore, the context and the proper wording suggest a rather different sense for the paragraph quoted from the Thai journal's conclusion; recall that the article was intended as a defense of the Khmer Rouge against criticism.[^ch06-fn360] As Lacouture gives the quote, following Ponchaud, the Thai journalist says that "the Khmer method has no need of numerous personnel." The implication is rather similar to that conveyed by the widely quoted remark about needing only 1-2 million people to build the new society (Lacouture's case (4), already discussed): namely, not many people are needed; the others can be eliminated. Evidently, Lacouture understood it this way (we did as well)—hence his comment about Beria, Himmler and Nazi Gauleiters. But the context omitted from Ponchaud's text makes it clear that this interpretation is entirely false. The immediately preceding paragraph and the one in question read as follows:






If we may make a comparison, we see that the Vietnamese method requires numerous personnel to supervise the population; it may even turn out that it will not succeed everywhere, and the authorities will thus be charged with a very heavy burden.[^ch06-fn361]






In contrast, the Khmer method does not need numerous personnel; there are no burdens; because they have removed all the burdens out of the city ...






Then comes the comparison of overturning the basket.






Note two crucial points. Placed in context, it is obvious that the reference to the Khmer method not needing numerous personnel means that not many people are needed as supervisors, not that most of the population can be eliminated. Whatever one may think of this, it hardly justifies the remarks about Beria, Himmler and the Nazi Gauleiters. Ponchaud's citation, eliminating the relevant context, radically changes and severely harshens the sense. Secondly, note that the phrase "they have removed all the burdens out of the city," which plainly means that the burdens of the authorities have been removed from the city, is translated by Ponchaud as follows: "there are no heavy charges to bear because everyone is simply thrown out of town."[^ch06-fn362]—obviously, the connotations are quite different.






When the proper context is introduced and Ponchaud's mistranslation is corrected, we find that the journalists of Prachachat are indeed giving what they take to be a defense of the Khmer revolution. We will not go into the question of whether this defense is adequate. Rather, our point is that what they are saying is radically different from the impression conveyed by Ponchaud—which explains why Lacouture, and we too, were so seriously misled as to the character of the Prachachat article. Thus this final item in the list of Lacouture's references (number (3)), goes the way of the others. It provides no basis whatsoever for his charges, but rather shows that Ponchaud has once again flagrantly misrepresented a quotation, the very one from which he took the chapter heading.






Two conclusions emerge from this discussion. First, journalists who have been relying on Lacouture's review (with or without corrections) have built their case on sand. Furthermore, inquiry reveals that when we proceed beyond his published correction to a full list of corrections, and beyond that to correction of Ponchaud's original text to which he referred, the sand turns to jelly.






The original French has been considerably modified in the American edition. Specifically, in the list just given, item (4) is dropped entirely; the central example of (2) is changed from a quote to a paraphrase; the final ironic comment based on the translation of Prachachat is deleted and it is correctly stated that the article did not contain an interview with a Khmer Rouge official but rather that such an interview was cited. Item (1) was simply an error based on a misreading of a false statement by Ponchaud. Item (2) was also a misreading of Ponchaud. As for item (3), not only was Lacouture's reference to Ponchaud seriously in error, but Ponchaud's original translation from Prachachat is in part extremely misleading and in part flat wrong.






All in all, not a very impressive performance, either at the source or in the review.[^ch06-fn363] But it is this material that has had such a major impact on Western journalists, perhaps second only to the Barron-Paul book that we have already discussed.






Returning now to Lacouture's point that it is a matter of secondary importance to decide "which person uttered an inhuman phrase, and whether the regime has murdered thousands or hundreds of thousands of wretched people," we believe that this review of the facts strengthens our earlier argument that it does matter indeed. It appears that the "inhuman phrases" in question may not have been uttered at all, or when uttered, were hardly so inhuman as Lacouture and Ponchaud suggest. It remains an open question whether the "regime has murdered" those who died from disease, starvation or overwork—or whether we have murdered them, by our past acts. It is also unclear on Ponchaud's evidence whether "the regime" has murdered the victims of "summary executions" (by government design? or peasant revenge? or soldiers out of control?).






We have now reviewed the two major sources of information for U.S. and indeed Western readers: Barron-Paul and Lacouture's rendition of Ponchaud. We turn next to Ponchaud's book itself. Again, we face the usual problem of logic: the trust we place in unverifiable material, which includes the essential and the most serious charges, depends on the trustworthiness of material that can be verified, here or elsewhere. In this case, we are restricted to the book itself, as the few articles we know of add little. As we have seen, Ponchaud plays fast and loose with numbers and is highly unreliable with quotations. This discovery naturally raises questions about sources that cannot be checked. As in the case of Barron-Paul, we can turn to his account of the history and background to assess the credibility of his reporting and conclusions. There is a vast difference between the two books in this regard. Ponchaud at least makes an effort to deal with these crucial matters. He offers virtually no documentation, which again reduces the possibility of assessment, but much that he recounts seems plausible both on grounds of inner consistency and what is known from other sources. We have mentioned a few cases where we find his historical account unsatisfying; namely, in reference to the colonial impact and the U.S. role, though these are at least mentioned. On his account of Khmer culture and the ideology of the post-revolutionary society, briefly mentioned above, we are not qualified to comment.






In his historical comments, Ponchaud tends to keep closely to the version of events offered by the U.S. propaganda system. Consider, for example, his discussion of the U.S. and Vietnamese involvement in Cambodia. Since he gives no sources, we do not know on what information he relies; plainly, not direct experience in these cases. The major studies[^ch06-fn364] give a general picture of the following sort: Cambodia had been subjected to attempts at subversion and direct aggression by its U.S.-backed neighbors, Thailand and South Vietnam, from the 1950s. Diem's troops had attacked border regions in 1957. A CIA-backed plot to dismember Cambodia in 1958-1960 was foiled. There were provocations from the Thai side of the border, but the Vietnamese frontier posed a much more serious threat. "From 1957, but particularly from 1964, American-South Vietnamese forces attacked posts and villages, bombed rice fields, machine-gunned trucks, napalmed or defoliated the Cambodian side of the frontier," causing hundreds of casualties each year (Pomonti-Thion). Meyer reports that "at the end of 1963, the 'Khmers Serei,' equipped and trained by the CIA, made more frequent incursions into Cambodian territory from bases in South Vietnam and Thailand," and a few years later "the American-South Vietnamese attacks, ever more murderous, multiplied against the frontier villages of Cambodia." After the massive and destructive U.S. military operations in nearby areas of South Vietnam, particularly in January-February 1967, Vietnamese peasants and guerrillas took refuge in narrow border areas, leading to cynical charges from Washington about Communist encroachment into neutral Cambodia. According to Meyer, by March, 1970, when the coup that overthrew Sihanouk took place, they were scattered along border areas to a maximum depth of perhaps 25 kilometers in the extreme northeast provinces which were to a considerable extent under the control of indigenous guerrillas. Other sources concur. Relations between the Cambodians and the Vietnamese in the "sanctuaries" were generally friendly at that time, and there were few military conflicts. The first evidence of Vietnamese encampments on the Cambodian side of the border was discovered in late 1967, a few kilometers beyond an unmarked border. While hypocrites in Washington and the press fumed in public about "North Vietnamese aggression," the internal view was different. From the Pentagon Papers we learn that as late as May 1967—i.e., well after the major U.S. military operations cited above—high officials believed that Cambodia was "becoming more and more important as a supply base—now of food and medicines, perhaps ammunition later" (John McNaughton). A year earlier a U.S. study team discovered the results of a U.S. helicopter attack on a Cambodian village (first denied, later conceded when eyewitnesses including a CBS television team reported the facts), one of several such cases discovered accidentally. In March 1969 the massive "secret bombing" began.






It is intriguing to consider the reactions in the United States to the occasional revelations that Cambodia had been attacked by U.S. forces. Roger Hilsman, who was director of the Bureau of Intelligence and Research in the State Department and later Assistant Secretary of State for Far Eastern Affairs in the Kennedy administration, describes an attack by U.S. bombers on a Cambodian village on January 21, 1962, with an unknown number of civilian casualties. He describes this as a "tragic error in map-reading": the real intent was "to bomb and strafe the cluster of huts near the Cambodian border" where it had been reported that there were Viet Cong guerrillas. It would not have been a "tragic error" if a Vietnamese village had been bombed by U.S. planes in January, 1962, with an unknown number of civilian casualties. Hilsman's sole criticism concerning this bombing attack against a defenseless village (apart from the tragic error in map reading, which led to the wrong peasants being killed) is that though "the plan was well and efficiently executed" it was not well-designed for guerrilla warfare: "The greatest problem is that bombing huts and villages will kill civilians and push the population still further toward active support for the Viet Cong."[^ch06-fn365] Hilsman is widely regarded as a "dove."






On 25 March 1964, the New York Times published a report by Max Frankel, now an editor, with the interesting title: "Stomping on U.S. Toes: Cambodia Typical of Many Small Nations Putting Strain on a Policy of Patience." What aroused Frankel's ire was that Cambodia had "borrowed a leaf from Fidel Castro's book and demanded tractors and bulldozers as compensation for the killing of Cambodians by South Vietnamese in a frontier attack." He is referring to the Cambodian response to a Vietnamese ground and air attack on a Cambodian village in which they were accompanied by U.S. advisers. A U.S. Army pilot "was dragged from the wreckage" of an L-19 observer plane "shot down in the action," and "diplomats who rushed to the scene confirmed Cambodian reports that at least one troop-carrying helicopter had landed at Chantrea with three Americans on board." The Cambodian village of Chantrea was bombed and attacked by 12 armored cars, according to Cambodian sources; seventeen persons were reported killed and 13 injured.[^ch06-fn366] It was not the attack, but Cambodia's response that enraged Frankel, who explains as follows:






It is open season again for the weaker nations to stomp on the toes of big ones...Leading the pack in big-power baiting these days is one of the smallest of nations, the Southeast Asian kingdom of Cambodia...What Cambodia is up to seems to turn on what Cambodia's young leader, Prince Norodom Sihanouk, is up to. Washington has always regarded the 41-year-old Premier-Prince as a clever, headstrong, erratic leader who wishes to serve his people, defend their independence and develop their resources. It has also found him lacking some of the talent and temperament for the job...For the most part, the Administration's instinct has been to try to save a wayward young nation's independence in spite of itself and, at times, despite its own leaders. Officials remark privately that Indonesia is more important than Sukarno, Ghana more important than Nkrumah, Cambodia more important than Sihanouk.






But now Washington is "not only alarmed and saddened, but confused." Of course, "Cambodia's current effort to force the United States into a major conference that would embarrass its Thai and Vietnamese friends will be resisted"; the reference is to a conference that would settle border questions and guarantee Cambodia's neutrality and integrity in a period when the United States was desperately seeking to undermine international efforts to neutralize South Vietnam, Laos, and Cambodia so as to avert the major war towards which the United States was clearly driving.[^ch06-fn367] But what was most irritating was the Cambodian effort to "stomp on U.S. toes" by asking for reparations after a village was attacked by forces trained, supplied and advised by the United States, and accompanied by U.S. military advisers and aircraft. It was this unmitigated gall that was trying the patience of the U.S. government while calling forth a reaction in the New York Times that is remarkable as much for the paternalism and racism of its style, so typical of the annals of colonialism, as for the response to the actual events discussed.






In his rather sketchy historical review, Ponchaud passes over all of these events of the 1950's and 1960's in silence. His only comment is that the "Vietnamese revolutionaries were becoming a real menace to Cambodia,"[^ch06-fn368] hardly an adequate summary. He says that "in his desire to stop the infiltration along Cambodia's borders, [Sihanouk] disclosed the location of Vietcong bases, which were then bombed by the American air force. He called it a scandal and a crime over Radio Phnom Penh, but nobody was deceived"[^ch06-fn369]; the reference is to the 1969 bombings. Actually, Ponchaud is deceived. Keeping strictly to the position of U.S. propaganda, he fails to indicate that Sihanouk vigorously and publicly denounced the bombing of Khmer peasants.[^ch06-fn370] Turning to the March 1970 coup, Ponchaud has little to say about the background. His few comments are, furthermore, inconsistent: the coup was "presumably backed by the Americans" and "the United States was not sure what attitude to adopt in the Cambodian crisis. Sihanouk's downfall was bad news ..."[^ch06-fn371] The first of these two contradictory claims seems to us the more likely correct, given what little evidence is available, but Ponchaud does not pursue the issue—a rather important one. He makes no mention of US-ARVN military intervention from two days after the coup of March 18. As for the "incursion" of April 30, he says only that the South Vietnamese took advantage of it to avenge the murder of Vietnamese by the Lon Nol government: "their savagery drove a number of Cambodian peasants over to the Khmer Rouge."[^ch06-fn372] Not a word about the savagery of the U.S. attack, which was amply reported at the time. Ponchaud asserts that the North Vietnamese "[swept] up young Khmers to be trained in revolutionary warfare,"[^ch06-fn373] ignoring entirely the eyewitness reports by U.S. correspondents in captivity that the U.S. bombing was recruiting Khmers, both young and old, to the Khmer Rouge. Pomonti-Thion remark appropriately that "the mechanism by which American bombs create resistance is too well known for us to describe here."






With regard to the war in Vietnam, Ponchaud also keeps closely to the U.S. government propaganda line in his scattered remarks. Discussing the "North Vietnamese" withdrawal from Cambodia by 1971, he says that they "returned to their conquest of South Vietnam"[^ch06-fn374]—the sole reference to that struggle, astonishing in its misrepresentation of the background that is so well-documented and familiar that we need not elaborate here. Referring to Sihanouk's attitude towards the struggle in Vietnam, he says that at the time of the Tet Offensive, "when he saw how fiercely the population in the south defended itself he wavered, and began to think the north might be defeated."[^ch06-fn375] Again, an amazing distortion of well-known facts that are easily documented from U.S. government sources. There is overwhelming evidence from these sources and elsewhere that the Tet Offensive was primarily a struggle between the U.S. Army and South Vietnamese guerrillas—indeed, the fact is not seriously disputed. In the Mekong Delta, for example, where some of the fiercest battles were waged, there were no North Vietnamese regular forces, and in fact the total number of North Vietnamese who had been drawn into the war by the U.S. bombardment of North Vietnam (exactly as planners anticipated) was at approximately the level of the South Korean and Thai mercenaries at that point, vastly outnumbered (and even more vastly outgunned) by the U.S. Expeditionary Force that had for years been attempting to conquer South Vietnam and to destroy the society in which the indigenous revolt was rooted. Furthermore, during the Tet Offensive, the U.S. military continually lamented their difficulties in encouraging ARVN to reenter the countryside, particularly in the Delta. To describe the Tet Offensive in Ponchaud's terms is a gross falsification and a remarkable capitulation to the U.S. propaganda machine.






Such examples as these do not increase one's faith in the veracity of material that is not subject to independent confirmation, to say the least, and should alert any serious reviewer. We have seen no mention of any of this in a single review or comment.






Turning to material that is closer to the focus of Ponchaud's book, as in the case of Barron-Paul, the only section subject to independent verification is the one dealing with the evacuation of Phnom Penh. Here too serious questions arise. We have already noted how severely Ponchaud's account was distorted by Donald Wise in a review.[^ch06-fn376] Turning to his own account, there are many dubious elements. Thus Ponchaud reports the explanation given by the revolutionary government: that the evacuation was motivated in part by impending famine. He rejects this argument on the grounds that rice stocks in Phnom Penh would have sufficed for two months for a large part of the population with careful rationing.[^ch06-fn377] The book cites none of the evidence from Lon Nol and U.S. government sources that gives radically smaller estimates, namely 6-8 days' supply,[^ch06-fn378] one of the many cases where the lack of documentation in the book conceals a rather casual attitude towards crucial facts. We questioned Ponchaud's two-month estimate in our review already cited. In a letter in response, Ponchaud informed us that his estimate included food illegally stored and "may be somewhat excessive"; he also suggests that the 8-day estimate of the Lon Nol government may have been exaggerated in an effort to obtain more aid, which is possible, though their demand at the time was primarily for arms rather than "humanitarian assistance," and in any event that still leaves the estimate of USAID officials that there was only a six-day supply of rice. Even if Ponchaud's possibly "excessive" two-month estimate were correct, it remains unclear how famine could have been averted after two months had the cities not been evacuated, though the methods were extremely brutal, judging by most of the eyewitness accounts. As we have already noted, sources in or close to the U.S. government concur.[^ch06-fn379]






On the question of whether the atrocities in Cambodia, which Ponchaud graphically records from the testimony of refugees, were the result of a centralized policy of massacre or were rather, as many close observers suspect, in significant measure the result of localized peasant revenge and the acts of undisciplined troops, Ponchaud comes down squarely on the side of systematic and centralized policy:






The liquidation of all town and former authorities was not improvised, nor was it a reprisal or expression of wanton cruelty on the part of local cadres. The scenario for every town and village in the country was the same and followed exact instructions issued by the highest authorities.[^ch06-fn380]






And elsewhere, after reporting a refugee account of the massacre of officers and sick or invalid soldiers, he writes: "So many accounts contain similar statements that it can safely be affirmed that the revolutionaries had simply decided to kill off the bulk of the former civilian and military establishment in the hours following the capture of Phnom Penh."[^ch06-fn381]






One may, perhaps, be skeptical that Ponchaud has reviewed the scenario "for every town and village in the country" as is claimed in the cited remark. As for the "exact instructions issued by the highest authorities," this is presumably his reconstruction from the alleged similarity of refugee accounts—he offers no direct evidence—and is as trustworthy as these accounts, his report of them, his interpretations of what he reports, and his judgment about the similarity of accounts of which, naturally, he can offer only a sample. The cautious reader, bearing in mind the serious inaccuracies of his quotes and citations where they can be checked and his careless treatment of historical fact, may want to reserve judgment on the question at issue. Ponchaud's own conclusions, it is by now clear, cannot be taken very seriously because he is simply too careless and untrustworthy. It is hardly in doubt that work of this calibre would be dismissed out of hand, if it were critical of the United States.






It is also worth recalling in this connection that according to published refugee testimony that Ponchaud does not cite, executions had been ordered halted by mid-1975,[^ch06-fn382] though we do not know how reliable this testimony is, or, if reliable, whether such orders were observed or changed. As for the similarity of refugee accounts, we have already noted reasons for skepticism. Other Cambodia watchers and scholars who have visited refugee camps and interviewed refugees have expressed different judgments, and we have cited a few examples that have been generally ignored by the media that also raise questions. Ponchaud himself naturally gives only a sample of the accounts he has assembled.[^ch06-fn383] Even the examples he cites do not substantiate his firm conviction that central direction rather than localized cruelty or revenge has been clearly established. To mention a few examples, he cites a Khmer pharmacist who escaped in June 1975—that is, well after "the revolutionaries had simply decided to kill off the bulk of the former civilian and military establishment in the hours following the capture of Phnom Penh"—who reports: "The attitudes of the Khmer Rouge varied enormously from one to the next, and we got the impression that their orders were not very specific." Later he is quoted as saying: "You had to understand [the villagers]; they had suffered a lot from the government air force. Several people in every family had been killed in the bombardments."[^ch06-fn384] Perhaps this observation, far from unique, accounts for some of the subsequent killing and oppression. The same pharmacist speaks of the unaccustomed hard work and lack of food, concluding: "The Khmer Rouge were decent enough but if anyone resisted them or didn't obey at once, it meant death."






In his Le Monde articles, Ponchaud was less certain about the alleged "central direction." Here he writes of the Khmer Rouge cadres that "it is difficult to know whether they receive orders coming from the government or whether they act on their personal initiative."[^ch06-fn385] In general these articles give the same account as the book, though obviously in less detail.[^ch06-fn386] What did Ponchaud learn in the interim that caused him to change his mind on this crucial point?






In other connections too Ponchaud refers to diversity of policy. On the matter of "marriage customs," the subject of much denunciation in the Western press, Ponchaud writes that "refugees' accounts differ widely on this point, presumably because of variations in regional practice."[^ch06-fn387] And on revenge as a possible factor for killings, he observes that during the Samlaut jacquerie of the late 1960s the police and military






were heavy-handed, killing many villagers and burning their homes. The population fled into the forest, with intensified loathing for the unjust administration that was leaving a trail of death wherever it went...when the Samlaut peasants took to the mountains [in 1968], they were firmly resolved to pay back a hundredfold the evil that had been done to them.[^ch06-fn388]






Recall again that this was one of the areas where the worst atrocities were later reported, and where Khmer Rouge control is said to have been very limited.






Such examples as these, which can readily be supplemented from the literature, raise serious questions about Ponchaud's certainty with regard to the central direction of the massacres. There seems ample evidence that other factors—peasant revenge, for one—were involved, and it seems to us far from clear, on the evidence that he and others put forward, that practices were as uniform as he claims. We note once again that not one single reviewer or other commentator in the mainstream press, to our knowledge, has expressed any skepticism about these conclusions, and some have elaborated them considerably, e.g., Lacouture, who informs us that the group of intellectuals who proclaim their Marxist ideology as they lead the country to ruin are systematically massacring and starving the population and that the "auto-genocide" of the new rulers shows us that we were wrong when we thought that Auschwitz and the Gulag were "the ultimate in horror." Ponchaud's reference to Lacouture's review expresses no reservations on these or other conclusions, so we may perhaps assume that he regards them as justified. They go far beyond any evidence that he presents (and as noted, are in part inconsistent with this evidence) and are subject to serious question in the light of other evidence to which he does not refer.






In the author's note to the American translation, Ponchaud writes: "I am an exegete by training and profession; I have long been accustomed to applying the methods of source criticism to a body of reported events in order to elicit the historical truth from them."[^ch06-fn389] This self-characterization hardly seems appropriate to the work we have been discussing, with its carelessness with regard to quotes, numbers, and sources. We have ourselves been led to undertake some unexpected exegesis in comparing the various texts that Ponchaud has produced: the Le Monde articles and the French book; the French original and the American and British translations; the Prachachat article and Ponchaud's severely distorted version of its contents. The discrepancies between the British and American translations deserve a further look, as we try to assess the credibility of the unverifiable material that constitutes the bulk of Ponchaud's case.






We have noted several discrepancies between the British and the American translations. In each case, the British translation remains true to the French original whereas the American translation introduces changes that are not trivial, in the light of the way in which the material deleted or modified has been exploited in the international condemnation of the Khmer Rouge. It is a little strange, to begin with, that there should be these discrepancies. None are indicated. There is a single translator: Nancy Amphoux. The author's notes for the two translations are dated on the very same day: September 20, 1977, Paris. Presumably they were written at the same time.[^ch06-fn390] Why then should the two translations differ? The differences are systematic: where a question was raised about the French text in the course of the effort to trace Lacouture's references, the American translation has been modified while the British translation has been left as in the original. We note, finally, that the queries were raised in the United States, and that by an international trade agreement the British translation cannot be purchased in the United States and will not be found in U.S. libraries; the British version is the world edition. Perhaps it is worthwhile to undertake a more systematic review of the discrepancies, in an effort to understand just what is going on.






To review so far, we have noted the following examples:






(1) The British translation includes (in the text, and as modified by Lacouture, on the cover) the alleged quote: "One or two million young people are enough to make the new Kampuchea" (Ponchaud's revision of his Le Monde citation) and the appended statement that the Khmer Rouge are "now grimly turning" this "blood-chilling boast...into a reality." All of this is eliminated from the American translation.






(2) The "quote" that is described as an official text by Lacouture, namely, that "their line must be annihilated down to the last survivor," has been softened to a "recurrent theme" of refugee reports without quotes in the American translation, but left in quotes as a "leitmotiv of justification" in the British version, as in the French.[^ch06-fn391]






(3) With reference to the Thai journal Prachachat, the American translation indicates correctly that there was no interview in the paper with a Khmer Rouge official, as both the French and British versions assert, but rather that such an interview was "cited" in the journal, which gave a second-hand report. Furthermore, the American translation deletes the final ironic comment about the "Great Leap Forward," again softening the impact, while the British version keeps it. We emphasize again that these discrepancies are insignificant in comparison to the gross distortion of the Thai original and the crucial omission of relevant context that remains in the French original and both translations, and is further distorted in Lacouture's review, where it reached a general audience.[^ch06-fn392]






(4) There is a further striking case in which the American and British translations diverge, in perhaps a still more curious way. Recall that the author's notes for the English and American translations are dated on the same day and are translated by the same person. They are also largely identical, but not entirely. The American version begins as follows:






On March 31, 1977, The New York Review of Books published an account of my book under the signature of Jean Lacouture, which provoked considerable reaction in all circles concerned about Asia and the future of socialism. With the responsible attitude and precision of thought that are so characteristic of him, Noam Chomsky then embarked on a polemical exchange with Robert Silvers, Editor of the NYR, and with Jean Lacouture, leading to the publication by the latter of a rectification of his initial account. Mr. Chomsky was of the opinion that Jean Lacouture had substantially distorted the evidence I had offered, and, considering my book to be "serious and worth reading, as distinct from much of the commentary it has elicited" [reference to the review cited in note 100], he wrote me a personal letter on October 19, 1977 in which he drew my attention to the way it was being misused by anti-revolutionary propagandists ...






The British version, dated the same day, begins as follows:






Even before this book was translated it was sharply criticized by Mr Noam Chomsky [reference to correspondence with Silvers and the review cited in note 100] and Mr Gareth Porter [reference to May Hearings]. These two "experts" on Asia claim that I am mistakenly trying to convince people that Cambodia was drowned in a sea of blood after the departure of the last American diplomats. They say there have been no massacres, and they lay the blame for the tragedy of the Khmer people on the American bombings. They accuse me of being insufficiently critical in my approach to the refugees' accounts. For them, refugees are not a valid source ...






The British version then includes the following passage:






After an investigation of this kind, it is surprising to see that "experts" who have spoken to few if any of the Khmer refugees should reject their very significant place in any study of modern Cambodia. These experts would rather base their arguments on reasoning: if something seems impossible to their personal logic, then it doesn't exist. Their only sources for evaluation are deliberately chosen official statements. Where is that critical approach which they accuse others of not having?






None of this appears in the American version.






The contrast between these two texts, both dated September 20, 1977, is quite striking. Our favorable reference to Ponchaud's book in the American version becomes a sharp attack in the British version. The "responsible attitude and precision of thought" that receive such fulsome praise in the American version become complete irrationality, refusal to consider evidence, blind dogmatism, lack of any critical approach, and faked "expertise" in the simultaneous British version.






The accusations in the British version are false, and Ponchaud knows very well that they are false, as is sufficiently clear from the American version penned—it appears—on the same day. Far from saying that "there have been no massacres," we wrote in the article to which he refers that there undoubtedly had been massacres though their scope and character were subject to debate, which we briefly reviewed, including Ponchaud's "grisly account of what refugees have reported to him about the barbarity of their treatment at the hands of the Khmer Rouge" in a book that we described as "serious and worth reading." We concluded that "we do not pretend to know where the truth lies amidst these sharply conflicting assessments," all of which, incidentally, assume substantial atrocities and thousands or more killed. As for Porter, in the reference that Ponchaud cites he begins by writing: "There were undoubtedly large numbers of killings in the newly-liberated areas immediately after the war by soldiers of the victorious army ..." and "it may well be true" that there were summary executions by local officials, though "an adequate picture" will be impossible to construct for many years. Ponchaud's statement that according to Chomsky and Porter "refugees are not a valid source" is also an outright falsehood, as he knows perfectly well. In the reference Ponchaud cites, we wrote: "While [refugee] reports must be considered seriously, care and caution are necessary"; exactly his own explicit conclusion in the book, as we have seen. Porter takes the same position: after giving examples to illustrate the care that must be taken with refugee reports, he writes, in the very reference that Ponchaud cites: "This does not mean that refugee accounts are always false or even grossly exaggerated. But in judging the credibility of assertion based on a refugee report, one should take into account ..."—then follow considerations that would be second nature to any serious journalist or scholar. Ponchaud's final remarks merit no comment, though they give some further insight into his reliability and precision.[^ch06-fn393]






This comparison, which strikes us as quite remarkable, explains why the editors of the Economist were misled into writing that Ponchaud "forthrightly included some of the main attacks as a footnote to the English-language preface,"[^ch06-fn394] referring to our review which described the book as "serious and worth reading," and thus hardly qualifies as an "attack"—recall Ponchaud's citation in the American edition. They were, of course, reviewing the British edition, and naively trusted the author, in this respect as in others. Further questions remain unexplained. Why the stream of falsehoods, surely known to the author to be false, in the British edition, replaced in the simultaneous American edition by a show of courtesy and praise? We note again that the British edition is not obtainable through commercial channels in the United States and is not to be found in American libraries, while conversely, readers of the British edition are unlikely to be familiar with the references to U.S. publications that Ponchaud cites in his series of false accusations.






This kind of petty deceit is unworthy of discussion except insofar as it provides some indication of the credibility of a person who is building a case on largely unverifiable evidence. That issue is important, given the enormous impact of his work and its effect, as it has been amplified through the international propaganda system, in reconstructing attitudes and ideology in the West.






We gain some further insight into Ponchaud's scholarly practice by looking at subsequent translations of his book. The Norwegian translation contains reference to events of May, 1978, and therefore evidently went to press long after the British and American translations were completed, indeed after they had appeared.[^ch06-fn395] The material deleted or modified in the American translation appears in the Norwegian translation, as it did in the French original and the British translation. Evidently, it is only the reader in the United States who is to be spared the material that has been questioned in the United States, and that Ponchaud knows to be indefensible.






In a review of Ponchaud's book that is fairer than most, William Shawcross writes that "Chomsky has pointed out some inconsistencies and mistakes in Ponchaud's book" (referring, presumably, to private correspondence and our published review), "but they are of a minor nature and do not in any way affect that judgment."[^ch06-fn396] The judgment to which he refers is Ponchaud's comment in the author's note to the American translation, which reads: "I was compelled to conclude [in the book], against my will, that the Khmer revolution is irrefutably the bloodiest of our century. A year after the publication of my book I can unfortunately find no reason to alter my judgment."[^ch06-fn397] The evil demon that bedevils quotations about Cambodia has been at work once again. We are, by now, perhaps not surprised to discover that Ponchaud has misrepresented himself. The conclusion stated in the book is not, as he alleges in the author's note, that the Khmer revolution "is irrefutably the bloodiest of our century" but rather a distinctly different one: "the Khmer revolution is one of the bloodiest of the twentieth century."[^ch06-fn398] Actually, we concur with the judgment expressed in the book itself ("one of the bloodiest"), although we feel that the context requires immediate complementary mention—lacking in Ponchaud's book—of the no less bloody U.S.-sponsored counter-revolution and direct assault that precipitated the bloody revolution. Shawcross seems to be implying that we do not concur with the judgment in the book, why, we have no idea; certainly not on the basis of anything we have written.






As for the inconsistencies and mistakes in Ponchaud's book, how seriously one takes them is, of course, a matter of judgment. While we find the conclusion in the book itself valid enough—and are indeed unaware of any contrary view—we want to point out the fallacy of reasoning that leads Shawcross to accept Ponchaud's misrepresentation of the conclusion of his book. The fact is that Ponchaud's book is highly unreliable where an independent check is possible. It is also true that the errors are "of a minor nature" as compared with the bulk of the evidence he presents: unverifiable refugee reports. As we have further noted, even these reports, on which he relies, do not support his unqualified conclusions on the serious question of central direction and planning of atrocities,[^ch06-fn399] and the material that has proven unreliable plays a large role in his argument for central direction and intent. We stress again that it is the verifiable evidence, of however minor a nature it may be, that determines how much faith a rational person will place in material that is subject to no check. This point Shawcross seems to have missed.






In his author's note for the American translation, Ponchaud writes that although "we, the French and the Americans, bear part of the responsibility for the Cambodian drama," nevertheless "we cannot make use of the deaths of millions of Khmers to defend our own theories or projects for society," referring to unnamed "accusing foreigners."[^ch06-fn400] Shawcross ends his review with the second of these statements and then adds: "In fact, of course, it can be and is being done." Shawcross does not say who is "of course" making use of the deaths of millions of Khmers to defend their own theories or projects for society, nor does Ponchaud tell us who are those "accusing foreigners" to whom his injunction is directed. The lapse is not accidental.[^ch06-fn401] It would be difficult indeed to find anyone defending the Khmer Rouge (as distinct from those who exploit and magnify Cambodian atrocities to demonstrate the evils of Communism or liberation) whom this description fits.






The logic should be carefully considered. Shawcross's statement is a plain falsehood and Ponchaud's comment on which it is based is at best seriously misleading, with a presupposition that is plainly false.[^ch06-fn402] There are, to be sure, people who are skeptical of the implicit claim that "millions of Khmers" have died as a result of the policies of the regime—surely nothing that Ponchaud reports substantiates this estimate, which is in fact far higher even than his own assessment of casualties, as we have noted.[^ch06-fn403] There are other people, though they are few indeed, who have defended the Khmer revolution on the basis of their own "theories or projects for society." We know of few people, in fact, who have offered more positive comments than Ponchaud himself does, in his discussion of the emphasis on self-reliance, the dignity of labor, the "new mentality" with its "spirit of responsibility" and "inventiveness," etc. But to fall under Ponchaud's injunction or Shawcross's obviously false claim, a person would have to both agree that millions have died at the hands of the regime and justify this fact on the grounds of his social theories. We seriously doubt that any such person exists. All of this is simply another of the desperate efforts to create an opposition, which we have observed throughout this review.






In fact, there is a different interpretation of Ponchaud's comment and Shawcross's elaboration which can be justified, though one at variance with their intention. There are indeed people—a great many of them—who claim that millions have died (or have been killed) in Cambodia and who are making use of this alleged fact to defend their own theories and projects for society. It is, in fact, one of our main themes that the mass media of the West have discovered Cambodia's travail (previously ignored, understated or suppressed when the direct responsibility was incontestably Western) precisely because of its ideological serviceability. The populace of the West can be mobilized to fear the consequences of "radicalism," attention can be diverted from the proliferating terror within the U.S. sphere, and the case can be reaffirmed that the West must be prepared to intervene to prevent such awful events as the removal of some "gentle land" from the Free World.






Returning to Ponchaud's book, despite flaws that seem to us quite significant, we still believe, as we wrote in the earlier review cited, that it is "serious and worth reading, as distinct from much of the commentary it has elicited" and as distinct from propaganda tracts such as Barron-Paul which have aroused general enthusiasm in the West, for reasons that are all too obvious. A fair review of informed opinion about postwar Cambodia would, in our opinion, include this book as a serious though also seriously flawed and obviously unreliable contribution, in some (but not all) respects, to be placed at the more extreme critical end of the spectrum of specialist judgment and analysis. Such a review would not, however, single this book out (still less, Barron-Paul) as the repository of unchallenged truth, as the media coverage generally suggests. In fact, as we have seen, insofar as its statements cannot be independently verified, they should be regarded with a degree of skepticism, given the fate of those examples that are subject to independent verification.






It is noteworthy that not only the media but also governments appear to have relied uncritically on Ponchaud, despite his evident unreliability. A British government report, released by the Foreign Office, stated that "many hundreds of thousands of people have perished in Cambodia directly or indirectly as a result of the policies of the Communist government," according to the press summary.[^ch06-fn404] The Foreign Office report "cited 'reputable observers' for this estimate." Only one such observer is cited in the Post account: "Father Francois Ponchaud, a French authority on Cambodia." A careful look at Ponchaud's work—specifically, his way with figures (his estimates are cited by the Foreign Office)—shows that it must be regarded with considerable caution; it is at best suggestive, hardly authoritative. If the press account of the British government report is accurate, proper caution was not taken, though an analysis of Ponchaud's work should not have been beyond the resources of the British Foreign Office, had it been concerned with finding the truth.






To complete the review of books about postwar Cambodia, we should mention briefly a third—actually the first to appear—namely the Hildebrand-Porter study to which we have referred several times.[^ch06-fn405] This book differs from the later studies by Ponchaud and Barron-Paul in a number of respects: (1) it is virtually unread (by mid-1977, when we discussed it in the cited review, it had sold about 1,000 copies); (2) it has been almost entirely ignored by reviewers and political commentators apart from occasional abuse; (3) it is carefully documented from Western and Cambodian sources. Factors (1) and (2) are explained by a fourth striking difference: this book gives a rather favorable account of Khmer Rouge programs and a detailed picture of the impact of the U.S. war—a continuing impact, as the authors show. The fourth factor alone suffices to eliminate it from the record, whatever its merits or deficiencies. Published in 1976, the book was well received by the journal of the Asia Society.[^ch06-fn406] In Choice[^ch06-fn407] it is described, in a brief note, as "A rare combination of humanitarianism and scholarly research." Apart from these notices, the book has to our knowledge been reviewed only in our 1977 Nation article (very briefly) and in the New York Review by Shawcross a year later,[^ch06-fn408] where its "use of evidence" was challenged in the manner we described. It has not been used as the basis for editorial comment, with one exception. The Wall Street Journal acknowledged its existence in an editorial entitled "Cambodian Good Guys,"[^ch06-fn409] which dismissed contemptuously the very idea that the Khmer Rouge could play a constructive role, as well as the notion that the United States had a major hand in the destruction, death, and turmoil of wartime and postwar Cambodia. In another editorial on the "Cambodian Horror," the Journal editors speak of the attribution of postwar Cambodian difficulties to U.S. intervention as "the record extension to date of the politics of guilt."[^ch06-fn410] On the subject of "unscrambling Chile," however, the abuses of the "manfully rebuilding" Chilean police state are explained away as an unfortunate consequence of Allendista "wrecking" of the economy.[^ch06-fn411] In brief, Hildebrand and Porter attribute "wrecking" and "rebuilding" to the wrong parties in Cambodia.






In his foreword to the book, Asian scholar George Kahin of Cornell University observes that






in their documented and comprehensive account, George Hildebrand and Gareth Porter provide what is undoubtedly the best informed and clearest picture yet to emerge of the desperate economic problems brought about in Cambodia largely as a consequence of American intervention, and of the ways in which that country's new leadership has undertaken to meet them...Anyone who is interested in understanding the situation obtaining in Phnom Penh before and after the Lon Nol government's collapse and the character and programs of the Cambodian government that has replaced it will, I am sure, be grateful to the authors of this valuable study.






The Free Press, however, is not grateful for an account of the results of the U.S. intervention or the efforts to overcome them, and has shielded the general public from any perception of postwar Cambodia that focuses on these issues.






Since this book does not form part of the media barrage concerning what must be believed about postwar Cambodia, we will not subject it to any further analysis, given our specific concerns here.






It is difficult to convey properly the deep cynicism of the all-too-typical reporting that obscures or completely eliminates the U.S. role in turning Cambodia into a land of massacre, starvation, and disease. While journalists prate about morality, people are dying in Cambodia as a direct result of policies that many of them supported and concealed, and now eliminate from history. It is hardly in doubt that the malnutrition and disease caused by the U.S. war, not to speak of the legacy of hatred and revenge, will have lasting effects upon this "lovely land" with its "engaging people."[^ch06-fn412]






It is difficult to conjure up in the imagination a statement from a Cambodian source that would not have served as proof of Communist iniquity as it entered the U.S. propaganda system. On the anniversary of the Khmer Rouge victory, Khieu Samphan gave a talk over Phnom Penh radio in which he said that agricultural production had improved and people now get enough to eat "to take care of their health and fatten them up." How was this received and interpreted in the United States? An AP dispatch from Bangkok cites this comment, adding that he "made no reference to the starvation, disease and widespread executions reported by many Cambodian refugees. But he admitted that the country...had 'suffered untold difficulties' since the Communist victory."[^ch06-fn413] The reader is presumably to conclude that this "admission" of untold difficulties such as starvation and disease supports the charges against the Communist regime. And just this conclusion is drawn by the Christian Science Monitor in the editorial on Cambodia already cited: "Reading between the lines is illuminating," the editors inform us, repeating the wording of the AP dispatch and commenting: "All this calculated mistreatment of a people in order to make a nation self-sufficient ought not to go unnoticed ..."[^ch06-fn414] Presumably, they prefer the situation in Laos where the United States withholds all but a trickle of aid in the face of overwhelming disaster,[^ch06-fn415] or Vietnam where the refusal is total and even initiatives to normalize relations have been rebuffed by the United States. Recall the widespread acknowledgement that the new regime had considerable, perhaps "spectacular" success in overcoming the food crisis caused by U.S. bombing, considerably more so than the other countries of Indochina. It was hardly irrational for the Cambodian regime to suppose that the United States would leave the country to starve after destroying its agricultural system. If the New York Times, the Christian Science Monitor, and the media in general were expressing any human concern, instead of simply grasping at any straw to find a way to denounce an official enemy, they would be in the forefront of the drive to bring the U.S. government to alter radically its inhuman policy of withholding sustenance from the countries it has destroyed, instead of gloating over the suffering of our victims in one of the most hypocritical displays in modern history.






Bertrand Russell was one of the early critics of Bolshevism after a visit to Russia in 1920. But he also had this to say:






Every failure of industry, every tyrannous regulation brought about by the desperate situation, is used by the Entente as a justification of its policy. If a man is deprived of food and drink, he will grow weak, lose his reason, and finally die. This is not usually considered a good reason for inflicting death by starvation. But where nations are concerned, the weakness and struggles are regarded as morally culpable and are held to justify further punishment...Is it surprising that professions of humanitarian feeling of the part of the English people are somewhat coldly received in Soviet Russia?[^ch06-fn416]






Similarly, when poor peasants are driven into the jungle from villages destroyed by bombing, they may seek revenge. How much more apt are Russell's words when applied to the United States, which bears direct responsibility for bitter suffering throughout Indochina and now refuses to aid the victims because they do not meet its finely discriminating standards of human rights. It would require at least the talents of a Jonathan Swift to do justice to this scene.






To appreciate fully the cynicism of the press and editorial comments, it is necessary to recall the role of the U.S. mass media in supporting the "secret war" against Cambodia. Prior to the Nixon-Kissinger administration, Cambodia had been subjected to U.S. or U.S.-supported armed attack and subversion, but not on a regular and systematic basis. The massive assault against Cambodia began with the B-52 operations, initiated, according to the official record, on March 18, 1969. On March 26 the Cambodian government, recognized by the United States, issued statements condemning the bombing and strafing of "the Cambodian population living in the border regions...almost daily by U.S. aircraft," with increasing numbers of people killed and material destroyed, alleging that these attacks were directed against "peaceful Cambodian farmers" and demanding that "these criminal attacks must immediately and definitively stop ..."[^ch06-fn417] Prince Sihanouk called a press conference on March 28 in which he emphatically denied reports circulating in the United States that he "would not oppose U.S. bombings of communist targets within my frontiers." He went on to say that Communists are not the only victims; "Unarmed and innocent people have been victims of U.S. bombs," including "the latest bombing, the victims of which were Khmer peasants, women and children in particular." He then issued an appeal to the press: "I appeal to you to publicize abroad this very clear stand of Cambodia—that is, I will in any case oppose all bombings on Cambodian territory under whatever pretext."[^ch06-fn418]






The "secret bombings" continued, along with defoliation attacks for which no agency of the U.S. government has as yet admitted responsibility. On January 3, 1970 the Cambodian government issued an official White Paper giving specific details of U.S. and U.S.-client attacks on Cambodia up to May, 1969 by air, sea and land, with dates, places, specific numbers of casualties, photographs, etc. Occasional cases of U.S. bombing of Cambodian villages (including destruction of well-marked hospitals, bombing of ambulances attempting to retrieve wounded, etc.) became public knowledge when discovered by Americans who happened to be on the scene; the usual technique was for the government to deny these reports, then concede them if American eyewitnesses were found to be present.[^ch06-fn419] Throughout this period, the press remained virtually silent. Neither Sihanouk's appeal nor the official White Paper which documented murderous U.S. government attacks on a "friendly" country were considered worthy of comment by the press; we know of no reference to the White Paper in the mainstream U.S. press, though it was hardly a secret.[^ch06-fn420] The "secret bombings" continued, concealed by the U.S. press which was later to claim that it was Richard Nixon who kept the bombings secret from the press and the U.S. public, thus undermining the foundations of our democracy.[^ch06-fn421]






There was one notable exception, namely, a New York Times report by William Beecher which reported B-52 raids on "Vietcong and North Vietnamese supply dumps and base camps in Cambodia," citing U.S. sources and stating falsely that "Cambodia has not made any protest," disregarding Sihanouk's impassioned appeal and his protest against the murder of "Khmer peasants, women and children in particular."[^ch06-fn422] Beecher's report also said that "in the past, American and South Vietnamese forces had occasionally fired across the border and even called in fighters or helicopter gunships to counter fire they received from enemy units there"; not mentioned is the somewhat more important fact that U.S. aircraft attacked Cambodian villages and that according to the "friendly" government of Cambodia, there were such incidents as an attack by U.S., South Vietnamese, and Korean armed forces on a Cambodian village along with aircraft of the same armed forces, after which U.S. and South Vietnamese troops invaded and burnt the villages, among other examples.[^ch06-fn423]






Now the same media that helped conceal these and earlier U.S. attacks on Cambodia, as elsewhere in Indochina, are retrospectively eliminating the U.S. role from history and attributing the consequences of the U.S. attack to its surviving victims.






The peasant army that captured Phnom Penh did not conform to the colonialist cliche. They were not gentle folk with a delightful Khmer smile:






The troops that seized Phnom Penh were dark-skinned peasants. Their close-cropped hair was covered by the traditional checkered peasant headcloth, their uniforms the faded remnants of what had once been olive green fatigues...They neither talked nor smiled. Some appear to be as old as 25 or 30, but a majority seem to be between 12 and 15 years old...Many had probably never seen a city street or a lawn before. Their appearance was equally shocking to many of the residents of Phnom Penh.[^ch06-fn424]






They had suffered bitterly in a war that had been fought with no quarter. Their enemy was a foreign power that had come to destroy their villages and land, and an urban society, hardly less foreign in their eyes, a colonial implantation that they know only as a murderer and a remote oppressor. In the regions where there had been brutal suppression of peasant revolts, there were many scores to settle. In the dark recesses of peasant life and history, unstudied and unknown beyond, there no doubt lay the roots of many more. The latent conflict was churned to a tempest of violence by the armed might of the United States, striking its savage blows directly or by the hands of its local clients. In Vietnam and Laos, where the circumstances were different though comparable, there appears to have been little murderous vengeance—little, that is, by historical standards. In Cambodia, however, the dark-skinned peasants exacted a fearful toll. Of that, there is little doubt.






Beyond that, evidence is slight and unreliable, and informed opinion ranges over quite a wide spectrum. At one extreme, we find Ponchaud—or rather, several different Ponchauds. One of them estimates "peace deaths" at over a million (including more than 100,000 killed); a second alleges that the Khmer Rouge were making good their formidable boast to eliminate 5-7 million people; and a third speaks of "the deaths of millions of Khmers." He regards it as established that a centralized plan dictated a systematic program of terror, massacre and oppression in every town and village, and apparently accepts Lacouture's interpretation that a small group of men who proclaim their Marxist ideology were systematically massacring and starving the people of Cambodia.






Across the spectrum opinions vary. Many, including State Department experts, are quite skeptical of a toll of "millions of Khmers"—we wonder, frankly, whether Ponchaud really believes such figures—and offer estimates of killed ranging from "thousands" upwards, with many more deaths from starvation and disease, though perhaps not the million such deaths predicted by U.S. government sources before the war's end. Many specialists suspect that executions were heavily concentrated in regions of little Khmer Rouge control and unusual peasant discontent and hatred, intensified by war and the U.S. bombings, particularly those of 1973.






There are also varying opinions on the character and effectiveness of Khmer Rouge social and economic programs and the roots of postwar Cambodian society in the traditional culture, Khmer nationalism, and the ideology of the leadership.






We suspect that the main body of informed opinion would accept the tempered comments of such critics of the Khmer Rouge as Charles Meyer that "one should be extremely careful in one's analysis of the politics" of the Khmer Rouge, whose leaders "incarnate really a part of the peasants, who recognized themselves in them," considering carefully such factors as "the weight of the past, the ideology of the leaders, the menaces from outside, and, naturally, the psychological factors as well as the economical, religious and other ones."[^ch06-fn425] Informed opinion would also not dispute the judgment of Laura Summers that "...the Khmer revolution is the expression of deep cultural and social malaise unleashed by a sudden and violent foreign assault on the nation's social structure."[^ch06-fn426]






If a serious study of the impact of Western imperialism on Cambodian peasant life is someday undertaken, it may well be discovered that the violence lurking behind the Khmer smile, on which Meyer and others have commented, is not a reflection of obscure traits in peasant culture and psychology, but is the direct and understandable response to the violence of the imperial system, and that its current manifestations are a no less direct and understandable response to the still more concentrated and extreme savagery of a U.S. assault that may in part have been designed to evoke this very response, as we have noted. Such a study may also show that the Khmer Rouge programs elicited a positive response from sectors of the Cambodian peasantry because they dealt with fundamental problems rooted in the feudal past and exacerbated by the imperial system with its final outburst of uncontrolled barbarism. Such a study, however, has yet to be undertaken. The West is much more concerned to excise from history the imperial role and to pretend that the history of contemporary Cambodia begins in April 1975 in a manner that is disconnected from the imperial legacy and must be explained by the lunacy of "nine men at the center" who were systematically massacring and starving the population in a form of "auto-genocide" that surpasses the horrors of Nazism.






While many questions remain open about Cambodia during the 1975-78 period that we have reviewed, on another question, the one that primarily concerns us, we feel that the facts are clear and overwhelming. The theory of the Free Press that we have been discussing throughout these two volumes is once again dramatically confirmed. The media, in this case as in others reviewed earlier, are serving in effect as a propaganda agency for the state. It is a fair generalization that the more extreme the condemnation of Cambodia, the more confident the claim that "Communism" lies at the roots of its present travail, the more diminished the U.S. share and responsibility—then the greater the exposure. The nature and quality of the evidence presented is of little moment. It is an astonishing fact that where evidence is subject to some independent check, it repeatedly and with remarkable consistency turns out to be fabricated, misleading, or dubious. Furthermore, exposure of falsehoods and fabrication is dismissed as insignificant and unimportant or is even condemned as apologetics for terror. Known fabrications and material of a most dubious nature continue to be exploited long after exposure. The extreme condemnations that constitute the standard fare in the media rest almost entirely on reports that cannot be checked, transmitted by sources that are revealed to be of extremely low credibility where they are subject to some verification.






Critics are not sent to concentration camps; Western societies are indeed free in this respect. Rather, they are permitted to speak to one another, within tiny circles. Meanwhile an image is concocted of a mighty force that must be vigorously combated by those courageous souls who try to stem the flood of apologetics; or it is claimed, with equal merit, that these lone voices must somehow find a way to penetrate the barriers of silence and unconcern. The propaganda system has been committed to eke what profit it could from the misery of Cambodia. Questions of truth are secondary. The serious moral issues that arise—the issues of the real locus of responsibility, the obligations to the victims, and the probable human consequences of the media barrage—have been entirely beyond the comprehension or concern of those who preach in the most strident tones of moral obligations. What enters history in the United States (and, we believe, the West generally, though we have not examined the media systematically elsewhere) is a version of the facts that suits the ideological requirements of dominant social groups; other interpretations, whatever their merits, are simply swept aside. The central theme that liberation from Western domination is a fate to be avoided at all costs is constantly and persistently drilled into popular consciousness. So effective is the awesome system of indoctrination and thought control that even many people who have been critics or skeptics are caught up in the well-orchestrated hysteria.






When the facts are in, it may turn out that the more extreme condemnations were in fact correct. But even if that turns out to be the case, it will in no way alter the conclusions we have reached on the central question addressed here: how the available facts were selected, modified, or sometimes invented to create a certain image offered to the general population. The answer to this question seems clear, and it is unaffected by whatever may yet be discovered about Cambodia in the future.






We urge once again that the reader concerned with the workings of Western propaganda compare the treatment of Cambodia—and the other societies of Indochina as well—with the attention given to other cases where the evidence available, the scale and character of the atrocities alleged, and even the time frame is comparable: Timor, for example. We stress again that in the case of Cambodia, as all observers of even moderate seriousness agree, what happened in the 1975-78 period under review, whatever it may have been, lay beyond our control, whereas in the case of Timor and other ongoing benign and constructive bloodbaths, that is far from true. Perhaps evidence will be forthcoming to support the claim of the British Foreign Office that "many hundreds of thousands of people have perished in Cambodia directly or indirectly as a result of the policies of the Communist government," evidence more credible than the material on which they uncritically relied. There is no doubt that many hundreds of thousands, if not millions of people have perished in other third world countries in the same period as a direct or indirect result of the policies of Western powers, victims of aggression, starvation, disease, hideous conditions of work, death squads, etc. Furthermore, this will continue, with continuing Western responsibility but without government protest or media exposure. The conclusions from such a comparison seem obvious.






Finally, perhaps we should stress some obvious points about what the future may reveal. We speculated in the preface that the Vietnamese invasion may prove disastrous for Cambodia. Any assessment of the resulting conditions should be carefully compared with what visitors observed just prior to the invasion—specifically, with their general assessment that food supplies appeared adequate and that there were certain constructive developments, whatever one may think of the regime.[^ch06-fn427] If there is a deterioration in the conditions of Cambodia, this is very likely a consequence of the invasion itself; and here again the Western contribution cannot be ignored, including the special role played by the propaganda hysteria and climate of opinion of 1975-78, discussed at length above. A no less obvious point is that for some time at least, the Vietnamese (like the Pol Pot regime) are likely to permit only a guided and selected view, so that interpretation of any evidence that may become available will necessarily have to be subjected to critical analysis. The media record hardly encourages optimism, in this regard.


[^ch06-fn301]: Ibid., p. 61.






[^ch06-fn302]: For a serious account of how the Communist forces were built up from an estimated 5-10,000 in the pre-coup period (January 1968 to March 1970), despite opposition from the Vietnamese and Chinese, who opposed the armed struggle line of the Khmer Communist Party, see Heder, op. cit.






[^ch06-fn303]: Even the limited range of sources they cite in their "impeccable documentation" hardly supports their case. Thus under "paucity of popular support for the communists" (p. 214) we find the study edited by Carney, op. cit., which does indeed include the statement by a hostile critic who lived with the Khmer Rouge that the masses do not support them, though it also contains laments from the same source concerning their popularity and success. See note 214 above. Under the same heading they also cite Quinn's study (see note 60), which gives ample evidence suggesting the contrary conclusion, as we have noted.






[^ch06-fn304]: Op. cit., p. 28.






[^ch06-fn305]: Recall that the Tarrs report having seen dead bodies on the streets. As many journalists have noted, it was difficult to decide whether dead that were seen were victims of the last stages of the fighting or postwar executions. Barron and Paul are quite certain, however. Their primary source, Ponchaud, saw no dead bodies (Cambodia: Year Zero, p. 24). See also the report by Lim Pech Kuon cited above, p. 167.






[^ch06-fn306]: Op. cit., p. 215.






[^ch06-fn307]: Not surprisingly, reports transmitted under such circumstances have low reliability. For example, Swain also reports that surgeon Bernard Piquart reported several atrocious acts by Khmer Rouge in the Calmette Hospital, a report corroborated by "other witnesses." But Piquart seems to have had second thoughts. See note 267.






[^ch06-fn308]: Cf. chapter 2, section 2.






[^ch06-fn309]: Recall that people who have a considerable knowledge of Cambodia do not find these fellows so "un-Cambodian like"—cf., e.g. Meyer, p. 255, above; Vickery, note 225—though they are undoubtedly quite unlike those whom Meyer calls the "Western colonials" in Phnom Penh.






[^ch06-fn310]: Compare Barron and Paul, who keep strictly to the government propaganda line: whatever the facts, the U.S. was simply striking "communist sanctuaries" (p. 54), i.e., Vietnamese Communists, as the context makes clear.






[^ch06-fn311]: This is not the only example. To take another, while they quote Swain's horrified account of the evacuation of the hospitals, they omit his equally horrified account of what he saw in a hospital before evacuation. See above, note 264.






[^ch06-fn312]: Cazaux and Juvenal, Washington Post (9 May 1975).






[^ch06-fn313]: This is in response to a surmise by some foreigners that only the strong will survive, so that the forced march is "genocide by natural selection." Others, they say, "believe the depopulation of the cities was a necessary race against time to prepare the rice fields for a new planting. Food is very short now, and much farmland had been devastated by the war."






[^ch06-fn314]: The Washington Post (9 May 1975) carries a story filed from Aranyaprathet (not Bangkok) compiled from unidentified news dispatches that contains reports that many refugees saw decomposing bodies or people who had been shot or apparently beaten to death, citing also Olle Tolgraven of Swedish Broadcasting who said "he did not believe there had been wholesale executions" though the Khmer Rouge may have shot people who refused to leave their homes when ordered to evacuate.






[^ch06-fn315]: Washington Post (9 May 1975). Paul takes care of this annoying fact as follows, in a letter to the Far Eastern Economic Review (9 December 1977): "I'm afraid that the evidence is overwhelming that these people, whoever they were, were either the rare exceptions or were not telling the truth," appealing to the testimony of "scores of Cambodian refugees" most of whom "witnessed summary executions" and all of whom, to his recollection, saw "corpses during the long exodus"—as did some foreigners, though the more scrupulous among them pointed out that it was impossible to know whether they were victims of the recent bloody fighting or of executions. Ponchaud writes that he saw no dead bodies in or near Phnom Penh (Op. cit., p. 24).






[^ch06-fn316]: New York Times (9 May 1975).






[^ch06-fn317]: Le Monde (May 8-10). See the Manchester Guardian Weekly (17 May 1975) and a brief report in the Washington Post (8 May 1975), which notes correctly that his account "lent no substance to reports that a massive and bloody purge of anti-Communists is under way in Cambodia." He saw no bodies en route and found the streets of Phnom Penh empty on leaving the city. His report "was generally favorable to the Khmer Rouge," and thus not to be discussed further.






[^ch06-fn318]: Recall that the second-hand report of the French teacher which they cite from Swain provides no evidence for the horrible consequences of summary executions that "virtually everybody" saw, but rather serves as an example of the "summary executions" themselves, furthermore, an example that does not support their conclusion, as noted.






[^ch06-fn319]: John Barron, letter, Economist (5 November 1977); response to Retbøll's letter of October 15. Anthony M. Paul, letter, FEER, 9 December 1977; response to Retbøll's letter of October 28.






[^ch06-fn320]: See note 17, above.






[^ch06-fn321]: See note 2, above. Even "scoops" have been avoided by the press when they convey an unwanted picture. For example, in 1972 Serge Thion was invited to visit the liberated zones in Cambodia, reporting on his experiences in Le Monde (26, 27, 28 April 1972). His reports provided a unique insight into the character of an unknown, though evidently very successful and significant movement. His story was offered to the Washington Post, but rejected. It appeared nowhere in the U.S. media, to our knowledge. For some excerpts, see For Reasons of State, pp. 190ff.






[^ch06-fn322]: Several are cited in Hildebrand and Porter, in their ignored study.






[^ch06-fn323]: See, for example, the testimony of Peter Poole, May Hearings, pp. 18-19. He points out that "I don't think there is a great deal we can do" to improve the situation though we might easily worsen it, and that even speaking out will do little good in this case. The point was commonly emphasized by people who know and care about Cambodia, as was the fact that the kind of irresponsible and sometimes hysterical "speaking out" that was being done, with its falsifications and unsupported allegations, could cause serious harm. See note 228 of this chapter, and the preface to this volume.






[^ch06-fn324]: Far easier, in fact. Throughout the protest against the U.S. war in Indochina, the Soviet Union was quite reluctant to back or tolerate strong condemnations of the United States, specifically of Nixon, a fact that led to continual controversy at international meetings.






[^ch06-fn325]: Not really "perfectly" because of the condemnation of the United States and the major theme that Khmer Rouge policies have roots and reason in the domestic society. But few will actually read the book, discovering these elements, and the commentary that reaches a mass audience can be counted on, by and large, to keep to atrocity stories. Lacouture takes note of the Western responsibility but ignores the second major theme of the book, as do other reviewers.






[^ch06-fn326]: Author's note for the American translation, p. xiii.






[^ch06-fn327]: William Shawcross, review of Cambodia: Year Zero, Inquiry, 16 October 1978.






[^ch06-fn328]: Economist, 1 July 1978.






[^ch06-fn329]: The Economist is correct, though not for the reasons it probably had in mind, in describing Lacouture's published corrections as "a bizarre episode." In what passes for intellectual discourse in the West, political discussion included, correction of errors is rare indeed, as a glance at review journals will indicate. Lacouture deserves credit for departing from the general norm. We think that his corrections are inadequate and disagree with some of the conclusions expressed in them, but we want to stress that it is no crime to misread—it is a rare review that avoids error—and it is only proper to issue corrections when errors are discovered. One of us (Chomsky) played a role in this, which though entirely a matter of private correspondence has for some reason been the subject of considerable discussion (and distortion) in the press. We see no point in commenting on any of this.






[^ch06-fn330]: The Economist thinks otherwise, for interesting reasons to which we return directly.






[^ch06-fn331]: See, e.g., Leo Cherne's comment on the MacNeil/Lehrer Report, referring to Ponchaud as "very sympathetic to the Khmer Rouge." See note 53. Similarly, the review in Foreign Affairs stresses that Ponchaud "was initially sympathetic to the Khmer Rouge" (Winter, 1978-1979), as have many others who take this alleged fact to add to the credibility of his account (reasonably, if it is true). Shawcross also writes that Ponchaud "originally welcomed the prospect of a revolutionary change" (New York Review, 6 April 1978). See also note 338.






[^ch06-fn332]: New York Review, 31 March 1977; thus he writes that he can read Ponchaud's book "only with shame."






[^ch06-fn333]: New York Times Book Review, 11 September 1977.






[^ch06-fn334]: For Sihanouk's own account, see the preface to this volume.






[^ch06-fn335]: See chapter 2, p. 26.






[^ch06-fn336]: See chapter 4, p. 128.






[^ch06-fn337]: Cambodia: Year Zero, p. 22.






[^ch06-fn338]: Reed Irvine of Accuracy in Media, Inc. (See note 33), letter, Boston Globe (15 October 1978).






[^ch06-fn339]: Lacouture's original charges, in fact, have continued to circulate widely even after they were withdrawn. To cite only one case, Homer Jack, Secretary-General of the World Conference on Religion and Peace, produced a WCRP Report entitled "Can the United Nations stop human massacre in Democratic Kampuchea" (20 November 1978) which is full of fanciful charges, including Jean Lacouture's estimate "of the number of persons killed" as "one-quarter of the population," referring to Lacouture's New York Review article in which he stated that the regime "boasted" of this achievement, but not to his "Corrections" where he stated that the charge had no basis. It is striking that the credible evidence of substantial atrocities never seems to suffice for human rights activists of this type. Jack surely knew of Lacouture's corrections; indeed, in the course of a series of undocumented slanders directed at "the political right wing" and "the left wing," he denounced our review in which the facts were mentioned. Even when the falsehood was specifically called to his attention, among many others in the document, he felt no need to correct it (or others). Recall Orwell's statement on what is true "in the sight of God" in the Stalinist school of falsification; p. 196, above. The example is not untypical.






[^ch06-fn340]: Editorial, "'Cambodia in the Year Zero,'" 26 April 1977.






[^ch06-fn341]: In contrast, its foreign correspondents have often been outstanding.






[^ch06-fn342]: For a few examples of its countenancing certain acts of barbarism and remaining silent about others, see Chomsky, American Power and the New Mandarins, pp. 14f., 185, 244, 277.






[^ch06-fn343]: See note 279.






[^ch06-fn344]: 21 March 1977.






[^ch06-fn345]: New York Times (21 April 1975). The preceding sentence tells us that "the early American decisions on Indochina can be regarded as blundering efforts to do good. But by 1969..." See p. 17, above. More recently Lewis has warned that "America should do nothing" regarding Rhodesia, because, "if we remember Vietnam, we know that intervention, however well-intended, may do terrible harm if it is uninformed." (New York Times, 1 February 1979). The inability of the intelligentsia to inform themselves about what their government is up to truly defies comment.






[^ch06-fn346]: Chomsky, letter, 1 June 1977.






[^ch06-fn347]: 12 May 1977.






[^ch06-fn348]: We know of only one case of honest retraction: Matthew Storin, Boston Globe (13 May 1977), correcting a report of 7 April based on Lacouture. Storin was also unique in his willingness to at least mention contrary evidence that was privately provided to journalists who had relied on Lacouture, along with conclusive evidence that their references were without basis. Alexander Cockburn expressed the hope—in vain—that "such liberal journalists as Lewis" who had relied on Lacouture's derivative account would see "that 'details' do indeed matter" (Village Voice, 16 May 1977). After Lacouture's corrections appeared, a letter was sent to the New York Review by a well-known scientist (Nobel Laureate) commenting that in his field, when conclusions are published based on certain evidence and it then turns out that the cited evidence is incorrect, the scientist does not retract the evidence while reiterating the conclusions—but evidently matters are different in journalism. The letter was not published.






[^ch06-fn349]: As we have mentioned (note 48), in the Nouvel Observateur, where Lacouture's review was originally published, the corrections never appeared. But this fact, which we find rather surprising, is perhaps of little moment given that in the United States, where they did appear, they have been ignored and what remains in the media record are the original errors. A misstated reference by Lacouture to a quote that has been deleted from the American edition appears on the cover of the British edition of Ponchaud's book. A different quote from Lacouture's review appears on the cover of the American edition, with no concern over the fact that the conclusions expressed were based on no accurate citation. See note 339.






[^ch06-fn350]: Somewhat misleadingly. He writes that "My reference to the death of 'one quarter' of the population in a single year must be corrected"—he had spoken of "boasts" and killing—citing Ponchaud's text, which gives a Cambodian estimate of 800,000 dead during the war and a U.S. embassy (Bangkok) estimate of 1.2 million dead (not killed) since the war; adding the two, we obtain the two million figure, about one quarter of the population, that has since been used with abandon in the press and Congress, very likely with this source. See note 293, above, on Ponchaud's 1.2 million estimate allegedly based on "American embassy sources,'' though the embassy offered no such estimate. Thus Lacouture's statement that the Khmer Rouge boast of having eliminated some 2 million people is based on a misreading of a claim by Ponchaud that is dubious to begin with. Ponchaud mentions other estimates attributed to various vaguely-identified sources, but there is little reason to suppose that these claims have any more validity than the single one which is subject to check, and which, as is the way with verifiable claims, turns out to be inaccurate. Lacouture continues to refer to the 2 million figure (dropping the "boast"); "...the hundreds of thousands, indeed 2 million victims ..." of the Pol Pot Regime (Nouvel Observateur, 2 October 1978), an excerpt from his book Survive le peuple cambodgien! He gives no source, and does not explain how such charges will help the Cambodian people to survive.






[^ch06-fn351]: See pp. 72-73 of the French original, pp. 50-51 of the American translation.






[^ch06-fn352]: We do not know why Ponchaud dropped the quotes in the translation in this case. Perhaps because of the focus on the question after Lacouture's review and corrections. Or perhaps the reason lies in a debate over translation from Khmer on which we are not competent to comment. In News from Kampuchea, August 1977, Stephen Heder challenged several of Ponchaud's translations, including this one. He asserts that in this case, the correct translation of the Khmer phrase (which he says is openly used) is something like "to have no more of this kind of person (e.g., imperialists, oppressors)." In a privately circulated document ("Vicissitudes de la linguistique au service de l'Idéologie abstraite," Ponchaud rejects these challenges to his translations. In this case he states that Heder's proposed translation is "false," but also says that his own translation was "hasty," and would require more time to justify and polish. His own account of the meaning seems to us to leave the correct interpretation rather ambiguous over a certain range, with his specific formulation at the harsher extreme. In any event, even if there is a quote, contrary to what the American edition suggests, it would seem that Lacouture's conclusions from a possible rhetorical flourish are distinctly questionable.






[^ch06-fn353]: The quote as Lacouture gives it in his Nouvel Observateur review is inaccurate, and further errors are introduced in the English translation. We will drop this matter, keeping to Ponchaud's text.






[^ch06-fn354]: P. 73 of the French original.






[^ch06-fn355]: This translation, which is sufficiently accurate, is what appears in the British edition, p. 70.






[^ch06-fn356]: Heder provided us with an English translation; Ponchaud with a French translation and the Thai original.






[^ch06-fn357]: Our apologies to the editors of Prachachat for the comparison.






[^ch06-fn358]: News from Kampuchea, August 1977.






[^ch06-fn359]: Cf. note 273, above. Also, note 82.






[^ch06-fn360]: There is a problem in that the French translation given in Ponchaud's book differs from the French translation that he sent us, which includes the context omitted in the book. We will assume that the translation that he sent us is accurate. It corresponds closely to the English translation provided by Heder. We have not taken the trouble to verify the translations from the Thai original, since the main points emerge fairly clearly even without this further step.






[^ch06-fn361]: The phrase reads: "il peut même arriver qu'on n'y arrive pas partout, et les autorités se trouvent alors chargées d'un fardeau très lourd."






[^ch06-fn362]: American edition, p. 51, a fair translation of the French text in Ponchaud's book.






[^ch06-fn363]: This exercise in verification raises some further questions. It is striking that those passages in the original French text that drew attention because of Lacouture's review have been softened, deleted, or changed in the American translation, or where they remain, are extremely misleading or outright misrepresentations. Note that this is true of each of the four cases just discussed, including the first, where a look at Ponchaud's text shows that estimates of roughly a million dead (the most crucial of which lacks any credible source) become, a few lines later, allegations that many millions are being eliminated, most of the population in fact. These passages were selected for investigation at random, in effect; that is, they were not selected on any basis other than the fact that they seemed to be the passages that Lacouture had in mind in his misrepresentations of (i.e., references to) the book. The facts suggest some obvious questions about the remainder. We have not carried out a thorough line-by-line comparison but a fairly careful reading has not brought to light any other changes from the French original to the American translation (apart from some new material and some rearrangement). If this impression is correct, it also suggests obvious questions.











Ponchaud's book is almost completely lacking in verifiable documentation. The Prachachat reference is one of a handful of examples. It is therefore of more than passing interest to see how it fares upon examination.






[^ch06-fn364]: For a review, see Chomsky, For Reasons of State, chapter 2, where there are references for the citations here.






[^ch06-fn365]: Roger Hilsman, To Move a Nation, Dell, 1967, pp. 436f.






[^ch06-fn366]: New York Times (20 March 1964).






[^ch06-fn367]: See chapter 1.






[^ch06-fn368]: Cambodia: Year Zero, p. 164.






[^ch06-fn369]: Ibid.






[^ch06-fn370]: See below, p. 288. It has been alleged that Sihanouk was being hypocritical in his denunciation of the U.S. bombing and that he had in fact secretly authorized it. This has been occasionally argued in defense of the failure of the U.S. media, like Ponchaud, to make public Sihanouk's impassioned criticism of the bombing of the civilian society of Cambodia. Two points deserve notice. First, even if Sihanouk secretly authorized bombing of "Vietcong bases," he surely did not authorize bombing of Khmer peasants, and his protests were directed against the latter crime. Second, while commentators and media analysts may draw whatever conclusions they please from the conflicting evidence available, this does not entitle them to suppress what is, by any standards, crucial evidence, in this case, Sihanouk's attempt to arouse international protest over the U.S. bombing of the civilian society.






[^ch06-fn371]: Cambodia: Year Zero, pp. 165, 169.






[^ch06-fn372]: Ibid., p. 170.






[^ch06-fn373]: Ibid., p. 167.






[^ch06-fn374]: Ibid.






[^ch06-fn375]: Ibid., p. 164.






[^ch06-fn376]: See notes 146, 147 above.






[^ch06-fn377]: Ibid., p. 21.






[^ch06-fn378]: See above, p. 183.






[^ch06-fn379]: See pp. 175 and 191 above.






[^ch06-fn380]: Ibid., p. 50.






[^ch06-fn381]: Ibid., p. 28.






[^ch06-fn382]: See Peang Sophi's testimony, p. 243 above. See also several reports cited by Kiernan, "Social Cohesion," from the Bangkok Post, reporting the statements of refugees that an order to stop reprisals was announced at the end of May 1975.






[^ch06-fn383]: See note 237, above, for a review of their scope and character.






[^ch06-fn384]: Cambodia: Year Zero, pp. 16, 53. Ponchaud does not explicitly state that this is the same man, but it appears so from his description.






[^ch06-fn385]: Le Monde (17 February 1976).






[^ch06-fn386]: Sometimes in more detail, as we have noted in the case of the alleged "quote" about 1-2 million young Khmers being sufficient to build the new Cambodia.






[^ch06-fn387]: Cambodia: Year Zero, p. 125.






[^ch06-fn388]: Ibid., p. 162. See also notes 203 and 240, above.






[^ch06-fn389]: Ibid., p. xiv.






[^ch06-fn390]: But given Ponchaud's carelessness with fact, already noted in several cases, some caution is in order here as well. Thus, the author's note to the American translation, dated 20 September 1977, contains a reference to a letter dated 19 October 1977.






[^ch06-fn391]: See note 352, above.






[^ch06-fn392]: We omit reference to other slight discrepancies.






[^ch06-fn393]: We have kept to published material, omitting discussion of personal correspondence mentioned by Ponchaud, who presumably obtained it from the editor of the New York Review. His references to this personal correspondence, apart from being irrelevant, are incorrect. What he calls "a polemical exchange" leading to Lacouture's corrections consists of personal letters pointing out errors and urging correction; Lacouture's published corrections reveal how little it was "polemical." It is difficult to imagine a less polemical response to the discovery of serious errors, and it was so understood, as the correspondence clearly shows. Nor is there anything in this correspondence to support Ponchaud's false statements, though even if there were, it would be irrelevant in this context, as should be obvious. We should perhaps mention that in his book cited above and in articles and interviews elsewhere, Lacouture has been presenting grossly false versions of Chomsky's views, invariably without the slightest effort at documentation, and indeed, quite inconsistent with what he knows to be true. This too deserves no further comment.






[^ch06-fn394]: See note 329. Ponchaud's fakery has also found its way into what purports to be "scholarship." In a review of Ponchaud's book in International Affairs, journal of the Royal Institute of International Affairs (January 1979), Dennis Duncanson writes that "The author reports, without rancour, that after the French edition came out it was attacked by Professor Noam Chomsky and Mr. Gareth Porter for relying on refugees' stories, on the grounds that refugees can be assumed to warp the truth, that we ought to give the Phnom Penh Politburo the benefit of its secrecy, and that as a positive fact no massacres took place in Cambodia." This is an embellishment of Ponchaud's false statements in the British translation, presented here simply as fact—to this scholar, it is of no concern that Ponchaud's charges are presented not only "without rancour" but also without a particle of evidence, and that, as can be easily verified, the charges are not only false but indeed were conscious falsehoods, as we have seen. Duncanson proceeds with further falsehoods and undocumented slanders that give some insight into what is regarded as "scholarship" in this domain but are otherwise not worthy of comment.






[^ch06-fn395]: Tiden Norsk Forlag, 1978, p. 210. See note 141, above. We are indebted to Torben Retbøll for providing us with the relevant pages.






[^ch06-fn396]: Inquiry, 16 October 1978. See note 327, above, and text.






[^ch06-fn397]: Cambodia: Year Zero, p. xiv.






[^ch06-fn398]: Ibid., p. 136.






[^ch06-fn399]: Shawcross regards this question as not just serious, but the most crucial question, and he believes that the evidence has firmly established central direction and intent. See note 187, above, and text. In his published work, he appears to rely largely on Ponchaud, quite uncritically.






[^ch06-fn400]: Cambodia: Year Zero, p. xvi.






[^ch06-fn401]: The lapse on Ponchaud's part is perhaps far from accidental. Thus in the British translation, the comparable passage in the author's note (p. 16) clearly implies that the "accusing foreigners" are the ones to whom he has already referred: namely, Chomsky and Porter, who "say there have been no massacres" and regard refugees as "not a valid source," an allegation that he knows perfectly well to be false, as we have seen.











Recall again that the British version is not available in the United States, where the merits of his allegations can readily be determined.






[^ch06-fn402]: Much the same is true of Ponchaud's rhetorical question: "How many of those who say they are unreservedly in support of the Khmer revolution would consent to endure one hundredth part of the present sufferings of the Cambodian people" (p. 193), immediately following the familiar accusation that few voices have been "raised in protest against the assassination of a people." He fails to enumerate those who are unreservedly in support of the Khmer revolution, though the list would be small enough so that it could easily have been given at this point. Note also that another question might easily be raised: how many of those who virulently condemn the Khmer revolution would consent to endure one hundredth part of the suffering of the peasants of the traditional society of Cambodia?—a society that was hardly improving their lot in its latter days.






[^ch06-fn403]: In fact, we know of no specialist who takes such an estimate seriously, including Ponchaud in his more sober moments.






[^ch06-fn404]: Washington Post (21 September 1978).






[^ch06-fn405]: See note 9. Ponchaud mentions it in the author's note to the American translation without comment, postdating it by a year.






[^ch06-fn406]: Asia, March-April 1977.






[^ch06-fn407]: July/August 1977.






[^ch06-fn408]: See notes 237, 259 above.






[^ch06-fn409]: 22 November 1976.






[^ch06-fn410]: 16 April 1976.






[^ch06-fn411]: 20 September 1976.






[^ch06-fn412]: Recall the predictions by U.S. government sources of impending starvation that will take a million lives, or by the Western doctors cited by Hildebrand and Porter (see p. 184, above) in a book which for this reason alone must be kept from public notice.






[^ch06-fn413]: New York Times (19 April 1977), our emphasis.






[^ch06-fn414]: 26 April 1977. The implication here, and explicit statement commonly, is that Cambodia did or would refuse any shipments of food. Is that correct? The crew of the Mayaguez saw two Chinese freighters unloading rice in the port of Kampong Som in May 1975. See Roy Rowan, The Four Days of Mayaguez, Norton, 1975, p. 153.






[^ch06-fn415]: See chapter 5, note 30.






[^ch06-fn416]: Bertrand Russell, The Practice and Theory of Bolshevism, Allen and Unwin, 1920, pp. 68, 55.






[^ch06-fn417]: The specific instances cited are not B-52 attacks.






[^ch06-fn418]: Bombing in Cambodia, Hearings before the Committee on Armed Services, U.S. Senate, Ninety-third Congress, first session, July/August, 1973, U.S. Government Printing Office, Washington, 1973, pp. 158-160. See note 370.






[^ch06-fn419]: Cf. Chomsky, At War With Asia, 1970, pp. 121ff.






[^ch06-fn420]: Ibid., pp. 122-123.






[^ch06-fn421]: In the Watergate hearings the alleged "secrecy" of the bombing became an issue but not the bombing itself. Nixon's crime, we must assume, was not that he sent his bombers to destroy a relatively peaceful country with which the United States had "friendly" relations, but that he kept the matter from Congress. On the hypocrisy of the Watergate proceedings and the press reaction quite generally, see Chomsky, introduction to Blackstock, ed., Cointelpro.






[^ch06-fn422]: William Beecher, "Raids in Cambodia by U.S. unprotested," New York Times (9 May 1969). Recall Ponchaud's comment that Sihanouk's protest against the bombing of North Vietnamese and Vietcong sanctuaries deceived no one. As we pointed out in note 370, Sihanouk's protests were primarily against the bombing of Khmer civilians. In regard to the bombing of Vietnamese concentrations near the border, while there is conflicting evidence as to Sihanouk's attitude, it is not up to the press or others to decide what it "really was" and then to withhold reference to his explicit appeal just cited on grounds that no one is deceived by it. What is more, recall that the bombings of the "Vietcong and North Vietnamese" sanctuaries were undoubtedly aimed at Vietnamese who had been driven across the border by murderous U.S. military operations in Vietnam, primarily since early 1967. And finally, recall that direct observation by Western reporters and others confirms that the B-52 raids were by no means aimed at the Vietnamese. See for example, Swain, op. cit.; p. 284-85, above. While the precise scale of these atrocities could not have been known in 1969, and is not known now in the West, a free press could have surmised and perhaps learned a great deal had it chosen to do so. It is remarkable that Beecher's unique though quite inadequate account is now held up as evidence that the press maintained its honor throughout this period, despite the crimes of Richard Nixon.






[^ch06-fn423]: See At War With Asia, pp. 121-22.






[^ch06-fn424]: Jean-Jacques Cazaux and Claude Juvenal, AP, Washington Post, 9 May 1975.






[^ch06-fn425]: See above, pp. 255-56.






[^ch06-fn426]: "Defining the Revolutionary State in Cambodia."






[^ch06-fn427]: See the accounts surveyed above, as well as the assessment in the FEER Asia 1979 Yearbook.



