project:
  type: book
  output-dir: ../docs/chomsky-hr2/

book:
  title: "The Political Economy of Human Rights, Volume II: After the Cataclysm"
  subtitle: "Postwar Indochina and the Reconstruction of Imperial Ideology"
  cover-image: cover.jpg
  author:
    - "Noam Chomsky"
    - "Edward S. Herman"
  date: "9/29/2023"
  chapters:
    - index.qmd
    - ch01-The_Setting.qmd
    - ch02-Precedents.qmd
    - ch03-Refugees.qmd
    - ch04-Vietnam.qmd
    - ch05-Laos.qmd
    - part: ch06-Cambodia.qmd
      chapters:
      - ch06-cambodia/ch06-1.qmd
      - ch06-cambodia/ch06-2.qmd
      - ch06-cambodia/ch06-3.qmd
      - ch06-cambodia/ch06-4.qmd
    - ch07-Final_Comments.qmd
    - references.qmd

bibliography: After_the_Cataclysm.bib

format:
  html:
    theme: cosmo
    css: "style.css"
  #pdf:
  #  documentclass: scrreprt



