# Precedents






2.1 The Intelligentsia and the State






In considering the refraction of events in Indochina through the prism of Western ideology, it is useful to bear in mind some relevant precedents. The first class of precedents has to do with the ways in which influential segments of the intelligentsia have responded in the past to abuses of state power; the second, with the record of treatment of former enemies after revolutionary, civil or other military conflicts.






Consider first the typical relations of the intelligentsia to state power. Quite commonly, intellectuals have a strong moral attachment to some favored state—usually their own—and have devoted themselves to lauding its alleged achievements (sometimes real) and concealing its abuses and crimes. At times, the “herd of independent minds” (Harold Rosenberg’s apt phrase) has succeeded in virtually stifling opposing views. One recalls, for example, the reaction to George Orwell’s Homage to Catalonia at a time when Stalinist loyalties were influential—one may also imagine how he would have reacted to its rediscovery and conversion to a cold war document when fashions changed. Similarly today, when “support for Israel” has taken on some of the characteristics of the earlier Stalinism of the intellectuals, it has been difficult for studies critical of one or another aspect of Israeli policies to find a publisher, or if published to receive an honest appraisal, in the United States.[1](../Text/Notes.html#Chapter2-FN1)






When the herd stampedes in a different direction for one reason or another, and service to some favored foreign state no longer has its earlier appeal, we enter the “God that failed” phase, which at one time had a certain validity and integrity, but now has become, all too often, a pose for those who adopt the more typical stance of the intelligentsia, namely, service to the propaganda system of their own state. To this end, it is often convenient to manufacture past allegiance to the current enemies against which recriminations are directed.






The normal case of straight chauvinist bias is, of course, of central importance in shaping the responses and defining the role of mainstream intellectuals, in part for reasons we have already discussed in Volume I, chapter 1, section 16. A primary social role of the group that Isaiah Berlin called “the secular priesthood” is to speak positively of the institutions and objectives of the state and dominant power interests within it in order to help mobilize public commitment and loyalty.[2](../Text/Notes.html#Chapter2-FN2) The adaptability of intellectuals to quality variation in the social order for which devotion is sought has proven to be very great—the pre-Civil War southern intelligentsia even found the slave system worth cherishing despite its economic inefficiency (“slave labor can never be so cheap as what is called free labor”) on the grounds of its sheer humanity and social beneficence (“what is lost to us [from inefficiency] is gained by humanity”).[3](../Text/Notes.html#Chapter2-FN3)






A further traditional role of intellectuals is to disseminate propaganda concerning the evil practices, real or fabricated, of current enemies of the state. It is remarkable to see how susceptible intellectuals have been, over the years, to the machinations of the atrocity fabrication industry. A classic example is the success of the British propaganda agencies in whipping up hysteria in the United States over alleged “Hun atrocities” during World War I, particularly among intellectual circles committed to war after the 1916 presidential election, which Wilson had won on a pledge of peace. “It was in the group known as ‘intellectuals,’” H.C. Peterson points out in his study of British efforts to induce Americans to support their cause, “that the best body of propagandists was enlisted.” These efforts resulted in “the enlistment of most of the leaders of intellectual life in America...it was an imposing propaganda group.” “Prominent men of America hastened to join a cause that was intellectually fashionable” and “College professors and school teachers repeated with a great show of wisdom the arguments which had originated” in the British and French propaganda services, whereas “in contradistinction to the easy surrender of American leaders was the stubborn pacifism of the great mass of the population.”[4](../Text/Notes.html#Chapter2-FN4)






Particularly effective among the intellectuals was the Bryce Report, produced in 1915 by a committee of inquiry chaired by Viscount Bryce, “a venerable scholar”[5](../Text/Notes.html#Chapter2-FN5) and former ambassador to the United States, beyond suspicion of Germanophobia, as admitted even by German critics, because of his long association with German universities and receipt of highest honors from the Kaiser. His committee also included other distinguished intellectuals and jurists. Its report was widely circulated throughout the world and scored its greatest success in the United States where it was widely printed in full and had an “overwhelming effect on the American mind and heart” (Daily Mail). Lord Bryce was initially skeptical of atrocity propaganda and hoped that his committee would “reduce within a small compass the burden of the charge,” according to an associate. But he was convinced by the “compelling mass of evidence” that had been gathered and became “an advocate of a fight to the finish” (Read).






The committee relied on some 1200 depositions, mostly by Belgian refugees in England, some by Belgian and British soldiers, as well as diaries of German soldiers, regarded as “the most weighty part of the evidence” in the report itself. The depositions were taken by twenty barristers. The committee was aware of the problems posed by refugee testimony and raised the case for skepticism in the introduction to the report:






It is natural to ask whether much of the evidence given, especially by Belgian witnesses, may not be due to excitement and overstrained emotions, and whether, apart from deliberate falsehood people who mean to speak the truth may not in a more or less hysterical condition have been imagining themselves to have seen things which they said they saw.






But the committee was so careful in sifting and evaluating the material that they felt they had overcome this difficulty. The 1200 depositions, incidentally, have not been found.






The report cites innumerable atrocities of the most fiendish sort. However, a Belgian commission of inquiry in 1922, conducting its investigations at the scene of the alleged atrocities, failed to confirm these atrocious crimes and was in general far more restrained. Read himself concludes that “the refugees naturally desired to convince their English hosts that they had fled from monsters,” and discounts the Bryce Report, which, in retrospect, contains little that is credible. According to Peterson,






A large percentage of the events making up the report was based upon second and third hand information. Rumors and opinions were included uncritically. It is not impossible that many of the statements used were the product of leading questions. Incomplete versions of actual events were the basis of the report. In addition, this official report of the British government dignified a great many old wives’ tales and considerable barrack-room gossip (pp. 53-54).






Of one story, Peterson notes, “This, of course, is but a rewrite of a standard wartime atrocity story. Senator Cullen of Nebraska used it in 1898” (p. 55). Of another, “This story is undoubtedly the work of someone’s feverish imagination” (p. 55).






The Bryce Report is perhaps the most important example available of a careful analysis of refugee reports on the part of a group attempting to assess the crimes of an enemy state. It was compiled under near-optimal conditions, and should be carefully borne in mind in evaluating such reports (or alleged reports) under far more ambiguous circumstances, from much more dubious sources.[6](../Text/Notes.html#Chapter2-FN6)






While U.S. intellectuals assured one another that the nation had entered the war “under the influence of a moral verdict reached after the utmost deliberation by the more thoughtful members of the community,”[7](../Text/Notes.html#Chapter2-FN7) it is not unlikely that the British and French propagandists who were feeding them myths about babies with their hands hacked off by German barbarians, etc., were laughing up their sleeves. Very soon, U.S. scholars took their own initiatives, as when a group of historians engaged in what one called “historical engineering, explaining the issues of the war that we might the better win it,” produced such material as The German-Bolshevik Conspiracy, a series of forged documents (as was suspected in Europe at the time) purporting to show that the Germans had materially assisted the Bolsheviks in coming to power and that Bolshevik leaders were paid agents of the German general staff.[8](../Text/Notes.html#Chapter2-FN8)






As intelligence services have become more sophisticated—or at least, better funded—they have learned to play upon the willingness of the more thoughtful members of the community to believe the worst about official enemies of the state to which they are devoted. One technique is to arrange for “scholarly studies,” such as the book by Hoang Van Chi which had such remarkable success in establishing the mythology concerning the bloodbaths during the North Vietnamese land reform.[9](../Text/Notes.html#Chapter2-FN9) Another device is to plant stories in the foreign press, to be picked up by “witting” (or perhaps, witless) journalists and others. The CIA recognized long ago that foreign correspondents are particularly susceptible to such deception since they so often tend to rely on local contacts for their “insights.” If these locals can be enlisted in the cause, the news can properly be arranged at the source. Some interesting examples of how it is done appear in the memoirs of Joseph Smith, a CIA agent who was impelled by the appearance of Philip Agee’s exposure of the CIA to write in defense of the Agency.[10](../Text/Notes.html#Chapter2-FN10) He describes, for example, how he enlisted a local newsman in Singapore on whom “the big-name foreign correspondents...relied...for all their scoops and legwork.” One of the useful contributions of this subordinate was to file a fake story, attributed to British defense officials, reporting that the Chinese were sending troops and supplies to the Viet Minh just prior to the 1954 Geneva conference; the purpose was to undermine the conception of the Viet Minh “as a purely indigenous Vietnamese group of national patriots” by identifying them “with the world Communist movement,” thus strengthening the Western-backed groups at Geneva, Smith explains. Other CIA stations were alerted “to have their press assets ready to pick [the story] up and make sure [it] was used in as many newspapers as possible.”






There is little doubt that such intelligence machinations have influenced scholarship.[11](../Text/Notes.html#Chapter2-FN11) One of the standard claims about the early stages of the U.S. involvement in Vietnam, faithfully repeated by John K. Fairbank, Edwin Reischauer and other leading Asian scholars, is that the U.S. intervention was grounded in a “tragic error,” the false belief that Ho Chi Minh was a “frontline agent” for the international Communist conspiracy—had we not been so naive and uninformed, so unpracticed in the ways of imperialism, we would have perceived that Vietnamese communism was in reality a national movement and been spared the “American tragedy” of Vietnam.[12](../Text/Notes.html#Chapter2-FN12) This claim is thoroughly refuted by the documentary record, which reveals that from the beginning U.S. analysts understood perfectly well that the source of Viet Minh strength lay in its credentials as the leading force in Vietnamese nationalism, and that after the United States determined to intervene, for quite rational imperial motives that are carefully outlined in planning documents and just as carefully excluded from the scholarly record, efforts were set in motion to establish the preferred (but false) “facts” necessary to justify this intervention, namely, that the Viet Minh were really agents of Moscow or “Peiping.”[13](../Text/Notes.html#Chapter2-FN13) Mainstream scholarship can be trusted to conform to the requisite mythology, just as in the true totalitarian societies.






Smith is not the only CIA source for information on news management. To cite only one further case, consider Snepp’s account of the last days of the Saigon regime,[14](../Text/Notes.html#Chapter2-FN14) also presented from a standpoint quite favorable to the general goals of the CIA though critical of its errors. He points out, for example, that the U.S. embassy in Saigon organized “a noisy press campaign around recent reports that the Communists were torturing and mutilating recalcitrant civilians in newly captured areas,” in the hope that this would generate sympathy for the “South Vietnamese,”[15](../Text/Notes.html#Chapter2-FN15) but the campaign had the unwanted effect of sparking “panic and chaos” among “the South Vietnamese population itself’ (p. 297). Snepp also cites his notebook references to the






atrocity stories...now imaginatively embroidered by Saigon radio, the local press and the Embassy. At the Ambassador’s orders, Joe Bennett [the political counselor] is still zealously churning out his share of them, playing on thirdhand reports relayed out of Ban Me Thuot by a Buddhist monk. “They’re tearing out women’s fingernails up there and chopping up the town council,” one of Bennett’s younger staffers advised me gleefully this afternoon. “That should turn some heads in Congress.”






The ambassador and CIA chief, Snepp reports, “apparently consider the latest crop too useful to risk putting them to any...test” of veracity; again, he notes, the stories terrorized the Vietnamese.[16](../Text/Notes.html#Chapter2-FN16)






Perhaps the most cynical example of atrocity management that Snepp cites was “Operation Baby-Lift,” which “in a sense” was “a fraud from the start,” in which children who “had been languishing for years in Saigon’s orphanages and were in no immediate danger from the Communist offensive” were, in effect, kidnapped and flown out of the country to the United States in the hope, expressed by Ambassador Martin, “that the spectacle of hundreds of Vietnamese babies being taken under the American wing would generate sympathy for the South Vietnamese cause around the world.” Not all of them made it; over 200 were killed in the crash of a C-5A air transport, somewhat diluting the intended propaganda effect, though the operation continued.[17](../Text/Notes.html#Chapter2-FN17)






It is predictable that the exposure of such tactics from the source, as in the past, will have little or no effect in diminishing the credulity of Western intellectuals with regard to the next batch of atrocity stories. We have discussed other examples of atrocities management in Volume I, chapter 5. The will to believe patriotic truths and a positive desire to aid the cause of one’s own state are dominant forces, and those abiding by such principles may also anticipate corresponding rewards and privileges.






The general subservience of the articulate intelligentsia to the framework of state propaganda is not only unrecognized, it is strenuously denied by the propaganda system. The press and the intelligentsia in general are held to be fiercely independent, critical, antagonistic to the state, even suffused by a trendy anti-Americanism. It is quite true that controversy rages over government policies and the errors or even crimes of government officials and agencies. But the impression of internal dissidence is misleading. A more careful analysis shows that this controversy takes place, for the most part, within the narrow limits of a set of patriotic premises. Thus it is quite tolerable—indeed, a contribution to the propaganda system—for the Free Press to denounce the government for its “errors” in attempting “to defend South Vietnam from North Vietnamese aggression,” since by so doing it helps to establish more firmly the basic myth: that the United States was not engaged in a savage attack on South Vietnam but was rather “defending” it. If even the hostile critics adopt these assumptions, then clearly they must be true.






The beauty of the democratic systems of thought control, as contrasted with their clumsy totalitarian counterparts, is that they operate by subtly establishing on a voluntary basis—aided by the force of nationalism and media control by substantial interests—presuppositions that set the limits of debate, rather than by imposing beliefs with a bludgeon. Then let the debate rage; the more lively and vigorous it is, the better the propaganda system is served, since the presuppositions (U.S. benevolence, lack of rational imperial goals, defensive posture, etc.) are more firmly established. Those who do not accept the fundamental principles of state propaganda are simply excluded from the debate (or if noticed, dismissed as “emotional,” “irresponsible,” etc.).






In a typical example, when the New York Times (5 April 1975) gave its retrospective assessment of the Vietnam tragedy, it referred to “the decade of fierce polemics” (to be resolved in due course by “Clio, the goddess of history”) between the hawks who thought that the United States could win and the doves who were convinced that the U.S. objective was unattainable. Those who opposed the war in principle—specifically, the mainstream of the peace movement—were simply not part of the debate, as far as the Times was concerned. Their position need not be refuted; it does not exist.[18](../Text/Notes.html#Chapter2-FN18),[19](../Text/Notes.html#Chapter2-FN19)






An excellent illustration of how the ideological institutions operate to buttress the state propaganda system by identifying the media as “hypercritical,” so much so as to endanger “free institutions,” is provided by a two-volume Freedom House study of the alleged bias and incompetence of the media in portraying the Tet Offensive as a defeat for the United States and thus contributing to the failure of U.S. arms by their excessive pessimism.[20](../Text/Notes.html#Chapter2-FN20) The name “Freedom House” should at once arouse a certain skepticism among people attuned to the machinations of modern propaganda systems, just as any good student of Orwell should have realized that a change in the name of the U.S. War Department to “Defense Department” in 1947 signalled that henceforth the state would be shifting from defense to aggressive war. In fact, “Freedom House” is no less of an Orwellian construction, as its record indicates.[21](../Text/Notes.html#Chapter2-FN21)






The study in question is in the Freedom House tradition. Contrary to its intentions and stated conclusions, any independent-minded reader should infer from its 1500 pages of text and documents that the media were remarkably loyal to the basic doctrines of the state and tended to view the events of the period strictly from the government’s point of view. But these facts, though obvious from the documents cited, completely escaped the author and his Freedom House sponsors; naturally, since they take ordinary press subservience as a norm. What is most striking about the study, apart from its general ineptitude,[22](../Text/Notes.html#Chapter2-FN22) are the premises adopted without comment throughout: the press is unjustifiably “pessimistic” if it tends to believe that U.S. force may not prevail in “defending South Vietnam,” and is “optimistic” if it expresses faith in the ultimate success of U.S. state violence. Pessimism is wrong even if based on fact and in conformity with the views of the Pentagon and CIA (as was often the case, specifically, in the instance in question). Since optimism is demanded irrespective of facts, the implication of this study is that “responsible” media must deliberately lie in order to serve the state in an undeviatingly propagandistic role.






To summarize the first class of precedents, the intelligentsia have been prone to various forms of state worship, the most striking and significant being subservience to the propaganda systems of their own government and social institutions. This subservience often takes the form of childish credulity that is effectively exploited by the organizations that are devoted to atrocity fabrication and other modes of ideological control. Sometimes the credulity is feigned, as the propagandist knowingly transmits a useful lie. All of this serves as a warning that should be borne in mind as we approach the issues at hand.











2.2 In the Light of History






We turn next to the second class of precedents, namely, the record of retribution following other wars. Here, one must be cautious with analogies. The U.S. war in Vietnam—later all of Indochina—reached levels of savagery and destructiveness that have rarely been paralleled, so that one might have anticipated that retribution by the victors would also pass well beyond normal levels. Nevertheless, it is useful to survey some of these “normal levels,” as a suggestion of a “base line” for evaluation of the situation in postwar Indochina.






To begin with a recent example, consider the immediate aftermath of World War II—recalling that the United States was never attacked directly (Hawaii and the Philippines were colonies), so that the more primitive forms of vengeance were not to be expected. The U.S. army of occupation in Japan, according to Japanese sources, indulged in rape, pillage, and murder.[23](../Text/Notes.html#Chapter2-FN23) But that, perhaps, is to be expected of a conquering army, so let us consider the cooler and more considered behavior of the political leadership. In Japan, “some 5,700 Japanese were tried on conventional war crimes charges, and 920 of these men were executed” while “an administrative purge removed over 200,000 Japanese at least temporarily from political activity.”[24](../Text/Notes.html#Chapter2-FN24) Some of the trials were sheer farce; for example, the trial and execution of General Yamashita for crimes committed by troops over which he had no control whatsoever.[25](../Text/Notes.html#Chapter2-FN25) The principles on which the prosecution was based were outlined by Justice Robert H. Jackson in these terms: “our test of what legally is crime gives recognition to those things which fundamentally outraged the conscience of the American people...I believe that those instincts of our people were right and they should guide us as the fundamental tests of criminality.”[26](../Text/Notes.html#Chapter2-FN26) As Minnear comments, “Law so defined seems little different from the Nazi ‘law’ that had aroused so much antagonism among the Allies,” specifically, the Nazi law of 1935 which held that “whoever commits an action which the law declares to be punishable or which is deserving of punishment according to the fundamental idea of a penal law and the sound perception of the people shall he punished.”






“None of the defendants at Tokyo was accused of having personally committed an atrocity,” Minnear writes, but only of having conspired to authorize such crimes or having failed to stop them, and no evidence was submitted that such crimes were government policy (66f.). One Japanese general was executed on the sole grounds that he had failed “to take adequate steps to secure the observance and prevent breaches of conventions and laws of war in respect of prisoners of war and civilian internees.”[27](../Text/Notes.html#Chapter2-FN27) Consider the fate of the U.S. military and political leadership if such standards were applied in the case of Vietnam. The sentence, in this case, was based on a split decision with a majority of 6 of 11 Justices favoring the sentence of hanging that was administered. On the other executions, the Court was split 7 to 4. The U.S. Uniform Code of Military Justice requires unanimity of a court-martial for sentencing to death and a ¾ majority for confinement for more than ten years (Minnear, 91-2).






Keeping solely to the Tokyo Tribunal itself, of the 25 defendants, seven were condemned to death by hanging, two died during the trial, and six more died in prison (31, 172); Prime Minister Konoe committed suicide when he learned of his arrest (105). Of the many procedural inadequacies of the Tribunal, perhaps the most striking is that no neutral Justices were appointed (let alone Japanese), but only representatives of countries allied against Japan, including one Justice who was a survivor of the Bataan death march (76-82).






Acts committed by the anti-Japanese alliance were excluded from consideration at the Tribunal. As Indian Justice Pal commented in his impressive dissent, “When the conduct of the nations is taken into account the law will perhaps be found to be that only a lost war is a crime.”[28](../Text/Notes.html#Chapter2-FN28) There was, for example, no reference to the atomic bombing of Hiroshima and Nagasaki—though as Pal correctly remarked, “Nothing like this could be traced to the credit of the present accused,” and as Justice Röling of the Netherlands commented some years later: “From the Second World War above all two things are remembered: the German gas chambers and the American atomic bombings” (Minnear, 101).






Though it is difficult to assign a measure, nevertheless it seems likely that Western racism was a factor, over and above the general submissiveness to the state propaganda system, in permitting the atomic bombing to be so quickly forgotten, or more accurately, unheeded in the West. One of the leading statesmen of the era, Canadian Prime Minister Mackenzie King of the Liberal Party, made the following entry in his diary on August 6, 1945: “It is fortunate that the use of the bomb should have been upon the Japanese rather than upon the white races of Europe.” Such sentiments are, of course, not to be publicly expressed. In fact, in The Mackenzie King Record, the 1968 biographical project of King’s literary executors, the sentence is excised, though the diary was kept as a record to “recount and explain” the conduct of public affairs and is described in the official Canadian military history as “the most important single political document in twentieth-century Canadian history.”[29](../Text/Notes.html#Chapter2-FN29) The same distinguished statesman also urged in 1944 that all “disloyal” Japanese-Canadians be deported “as soon as physically possible,” while those adjudged “loyal” should be dispersed. Though civil libertarian pressures in Canada prevented the enactment of this proposal or other racist measures of the sort instituted against the local population of Japanese origin in the United States, nevertheless “over 4,000 persons, many of them Canadian since birth, were shipped to devastated Japan in 1946-1947.”[30](../Text/Notes.html#Chapter2-FN30) Such vengeful and racist acts in a tolerant and wealthy Western country untouched by Japanese aggression are not recalled, needless to say, when the time comes to raise a chorus of protest—justified on libertarian and humanist grounds that are foreign to Western thought and practice—against expulsions and oppression in postwar Indochina.






The deep moral flaw of the Tokyo Tribunal, noted above, also undermines the moral basis for the Nuremberg Tribunal, which administered 12 death sentences to Nazi war criminals. The chief counsel for the prosecution at Nuremberg, Telford Taylor, has observed that “since both sides had played the terrible game of urban destruction—the Allies far more successfully—there was no basis for criminal charges against Germans and Japanese, and in fact no such charges were brought.”[31](../Text/Notes.html#Chapter2-FN31) The Nuremberg Tribunal was empowered “to try and punish persons who, acting in the interests of the European Axis countries...committed any of the following crimes.”[32](../Text/Notes.html#Chapter2-FN32) The operational definition of “war crime” is: criminal act committed by the defeated enemy and not (allegedly) by the victor. Only a lost war is a crime.






Apart from the major war crimes trial, the Allies conducted a “denazification” procedure in occupied Germany which was described by General Lucius Clay, who was responsible for the U.S. zone, as “perhaps, the most extensive legal procedure the world had ever witnessed.” He reports that “in the U.S. zone alone more than 13 million persons had been involved, of whom three and two-thirds million were found chargeable, and of these some 800,000 persons were made subject to penalty for their party affiliations or actions.”[33](../Text/Notes.html#Chapter2-FN33) This procedure was regarded as an indication of the deep moral principle of the victors.






The same is true of current reaction to the Allied treatment of captured POWs. In Britain, there were some 400,000 German POWs. By Autumn 1944 they were being used for forced labor as a form of “reparations.” Repatriation began in September 1946 and continued until the summer of 1948, over three years after the German surrender. After the war, too, the POWs spent the harsh winter of 1945-1946 in tents in violation of the 1929 Geneva Convention. The POWs referred to themselves as “slave labour,” with some justice. A “stereotype” was “heard among the POW that ‘a venomous re-education drove back to National Socialism many a man who had honestly been seeking a new way of life.’ The stereotype endured in varying measure for the whole of captivity and, as an expression of resentment, beyond it.” The psychological state of the POWs changed “from the anxiety and hope of the first half of 1946 to the depression and nihilism of 1948,” according to Henry Faulk.[34](../Text/Notes.html#Chapter2-FN34)






The British government, naturally, saw matters in a different light. The general aims of the “re-education” program, Faulk writes, were “to present the British Commonwealth of Nations as an example of a democratic community in action, while avoiding the projection of Britain as a model to be slavishly copied.” Faulk does not explore the choice of representatives of this “democratic community” as “guest lecturers.” Presumably they did not include, for example, Jawaharlal Nehru, who observed that the ideology of British rule in India “was that of the herrenvolk and the Master Race,” an idea that is “inherent in imperialism” and “was proclaimed in unambiguous language by those in authority” and put into practice as “Indians as individuals were subjected to insult, humiliation, and contemptuous treatment.”[35](../Text/Notes.html#Chapter2-FN35)






In the case of Britain, the abuse of German prisoners can be explained, if not justified, as revenge for the terror Britain suffered at their hands (residents of Hamburg and Dresden might have harbored similar thoughts). But no such justification can be brought to bear on the treatment of German POWs by the United States. Judith Gansberg, in a study based on recently declassified documents, provides an awed and admiring account of an “unusual plan to reeducate the 372,000 German prisoners.”[36](../Text/Notes.html#Chapter2-FN36) “The reeducation program,” she notes, “adopted at the urging of Eleanor Roosevelt, was undoubtedly a violation of the spirit of the Geneva Convention’s provisions against denationalization. It was a massive multimedia effort to bring about a democratic trend among the prisoners which would not only change their views but could also provide a vanguard for redirecting postwar Germany” and “to return the men to Christian practices”(2, 110-1). It was run by a “small group of talented and dedicated men” and was a “unique experiment in political reprogramming” (6). Only “the most incorrigible Nazis—less than 10 percent—never succumbed to any efforts to reeducate them”(99). There were some difficulties in reeducation; for example, some POWs were appalled by the treatment of Blacks in the United States. But in general it was regarded as a smashing success.






The general tone is conveyed in a commencement address to the prisoners by Professor Howard Mumford Jones of Harvard:






It may seem odd to appeal to the spirit of a prison camp and of a military installation, but what is the idea behind Fort Kearney unless it is the notion of human dignity and of the brotherhood of man? When therefore I say to you it is my hope, as it is the hope of other members of this faculty, of officers of this post, and of your fellow prisoners...that the spirit of Fort Kearney may go with you wherever you are, I speak for these, your associates, as well as for myself, no less than for the American government which has sanctioned this amazing enterprise. May you be each one, a good Christian soldier in the campaign against hatred and ill will. (p. 84)






The first list of names of Fort Kearney prisoners to be repatriated was released in September, 1945 (prisoners remained in the United States until July, 1946). In September, 1944, it was decided that “reeducation” was an inappropriate term. An office memo states that “the terms ‘reeducation’ or ‘reorientation’ of prisoners of war will not be used in referring to the mission of this Branch. The term ‘I.D. Program’ (Intellectual Diversion) will be used whenever reference is made to the program” (p. 89).






Reeducation and intellectual diversion were not the only devices used to return the prisoners to Christian ways. A field intelligence officer “admitted having shot a German captive in the head to induce his comrades to talk. But that was only a first step...” The British beat prisoners to get information. “Many stories of brutality were true” in U.S. POW camps. Prisoners were starved into collapse, etc., but no official actions were taken to modify these practices. In July, 1945 a guard strafed POW tents, killing 8, among other atrocities.[37](../Text/Notes.html#Chapter2-FN37)






In the United States, as in Britain, prisoners were used for forced labor. Truman delayed repatriation for 60 days for POWs essential for the harvest. POWs performed 20 million man-days of work on army posts and 10 million for contract employers (farm work, lumber industry, etc.). Some were assigned to work at the Chemical Warfare Center at the Edgewood Arsenal in Maryland (pp. 34-7).






The “amazing enterprise” of “reeducation” (rather: Intellectual Diversion) has evoked much admiration in the United States. Reviewing Gansberg’s book in the New York Times (1 February, 1978), Thomas Lask writes that “it was a startlingly original notion to work at converting German thinking, and no praise is too high for those United States Army men and educators who conceived and carried out the effort.” He notes that the operation had to be carried out in secret—“the Army did not want American POW’s in Germany to be subjected to the same treatment.” The book has some flaws, Lask believes: it did not, for example, explore “American innocence” sufficiently. But in general, the reeducation program must be regarded as one of the marvels of American humanitarianism.






To appreciate the quite amazing hypocrisy of this reaction—indeed, of the book itself—it is necessary to turn to the flood of denunciations of the barbarity of the Vietnamese in conducting a program of “reeducation” (which includes rehabilitation of the hundreds of thousands of drug addicts, prostitutes, torturers, and other debris left by the U.S. war), during exactly the same period. Evidently, it all depends on whose ox is being gored.






The aftermath of World War II was not limited to the pleasures of military occupation—pillage, rape, and murder—judicial murder, “Intellectual Diversion,” years of forced labor, occasional killings of POWs in prison camps, massive purges, and other such humane practices for the defeated; and massacres, union-busting by gangsters, and so on, for victors with the wrong politics as determined by their liberators. It also included direct retribution against collaborators with the Nazis on a scale that is not appreciated in the West, though it has been well-documented. French historian of the resistance Robert Aron is one of those who has honestly faced the grim task of determining the facts.[38](../Text/Notes.html#Chapter2-FN38) He cites police and other reports of murderous reprisals up to “ten months after the Liberation of practically the whole country,” including collective massacres discovered many months after when mass graves were located. Many of the facts are unknown because “the families of the victims had often been terrorized and preferred to conceal their misfortunes rather than go to the authorities.” Aron cites journalists’ figures of 50,000 killed but notes, correctly, that such estimates must be disregarded as “figures adopted lightly in a climate of excitement by which armies in a campaign or frightened civilian populations crystallize their emotions.” He also cites the study of Pleyber-Grandjean (one of the “victims of the Liberation”), “who made an effort to give an objective account of a number of atrocities in Ecrits de Paris. The facts he gives are for the most part exact, but he exaggerates the conclusions he draws from them.” Pleyber-Grandjean estimated the number massacred at seven million—no doubt an exaggeration.






Aron undertook a careful study, basing himself in part on detailed information provided by the French gendarmerie. He concludes that the number killed in summary executions just prior to or after Liberation must be at a “minimum...between thirty and forty thousand”—“Approximately one Frenchman in a thousand was the victim to the excesses committed at the Liberation.” Translating to South Vietnam, where the war was far more brutal and the aggressors and their collaborators exercised incomparably greater violence than the Nazis did in France, we would have some 20,000 murdered at the time of Liberation, or, if we accept the figures of “victims of the Liberation” with the credulity typical of Western commentators in the case of Indochina, about 3 million outright murders. Fortunately, the Vietnamese did not keep to the standards of Western humanism.






We might add that the massacres in France were carried out during a period when General Eisenhower, under a directive from President Roosevelt issued with Churchill’s approval, exercised “supreme authority” in France, and the “ultimate determination of where, when and how civil administration...shall be exercised by French citizens.” The Provisional Government of de Gaulle was not recognized until October, 1944.[39](../Text/Notes.html#Chapter2-FN39)






Imagine that Germany had survived the second World War unconquered, but driven from occupied Europe, still a major world power under the regime that had conducted the war. How would these events in liberated France have been perceived? One can easily guess. The figure of seven million dead would no doubt have become gospel truth—much as Americans and Frenchmen now circulate figures with wild abandon about Indochina, as we shall see—and there would be no limits to the indignation over the barbarism tolerated (or, the claim would be, encouraged) by the U.S. occupying forces that had conquered peaceful France, overthrowing its legitimate government virtually without French assistance. Similarly, we may imagine how an undefeated Japan might react to the spectacle of the annual reenactment of atomic bombing, e.g., at a Texas air show in October, 1977 with a B-29 flown by Paul Tibbets, the retired Air Force general who dropped the atom bomb on Hiroshima, before an admiring audience of 20,000.[40](../Text/Notes.html#Chapter2-FN40) Perhaps the Germans, in our invented nightmare, would have proposed a reenactment of the second major atrocity that we recall from World War II, according to Justice Röling (cf. p. 37, above).






But Germany was defeated and occupied, so we are spared such venomous hypocrisy.






But even defeated Germany provides some precedents. The Washington Post (10 April, 1977) featured a report from Dachau, which “in its own way is reflective of West German attitudes toward the question of dealing with the Nazi era.” There is, for example, “no mention of the participation of German industry in the use of slave-camp labor. ‘It is a guilt never acknowledged here and rarely spoken about in our history books,’ says Barbara Distel, the Dachau museum director...‘The general attitude really is not to talk about it, to forget about it if possible,’“ she adds, in reference to Dachau. But Germans, even those directly implicated, are quick to concede error, perhaps even “tragic error”: “Under interrogation in captivity Goering said that the liquidation of the Jews was a vast political blunder; many would have made good nationalists and joined in the liquidation of the Communists. If only Hitler had not confused these two issues, he said.”[41](../Text/Notes.html#Chapter2-FN41) And then there is the man known as the “hangman of Lyons,” twice sentenced to death in absentia by French courts for war crimes and now residing in peace in Bolivia, who concedes that “the mass killings of Jews constituted a grave error. Many of us SS officers believed that the Jews could have been put to better use building roads to facilitate the advance of our troops” (New York Times, 18 May, 1975). Not all see error. For example, the chief legal officer of Lower Saxony, who resigned in March, 1978 after the disclosure that in a 1936 doctoral dissertation he had advocated that “only a racially valuable person has the right to exist within the community. Someone who is useless for the community because of his inferiority, or even harmful to it, is to be eliminated...The law as a whole must serve racial development.” But he felt neither “morally, nor politically” obliged to quit (New York Times, 25 March, 1978).






We leave to the reader the choice of appropriate current parallels.






Like virtually all wars of imperial aggression, the war in Indochina was in part a civil war. Substantial Vietnamese forces fought with the French, and the U.S. invaders organized a large and well-equipped—though unwilling and demoralized—army, as well as a network of terror organizations to assist them in destroying local resistance and maintaining the U.S.-imposed civil regime. Civil wars tend to be unusual in the cruelty they evoke. As a final precedent, let us consider a civil war that played a significant role in U.S. and world history, namely, the American revolution, an example that was cited by Bernard Fall in reference to U.S. propaganda about “outside intervention” (by Vietnamese) in support of the South Vietnamese who were being massacred by the U.S. invaders in South Vietnam.[42](../Text/Notes.html#Chapter2-FN42)






The analogy is far from close. The American revolution was minuscule in comparison with the Vietnamese in the degree of force used by those opposed to the revolution, and in the level of internal military and social conflict that developed. “The willingness of both British and rebel leaders to accept, if not always enforce, the fairly humane conventions of eighteenth-century warfare served to mitigate some of the radical effects that civil wars often have on society” (Shy, 200), and obviously the force levels were of vastly different orders of magnitude. In addition, the relative affluence of the American colonies significantly eased the impact of the war, although there was much suffering. Shy writes: “Revolutionary America may have been a middle-class society, happier and more prosperous than any other in its time, but it contained a large and growing number of fairly poor people, and many of them did much of the actual fighting and suffering between 1775 and 1783: A very old story” (173). Furthermore, “one measurable effect of war might have been to widen the gap between richer and poorer Americans” (197).






It is important to recall that the war “remained a civil conflict in America after it had become a struggle between the United States and Great Britain”[43](../Text/Notes.html#Chapter2-FN43)—and between France and Great Britain. “In proportion to population almost as many Americans were engaged in fighting other Americans during the Revolution as did so during the Civil War” (Shy, 183). The fact has seldom been given prominence, in part because so many of the Loyalists simply fled, expecting, as one said, that if the rebels should gain independence “that unfortunate land would be a scene of bloody discord and desolation for ages.”[44](../Text/Notes.html#Chapter2-FN44) “Palmer suggests that, unlike France, the American counterrevolutionary refugees never returned, creating an illusion of tranquility and unity in the postwar Republic.”[45](../Text/Notes.html#Chapter2-FN45) Van Doren summarizes the exodus as follows:






There are no accurate figures as to how many persons including women and children left the United States on account of loyalty to the British Empire, but it may have been as high as 100,000, of whom 35,000 may have gone from New York alone...The expulsion was so thorough that the next generation of Americans, with few former loyalists as reminders, almost forgot the civil aspects of the war and came to think of it as a war solely against England. The loyalists disappeared from American history, at least from ordinary knowledge of it [until the 20th century] (433).






Recall that the white population of the United States was then about two and a half million, and that “at least a fifth of the white population—a half-million people—behaved in ways that enable us to identify them as Loyalist.”[46](../Text/Notes.html#Chapter2-FN46) Comparative figures for South Vietnam would be about 4 million supporters of the United States and 800,000 refugees fleeing the victors. Comparative figures for all of Vietnam would double these numbers, approximately.






During the war, thousands of Loyalists escaped with the British when they evacuated some area, most coming to live in New York “in swarming desperation” (Van Doren, 12-13). Later, tens of thousands fled with the British, including “ragged unpaid American soldiers drifting down the Hudson Valley to sign on as sailors in the ships which were evacuating British forces”(Shy, 17). “Genuine support for the war appears to have declined” from 1775, Shy writes, as people “grew weary of being bullied by local committees of safety, by corrupt deputy assistant commissaries of supply, and by bands of ragged strangers with guns in their hands calling themselves soldiers of the Revolution,” and “got angry when British or Hessian or Tory troops misbehaved...The years from 1776 to 1782 might indeed be recounted as horror stories of terrorism, rapacity, mendacity, and cowardice, not to blame our ancestors for these things, but to remind us what a war fought by the weak must look like” (Shy, 13f.).






Both Loyalists and rebels “gave credit and currency to stories of inhuman deeds done by either to the other,” and the Loyalists argued “that the American governments were more oppressive than the British had ever been” (Van Doren, 120). In particular, the British “had frequently upheld the rights of the Indians against encroaching American settlers” (ibid., 120), one reason why many Indian tribes supported the British, as did many Blacks, recognizing what lay ahead for them if the rebels proved victorious.[47](../Text/Notes.html#Chapter2-FN47) In areas where the British “hardly appeared or not at all,” “Tories either ran away, kept quiet, even serving in the rebel armies, or occasionally took a brave but hopeless stand against Revolutionary committees and their gunmen” (Shy, 178). Meanwhile, at home, the British government attempted “to justify a long expensive war to an unhappy public on the ground that the king had a solemn commitment to defend his numerous American supporters against a rebel bloodbath” (Shy, 185). How familiar it all sounds.






Some of the most graphic accounts of the nature of the civil conflict are found in the letters of General Nathanael Greene, who commanded the southern Continental Army from 1780 to 1783.[48](../Text/Notes.html#Chapter2-FN48)






Greene wrote:






...the whigs and tories pursue one another with the most relentless fury killing and destroying each other whenever they meet. Indeed, a great part of this country is already laid waste and in the utmost danger of becoming a desert. The great bodies of militia that have been in service this year employed against the enemy and in quelling the tories have almost laid waste the country and so corrupted the principles of the people that they think of nothing but plundering one another...The country is full of little armed parties who follow their resentments with little less than savage fury...[the South is] still torn to pieces by little parties of disaffected who elude all search and conceal themselves in the thickets and swamps from the most diligent pursuit and issue forth from these hidden recesses committing the most horrid murders and plunder and lay waste the country (pp. 294-5).






Greene employed terrorism both to improve the morale of his supporters and to frighten the “disaffected.” He told his subordinate, General Thomas Sumter, that partisans were “to strike terror into our enemies and give spirit to our friends” (308). An example was a successful raid that Greene described to Thomas Jefferson as follows:






They made a dreadful carnage of them, upwards on one-hundred were killed and most of the rest cut to pieces. It has had a very happy effect on those disaffected persons of which there are too many in this country (p. 308).






But Greene also recognized that terror was a dubious tactic. In 1781 he outlined a new strategy to Sumter in the following terms:






Don’t spare any pains to take off the tories from the British interest for tho we have great reason to hate them and vengeance would dictate one universal slaughter yet when we consider how many of our good people must fall a sacrifice in doing it we shall find it will be more for our interest to forgive than to persecute. This was always my opinion and if the war continues in this country, unless we can detach the people from the British interest we shall feel more inconveniences from them than from all the British army. Indeed we do now (p. 310).






Loyalist sympathies were sufficiently strong so that a British secret agent expressed his conviction that the British could raise a Provincial army strong enough to defeat Washington, whose troops were not, “as has been represented, a respectable body of yeomanry...but a contemptible band of vagrants, deserters, and thieves,” mainly Irish (Van Doren, 110). The British did attempt “Americanization” of the war in the latter stages, in part because of the “unhappy public” at home (Shy, 185). The secret agent’s judgment might have proven valid had it not been for the French intervention supporting the insurgency—what would now be called “terrorist bands.” As it was, “New York alone furnished about 15,000 men to the British army and navy, and over 8,000 loyalist militia.” With the contribution of the other colonies, “we may safely state that 50,000 soldiers, either regular or militia, were drawn into the service of Great Britain from her American sympathizers” (Van Tyne, 182-3).






During the war, the “persecuted tories had a sanctuary” in New York, to which they fled “from every colony...by boat, on foot, in carriage or on horse, ready to thank God when they had passed the British lines, and had left behind them the din of persecution,” including tarring and feathering, “hoisting the victim upon a liberty pole,” forced oaths of loyalty, jailing for long periods without trial, confiscation of lands, and other forms of oppression and terror. Many were prevented from fleeing, others driven out. “The records kept by the committees of safety prove, beyond the possibility of doubt, the Tory charges that committee rule was despotic and tyrannous,” while “from the Tory pen we have a picture of an inexorable reign of terror” (Van Tyne, pp. 128, 61, 66, 230). While few were actually killed, many were tried and sentenced—Washington noted in a letter that “one or two have done what a great number ought to have done long ago, commit suicide”—referring to these “miserable set of beings,” “these wretched creatures” who retained their loyalty to the crown (ibid., p. 57).[49](../Text/Notes.html#Chapter2-FN49)






Many fled abroad to await the outcome of the war, choosing to commit themselves “to the mercy of the waves at a tempestuous season rather than meet their offending countrymen,” as one Tory wrote (Van Tyne, 57). The largest fleet ever seen in America, more than 170 sail, departed in March, “the most tempestuous month of the year on the American coast,” fearing that “without a miracle the wretched fleet must be dispersed and lost...on their top-heavy decks were huddled a wretched throng of soldiers and refugees...It was impossible, thought one of them, that more events could concur to render their distress complete, and their ruin almost inevitable” (ibid., 58). “Sir Henry Clinton wrote that nothing distressed him so much as the applications he hourly received from great numbers of refugees who crowded to New York from every quarter of America. Many, he said, had been reduced from affluent circumstances to the utmost penury by their attachment to the king” (ibid., 254). As the British were withdrawn, more refugees fled, primarily to British American territories, including Nova Scotia, which one described as “the most inhospitable clime that ever mortal set foot on” (ibid., 294). There, “women, delicately reared, cared for their infants beneath canvas tents, rendered habitable only by the banks of snow which lay six feet deep” while “strong and proud men wept like children, and lay down in their snow-bound tents to die” (ibid., 305).






But the “boat people” were perhaps more fortunate than those who remained. In violation of the treaty with the British and in spite of the recommendation of Congress, after the war “confiscation still went on actively; governors of the states were urged to exchange lists of the proscribed persons, that no Tory might find a resting place in the United States; and in nearly every state they were disfranchised, while in many localities they were tarred and feathered, driven from town and warned never to return,” or sometimes murdered (ibid., 295).






One can imagine what a British Henry Kamm[50](../Text/Notes.html#Chapter2-FN50) would have made of all of this. We also note that these aspects of the Revolutionary War are not exactly centerpieces of school textbooks describing the struggle of “Americans” for freedom from onerous foreign rule.






We stress again that the analogy to Indochina, which will be obvious to any reader of the daily press, should not be drawn too closely. There are many crucial points of difference. The American rebels, as noted, were supported—indeed far outnumbered—by the military forces of France, while no foreign troops were engaged on the side of the Vietnamese. The force brought to bear by the British and their local allies was infinitesimal as compared with Westmoreland’s killing machine, and in fact the civil conflict enflamed by foreign aggression from 1946 was also, naturally, far more fierce, given the nature of the intervention by France and the United States (and in the early stages, Britain, which prepared the way for the return of French imperialism). Vietnam is far poorer than the American colonies, which were already ranked high among the more affluent societies in the world, and its foreign enemy vastly richer and more powerful, as well as incomparably more savage. Nor is there in Indochina anything comparable to the exploitation of Blacks and persecution of native Americans. Despite these and other crucial differences, it is nevertheless interesting to recall this example of a civil conflict enmeshed in a struggle for national independence, and its consequences for the victims—Loyalists, Blacks and Native Americans.[51](../Text/Notes.html#Chapter2-FN51)






To conclude, we note that it is standard in later scholarly work in American history to recount, in part at least, the torment of Native Americans and Blacks at the hands of the victors in the revolutionary struggle, though it is equally common to describe this oppression, far from ended, as an unfortunate “exception” to the general humanism of the American experience. In a review of a book that is “rooted in the familiar nationalistic strains of Daniel Boorstin’s view of U.S. political history,” Clarence Karier makes the following apt comment:






For the Irish who died building the railroads and canals in the East, the children who died in the coal mines of Pennsylvania, the women who died chained to their machines in factories, the Polish laborers burned to death in the steel mills of Gary, the Indians wasted by the Gatling gun in the West, or the slave who felt the white man’s lash, Cremin enters the “caveat” that these were “inexcusable omissions.” When, one might ask, do these “inexcusable omissions” cease to be “omissions” and when do they become an organic part of American history?[52](../Text/Notes.html#Chapter2-FN52)






This point might be borne in mind, along with the historical background just recounted, when we turn to the question of how the Indochinese peoples are facing their incomparably more severe problems, unrelated to anything in the U.S. experience not only because of the destructive impact of colonialism and the absence of the immense natural advantages of the American colonists, but also because they have been subjected to murderous destruction, the likes of which the world has rarely seen, on the part of those who now feel no shame when they let the words “human rights” fall from their lips.






Many other examples of a similar sort may be cited. The historical record serves as a kind of “base line” against which we may evaluate events in postwar Indochina. To repeat, while Western propaganda attributes the suffering of the people of Indochina—those who flee the war or its aftermath, those who are persecuted within, and the vast majority who are attempting to reconstruct some sort of viable existence from the wreckage—to the evil effects of Communist ideology or the generally “uncivilized” character of the Third World, which has failed, to our dismay, to absorb Western humanism, an honest historical analysis would proceed quite differently. It would begin by establishing the common practice in comparable situations, then add an enormous increment attributable to the unusual barbarity of the U.S. attack with its legacy of destruction, bitterness and hatred. Atrocities and oppression that exceed this measure might reasonably be attributed to Indochinese communism.






Applying these standards to Vietnam, there seems little doubt that the aftermath of the revolutionary victory has been remarkably free of vengefulness. The same is true in Laos. No doubt Cambodia differs, even when one discounts for the stream of falsification in Western propaganda. Finally, in evaluating these painful and troubled issues, we must bear in mind the long record of atrocity fabrication and the traditional gullibility of the intelligentsia regarding the alleged evil practices of enemies of their own state.




