# Refugees: Indochina and Beyond


We now turn to the central topic of this volume, the nature of the evidence that has been presented in the West with regard to postwar Indochina, the uses to which such evidence is being put, and the significance of these facts.






One major focus of concern and outrage in the West has been the continuing flight of refugees from Indochina. In a review that is unusual in its honesty, the London Economist reports that:






16,000 boat people [from Vietnam] have landed in neighbouring south-east Asian countries so far this year; the monthly rate has increased from 980 in December to 6,000 in May. Partly because of the wide publicity these doughty seafarers have received, partly because refugees from Vietnam tend to have other advantages (gold bars, skills, relatives in America), a remarkable high proportion of the Vietnamese who have escaped since the spring of 1975 have been permanently resettled. Only 12,000 boat people (10,000 of them in Malaysia) and a few thousand other Vietnamese are currently waiting for a place to go...Thailand, by geographical ill-fortune, is still today the largest repository of unsettled Indochinese refugees, with 100,000 people registered in refugee camps. The great majority of these—83,500 Laotians and 14,000 Cambodians, who are mostly tribesmen and illiterate farmers—have little chance of moving on.[1](../Text/Notes.html#Chapter3-FN1)






The Economist is certainly correct in adding that “there is room for far more generosity” from the West with regard to these unfortunate victims.






What is unusual about the Economist report is that it is not limited to refugees from postwar Communism, as is the general practice. The Economist observes that “nearly 400,000 people have walked or sailed away from their home countries since the beginning of the year” in Asia[2](../Text/Notes.html#Chapter3-FN2) (far less than Africa, where the same report estimates the number of refugees at 2 million).[3](../Text/Notes.html#Chapter3-FN3) “The biggest single group,” the report continues, are the Muslim Bengali people who have been fleeing from Burma to Bangladesh at the rate of about 2,000 a day. A June 24 report in the Economist estimates their number at 175,000. An earlier report of June 10 reports that they arrive in Bangladesh “bearing gruesome tales of atrocities committed by advancing waves of Burmese soldiers” and that they are being forced off their lands by Buddhist tribesmen.






We learn more about the refugees from Burma elsewhere in the foreign press. Richard Nations reports in the Far Eastern Economic Review (30 June 1978) that 200,000 refugees fled from Burmese terror in two months—a far higher rate than the 2,000 per day estimated by the Economist. During the initial phase of the flight, the rate was 8,000 per day according to “one United Nations veteran of relief operations throughout the world,” who described the camps where they were kept “as absolute death traps—the worst I’ve ever seen,” though there was improvement later. Nations continues: “Refugees tell of atrocities, rape, indiscriminate arrest, desecration of mosques and razing of villages by Burmese soldiers and local Mogh (Arakanese Buddhist) chauvinists,” circumstances far worse than anything reported from Vietnam. William Mattern comments in the same journal that the fate of the “200,000 or more Burmese Muslim refugees now in Bangladesh” can be traced in part to a civil conflict that erupted during World War II, when the British organized the Muslim community to fight the Japanese who were supported by the Burmese Buddhists in the Arakan mountains, leading to “one of the bloodiest communal riots in South Asian annals.”[4](../Text/Notes.html#Chapter3-FN4) By the end of September, only about 250 of the refugees had returned home, according to unofficial reports in Rangoon, even though “in the squalor of the camps on the Bangladesh side, a return to their small farms and shops in Arakan—however impoverished—must have some attraction even for the downtrodden Muslims.” Informed observers believe that “certainly, someone put fear into the hearts of the Muslims of Arakan—and is keeping it there.”[5](../Text/Notes.html#Chapter3-FN5)






These 200,000 refugees of April-May 1978 were not totally ignored in the U.S. press. On May 1, the New York Times devoted 150 words on p. 13 to a report that 70,000 refugees had fled in three weeks, bringing “tales of torture, rape and robbery,” including more than 18,000 in the preceding 24-hour period. They fled despite the efforts by Bangladesh forces to seal the borders and turn back illegal immigrants. “One refugee asserted that the [Burmese] army had launched an operation to clear the border area of the Moslem community that was not originally Burmese.” Brief mention of this vast refugee flow also appears in subsequent stories. Humanitarians concerned with the suffering people of Asia, particularly the refugees from brutal atrocities and oppression, were clearly alerted to the existence of a major disaster, but the response was undetectable.






Returning to the London Economist report of June 17 on refugees, it points out further that 110,000 Chinese residents fled from Vietnam to China after the government cracked down on the black market and other illegal practices and nationalized businesses in the South; ethnic Chinese, the report notes, have been the most frequent “target of local hostility” in Asia, the most extreme example being the massacre in Indonesia in 1965-66.[6](../Text/Notes.html#Chapter3-FN6) Since the fall of Saigon and Phnom Penh, the report continues, more than 200,000 refugees have fled from Indochina to neighboring countries—a substantial number, though, as we have seen, small by such historical standards as the American revolution, both in proportion to the total population and relative to the character of the conflict. In addition, some 150,000 Cambodians, including 20,000 ethnic Chinese, have fled to Vietnam.






The Economist does not mention the refugees who fled from the Philippines to Sabah at an estimated rate of 400 a day, some 140,000 by mid-1977, constituting 14% of the population of the Sabah. The Malaysian government has agreed to allow 90,000 to remain.[7](../Text/Notes.html#Chapter3-FN7) Nor does it discuss the refugees fleeing from Indonesian terror in Timor—or according to the Western-approved version, fleeing from the fierce guerrillas who have “forced them” to live under their control—so that they can be “protected” by the Indonesians (see Volume I, chapter 3, section 4.4).






As for Vietnam, “Most of the refugees appear to come from middle-class backgrounds or better, and they believe, with some justification, that they have the most to lose under communism.”[8](../Text/Notes.html#Chapter3-FN8) “Fear of being punished for past actions or associations seems to be a factor as well” and “officials who have questioned thousands of refugees say that nine out of 10 identify a desire for freedom as the major factor in the decision to abandon their homelands.” Frederic Moritz comments that “the Vietnamese [in Thailand] are largely middle-class businessmen and former low-level employees of the Americans who say that they faced disruption, loss of freedom and income, and possible job discrimination if they had stayed behind. At the least, the Vietnamese refugees were former independent fishermen.” “Vietnamese refugees say those who fail in escape attempts often are punished only mildly with short terms in ‘reeducation camps’ or other less severe measures,” but the Laotian refugees, who “actively fought communist forces for more than a decade in collaboration with the U.S. Central Intelligence Agency,” would presumably “expect far harsher treatment,” long imprisonment or execution. The Cambodians still in camps—over 14,000—“are a mix of farmers, students, military men and minor government officials. Skilled Cambodians such as technicians and physicians or those with money have moved on to be resettled.”[9](../Text/Notes.html#Chapter3-FN9)






A fuller account of refugees in Asia by mid-1978 would include the quarter of a million driven from their homes in West Asia by Israeli troops in March, 1978, after bombing of cities, villages and refugee camps with U.S. cluster bomb units[10](../Text/Notes.html#Chapter3-FN10) and heavy artillery, among other devices, in attacks reminiscent of Vietnam: “concentrated and heavy firepower and air strikes to blow away all before them—be they enemies or civilians—in order to hold down their own casualties,” leaving “a broad path of death and wide-scale destruction” with “hardly a town...left undamaged” and some “all but totally flattened by air strikes and explosive shells”; “the scope and sweep of the damage here makes a mockery of Israeli claims to have staged surgical strikes against Palestinian bases and camps.”[11](../Text/Notes.html#Chapter3-FN11) These quarter-million recall the 700,000 who fled (about half of them expelled, according to conservative estimates by such pro-Israeli scholars as Nadav Safran of Harvard) in 1948, the 400,000 who fled or were expelled in 1967, many of them long after hostilities ceased, the one and a half million driven out of the Suez region by Israeli bombing during the 1970 “war of attrition,” and many others, including the former inhabitants of the Jordan Valley, cleared by force in 1969-70. Apart from those simply expelled by force, as in South Lebanon, there are the many who are escaping from the occupied West Bank, where the rate of emigration sharply increased to more than 17,000 in the past two years.[12](../Text/Notes.html#Chapter3-FN12)






By the latter part of 1978, we may add several hundred thousand Maronites driven from Lebanon by Syrian bombardment, added to the earlier Lebanese Muslim and Palestinian victims of Syrian force as Lebanon is further dismembered by civil strife and foreign invasion and intrigue too complex and remote from our focus here to receive a proper discussion. The Economist (7 October 1978) reports a Lebanese government estimate of 600,000 exiles, about half of them Maronite, in addition to hundreds of thousands of refugees within Lebanon.






The refugees in Asia and Africa by no means exhaust the grim story. In Volume I, we discussed the massive flight from U.S.-backed terror in Latin America: an estimated half million from Uruguay, perhaps 700,000 from Bolivia, many more from the other subfascist states. Keeping just to 1978, in September more than 16,000 refugees fled Somoza’s terror to neighboring Honduras and Costa Rica, joining the 100,000 Nicaraguan exiles already living in Costa Rica, earlier victims of oppression in a country long favored with the benign attention of the United States.[13](../Text/Notes.html#Chapter3-FN13) These refugees have evoked no more interest in the United States than the hundreds of thousands fleeing Burma, the Philippines, Zaire, or other non-Communist states. Attention is reserved for refugees from Indochina. Editors and columnists plead for greater concern and aid for refugees and international condemnation of the repressive policies responsible for their flight, referring solely to the refugees from Indochina—and not calling for measures to alleviate the harsh conditions in Indochina that are surely a direct reason for the flight of refugees and also a factor in the institution of the repressive policies that so concern U.S. humanitarians. Discussion of the U.S. contribution to the plight of the refugees or of the vast flow of refugees elsewhere would simply not serve the needs of Western ideology at this moment. Consequently, these topics merit no comment or concern. The Social Democrats, USA, publish full-page advertisements in U.S. journals calling for “compassionate action” to help the Indochinese refugees, signed by a wide range of people including some of the most extreme and vocal apologists for U.S. aggression and terror in Indochina. Their compassion, however, is restricted to “Indochinese Refugees” and the statement makes no mention of any “compassionate action” to help overcome the consequences of the U.S. war.






By late 1978, the refugee flow from Indochina had reached quite substantial proportions. According to the UN High Commissioner on Refugees, over 71,000 had successfully escaped from Vietnam by sea since April 1975[14](../Text/Notes.html#Chapter3-FN14) and many more undoubtedly died in escape attempts, in addition to the ethnic Chinese who fled by land. In a speech before the Boston World Affairs Council, Richard Holbrooke of the State Department reported that in October 1978 “a record 10,000 ‘boat people’ landed in Southeast Asian countries. In the first two weeks of November an additional 10,000 landed in Malaysia alone...fleeing unbearable conditions in their home countries.” This “dramatic flow of refugees,” most of them ethnic Chinese, “could be highly damaging to the emerging stability of Southeast Asia.”[15](../Text/Notes.html#Chapter3-FN15) Apparently the flight of 200,000 Burmese Muslims to Bangladesh in April-June 1978, more than 18,000 in a single day, was not “dramatic” enough to have reached the attention of the Assistant Secretary of State for East Asian and Pacific Affairs, just as the flight of 140,000 Filipinos failed to reach this threshold. Among the refugees in Latin America there are also “boat people.” For example, 1,000 refugees from Haiti who “voyaged 800 miles in flimsy sailboats to Florida, where they received harsh and discriminatory treatment by Immigration and State Department officials.”[16](../Text/Notes.html#Chapter3-FN16) These refugees fled from oppression and torture in the subfascist U.S. client with the lowest living standards in the hemisphere.[17](../Text/Notes.html#Chapter3-FN17) “No rationale has been offered,” Gollobin continues, for treating the Haitian “boat people” differently from the Vietnamese and Cubans “who have been given asylum as a group.” The rationale, however, is obvious enough. As in the case of 140,000 refugees from the Philippines or a quarter of a million refugees from Southern Lebanon, the Haitians are not fleeing from “Communist tyranny,” but rather from “unbearable conditions” in a client state, or the acts of a friendly ally, and therefore merit no special concern.






In addition to their unwise choice of oppressor, the Haitian boat people have another strike against them. The New York Times reports that there are some 15,000 Haitians in the Bahamas seeking refuge in Florida, which has “raised fears here that the poor on other islands in the Caribbean may also risk the dangers of the open sea to get a legal foothold in Florida.” This is another reason why “only 26 Haitians have been granted asylum since 1972, the year when the rotting fishing boats made their first landings on Florida beaches.”[18](../Text/Notes.html#Chapter3-FN18)






Fear of inundation by the poor and oppressed of the world can occasionally be relaxed, for example, when seasonal workers are needed in the Southwest or when some political capital can be gained by a demonstration of our humanitarian concern for victims of Communist tyranny—particularly when they are “orphans” (see chapter 2, note 17). But the Haitian boat people do not meet these conditions: “Now, as a signal to the rest of the world that just being poor is not enough reason to sneak into the U.S., federal officials are beginning a crackdown aimed at catching Haitians who have entered the U.S. illegally and sending them home” to the “poverty and repression” from which they have escaped.[19](../Text/Notes.html#Chapter3-FN19) Some 1,200 arrived from November 1977 to mid-1978, including “boat people” who spent weeks at sea in sinking craft and were arrested on their arrival—if they made it.[20](../Text/Notes.html#Chapter3-FN20) But the State Department denies that they will be in any danger if returned to Haiti, and a spokesman for the U.S. Immigration and Naturalization Services cited by Robert Press assures us that “the entire effort is being made with full regard to the administration policy of human rights”—which is true enough, though not exactly in the sense he was trying to convey.[21](../Text/Notes.html#Chapter3-FN21) Temporary work permits that had been granted for 3-4,000 Haitians are being revoked. Some officials and one church in Miami, Robert Press reports, “have charged the U.S. with ‘racism’ for turning its back on the needs of the Haitians—a black people.” The fact that their oppressor is a U.S. client state is, however, sufficient to explain their treatment.






The ironies have not gone entirely unnoticed in the press. Karen DeYoung comments that “while the United States is acting to admit more Indochinese immigrants who wash ashore in Asia, it is attempting to deport other thousands of ‘boat people’ who have landed on southern Florida beaches from Haiti” (Washington Post, 22 December 1978). She notes that “the issue of the Haitian boat people has been simmering since 1972,” though “it was not until a 1977 Supreme Court case, however, that the Justice Department recognized the rights of the Haitians to INS interviews to judge their political asylum claims.” But the decision was virtually irrelevant. The INS Commissioner said in an interview that “practically none” of the 9,000 Haitians whose cases were being reviewed in Miami in December 1978 had been adjudged as meriting political asylum. Since the INS is no longer issuing work permits, “some Haitians are once again being thrown into jail while awaiting processing.” A committee of civil rights lawyers charged that “the INS rarely bothers to find out if the refugees are likely to be persecuted if they are forced to return to Haiti” (and, of course, no questions are raised in the case of flight from a Communist state), and “deportation proceedings are initiated even before an interview is scheduled, under the 1977 Justice decision, to hear their claims for asylum.” The group “charged that the INS, in response to the vast and unexpired numbers of poor illegal Haitians, decided to begin throwing them out—primarily to avoid setting an encouraging precedent for other Third World illegals.” The London Economist, estimating the number of Haitians illegally in the United States at 30,000, most of them “boat people,” added that “as many as 150 Haitians are being dealt with each day [by INS], with only one or two minutes for each case to be heard,” while “spokesmen for the Haitian community in southern Florida wonder out loud why Haitians are not accorded the same treatment as thousands of Cubans and Vietnamese” (30 December, 1979).






The treatment of refugees in the mass media and by U.S. official action seems to depend, once again, on political-economic-ideological, rather than human rights considerations. The earlier classification of terror used in Volume I is fully applicable to the refugees as well: (1) benign (e.g., Burma, where no one cares); (2) constructive (e.g., Latin America, where the flow stems from actions serviceable to U.S. interests); (3) nefarious (Indochina, where the blame can be placed on the evils of Communism—overlooking the insignificant matter of the legacy of U.S. intervention). Refugees of the first and second categories can be shipped back to tyranny or left to rot in oblivion wherever they may land (as long as it is not here). But refugees of the third category call forth stirring cries of indignation, editorial denunciation, passionate speeches in the halls of Congress, outraged protest from spokesmen for human rights, and moving words—rarely deeds—of compassion in keeping with the lofty traditions of Western humanism.






In an editorial entitled “The Indochina Debt that Lingers,” the New York Times writes:






The case for American help to the refugees of Indochina continues to be self-evident. After our involvement in Southeast Asia, no debate over who owes whom how much can be allowed to obscure the worst horrors experienced by many of those in flight.






The Times recognizes no “case for American help” to the many hundreds of thousands of refugees elsewhere in Southeast Asia and beyond—indeed, one could hardly know of their existence from the pages of America’s leading newspaper—and most remarkably, recognizes no debt to the victims of U.S. barbarism who remain in their ravaged lands and who vastly outnumber the refugees. For the editors of the Times, the efforts of the Indochinese governments to rebuild are the subject only for censure, because of the suffering their people endure—a sure proof of Communist iniquity. The remark in the editorial about “debate over who owes whom how much” is, perhaps, an oblique reference to one of the sayings of President Carter, who, in the midst of a sermon on human rights, was asked by a journalist about U.S. responsibility to the Vietnamese. We owe them no debt, the great humanitarian responded, because “the destruction was mutual,” as a tour through the bombed out ruins of San Francisco and the Georgia countryside will reveal.[22](../Text/Notes.html#Chapter3-FN22) While this amazing statement was deemed worthy of no commentary in the Free Press, it is possible that it rankles a little at least.






We have already discussed the intellectual and moral standards by which the honesty of protest over human rights violations and concern for their victims should be judged.[23](../Text/Notes.html#Chapter3-FN23) Applying such standards, U.S. citizens concerned over the fate of refugees should distribute their efforts in accordance with the potential impact in relieving human misery. A refugee from Vietnam is no more or less worthy of concern, assistance, or admission to the United States than a refugee from Zaire, Burma, the Philippines, or Haiti. Articulate protest over the actions of U.S. clients such as Marcos or Suharto is far more significant in human terms—that is, in terms of potential benefit for victims—hence far more obligatory on grounds of moral principle than protest over acts or conditions in states beyond the reach of U.S. power. What we find, however, is that articulate opinion—at least, that part that is able to reach more than a tiny segment of the public—is focused almost exclusively on victims of Communist oppression, a concept that includes the rigors of life amidst the ruins, and is careful to evade the question of actions that would alleviate the conditions that are a primary cause for the flight of the refugees.






The New York Times has assigned one correspondent, Henry Kamm, to virtually full time coverage of the misery of postwar Indochina, though others too report frequently on this topic. No comparable concern is shown outside of Indochina. “The Pulitzer Prize for international reporting was won by Henry Kamm, chief Asian diplomatic correspondent for the New York Times, for his articles on the plight of the so-called ‘boat-people,’ war refugees from Indo-China.”[24](../Text/Notes.html#Chapter3-FN24) No such prize is, or will be offered for studies of the misery of refugees (or those not lucky enough to escape) from U.S. client states, or from countries such as Burma that have not been so ignoble as to defend themselves successfully from U.S. invasion. In fact, the Pulitzer Prize jury had recommended Les Payne of Newsday for the prize in international reporting for a series of articles on conditions in South Africa, but “the winner chosen by the [advisory] board was Henry Kamm of the New York Times, whose articles on Vietnamese refugees had been the jury’s fourth choice,’’ we learn in a brief AP report carried by the New York Times on April 22.[25](../Text/Notes.html#Chapter3-FN25) The Pulitzer Prize advisory board is, evidently, more finely tuned to the needs of contemporary ideology than the professional jurors.






In sum, the United States ought to have a real concern for the peoples of Indochina, victims of a long and agonizing U.S.-sponsored cataclysm. But as this concern has been selectively exhibited in the postwar period, the cruelties and hypocrisies of the entire Vietnam war intervention display themselves in new form. The main victims, the bulk of the rural population who remain in Indochina, are ignored, and the concern for refugees is so intertwined with ideological warfare and a rewriting of history that the humanitarianism is once again shown to be hopelessly compromised by political interests. The ghastly episode of the Vietnamese “orphans,” discovered at the last moment and spirited out in a brazen effort to gain public support for the war, was, regrettably, a microcosm of the continuing U.S. response to the war victims. The lack of any comparable concern for the vast flow of refugees from terror within the U.S. sphere of influence, or the victims of benign terror, also tells us a great deal about the power of political economy to twist human rights into such shape that its humanistic component is hard to locate.




