# 7 Final Comments {.unnumbered}


We have explored some of the ways in which the propaganda systems of the West, primarily that of the United States, have faced the major tasks noted in chapter 1 of this volume. Not surprisingly, inquiry reveals a highly selective culling of facts and much outright lying. Some areas of the world are almost entirely blacked out, where disclosure of major abuses would disturb both pliable clients and the U.S. economic, military and political interests that find this pliability advantageous. As we have described throughout the two volumes, the first principle of the Free Press is the averting of the eyes from benign or constructive terror, along with a general avoidance of invidious language and a sympathetic understanding for the difficult problems faced by the terrorizing elites backed by the United States. In sharp contrast, countries that ordinarily evoke minimal Western interest are thrust into the limelight when "enemy" terror and the evils of Communism can be revealed, and other useful lessons drawn. Thus the second principle of the Free Press is the intense and dedicated search for nefarious terror, which can be brought into focus without giving offense to any important groups and which contributes to domestic ideological mobilization.




Further devices used in handling nefarious terror, as we have described, include the stripping away of historical context, fabrication, and myth creation. Useful myths, once successfully instituted, are virtually immune to correction. In focusing on refugees fleeing from Indochina and the prevailing harsh conditions there, the Western media employ a third principle of the Free Press, namely, "agent transference." That is, the critical role of the United States in maintaining internecine conflict from 1954, and its more direct shattering of the Indochinese societies and their economic foundations, is acknowledged only occasionally and as an afterthought. The only "agents" to whom responsibility is indignantly attributed for the suffering in Indochina are the new regimes that came into power in a presumably normal environment in 1975. Death and suffering from malnutrition and disease in societies brought to ruin by U.S. intervention are displayed as proof of the evil nature of Communism. Meanwhile, in the U.S. sphere of influence working conditions of extraordinary severity, massive dispossession of the peasantry, child labor, near slavery, starvation in the midst of rapid economic "growth," and similar concomitants of development in accord with the Free World model are, if noted at all, dismissed as an unfortunate element of the process of modernization. And the hundreds of thousands of refugees from Latin American subfascism, or the plight of the victims of Indonesian aggression in East Timor or other benign and constructive terror in Southeast Asia and elsewhere, and the causes of their plight, are studiously ignored, in recognition of the friendly client status of the official terrorists and the absence of any useful lessons to be drawn from their depredations.



There are further and more general aims to be served by the extensive effort to dispel what the Wall Street Journal calls the "simple-minded myth" that Indochina’s suffering is somehow related to U.S. actions over the past thirty years. For the groups that dominate economic, social, political and intellectual life in the United States, it is a matter of urgency to ensure that no serious challenge is raised to their predominant role, either in ideology or in practice. While mild social reforms have been introduced in the United States, others now conventional in Western Europe (e.g., national health insurance, minimal "worker participation" in industry, etc.) have been effectively resisted here, and there has been remarkable success in designing policy so that state intervention in the economy and social life serves the needs of the wealthy and powerful. We have noted that the absence of an organized left opposition in the United States has facilitated the work of the system of thought control and indoctrination. U.S. ideologists have been unusually successful in conducting "the engineering of consent," a technique of control that substitutes for the use of force in societies with democratic forms.[^ch07-fn001] To serve this end, every effort must be made to discredit what is called "socialism" or "communism." In its more vulgar forms, the argument is that "socialism" or "Marxism" (which in practice means unwelcome social reform, since radical institutional change is hardly an immediate issue) leads inevitably to Gulag. The process of agent transference has made more plausible the doctrine that socialism must inevitably become tyranny. A recent media favorite is the group of Paris "new philosophers," whose congenial message that Marxism equals Gulag has assured them a ready and uncritical audience in the United States and Western Europe. In fact, their critique of authoritarian elements in Marxism-Leninism is remarkably shallow as compared with the long tradition of left-wing libertarian thought that has been virtually ignored in the West, and their enormous success in France reflects in part conditions specific to French intellectual life,[^ch07-fn002] but U.S. media have little care or understanding for any of this. The access of this group to the media and the receptivity to their slogans is a perfect counterpart to the curtain of silence drawn over the proliferating Gulags in the U.S. sphere, as well as the agent transference in Indochina.

There is, to be sure, an element of absurdity in the constant refrain that socialism equals Gulag, as revealed by events in the underdeveloped societies. A comparison of the problems facing such societies as Vietnam, Laos, Cambodia, Cuba, Mozambique, etc., with the situation in the industrial West would simply be ridiculed in societies that were not subjected to such effective ideological control as ours. But despite the inherent absurdity of attributing, say, revenge killings by Cambodian peasants who were bombed out of their homes by Western force to "Marxism" or "atheism," the practice is common and quite successful as a tactic in engineering consent to the priorities and structures of contemporary state capitalism.



In the United States, this tactic has become a virtual reflex. Bolshevik and later Stalinist crimes have regularly been exploited as a weapon against movements seeking reform or revolutionary change. During the Red Scare after World War I, which was quite effective in controlling labor militancy and eliminating radical intellectual currents, the Wall Street Journal wailed: "We talk of parlor Bolshevists, but what of those other Bolshevists, in the Cabinet, or at any rate near the throne?" Similar accusations, loosely associating reform Democrats with Stalinist crimes despite the eager and frightened collaboration of many liberals were common during the era mislabelled "McCarthyism." Harry Truman even denounced the civil rights movement of the 1950s as a Communist plot—conceding, in response to inquiry, that he had no proof, but explaining: "I know that usually when trouble hits the country the Kremlin is behind it."[^ch07-fn003] The 1970s campaign against "Big Government" (understood to cover health and welfare activities but not the police and military establishment) is likewise facilitated by a propaganda barrage carrying the implicit message that "socialism equals Gulag." In this context, too, it is an effective tactic to focus attention on real or invented atrocities committed in underdeveloped ex-colonies that use the phrase "socialism" in reference to their programs of mass mobilization under authoritarian state control to carry out industrialization and modernization.


One final factor merits a few words of comment. So-called "North-South conflicts" do not necessarily take the form of imperial intervention. At various levels and in a multitude of interactions there is a continuing struggle over access to resources, terms of trade, opportunities for international capital and other problems. A general public mood of hostility to the Third World is useful to the managers of the industrial democracies as they attempt to manipulate these conflicts to their benefit. In contrast, the sympathy towards Third World independence movements that developed during the post-World War II struggles for national liberation, brutally repressed primarily by France and the United States, is an impediment to the imposition of measures that will meet the requirements of the world’s wealthy industrial powers. In this context, it is useful to engender hatred, contempt and moralistic outrage directed against the nationalist movements of the Third World, particularly those that have recently escaped from the domination of the United States. It should hardly come as a surprise, therefore, that a major effort should be directed towards reversing the worldwide currents of sympathy towards the people of Indochina that were aroused by the assault of the U.S. war machine. That struggle came to be perceived as symbolic of the conflicts between the industrialized West and the former colonial domains, and it imposed barriers to the mobilization of public support for the traditional measures that may be required to preserve a favorable investment climate in the coming era.


These remarks bear directly on the framework of Western propaganda. They do not touch another and very different question: how should one evaluate the programs and character of the countries that have been liberated from Western domination, or respond to developments there? Our primary concern here has been U.S. global policy and propaganda, and the filtering and distorting effect of Western ideology, not the problems of reconstruction and modernization in societies that have been victimized by Western imperialism. Correspondingly, we have not developed or expressed our views here on the nature of the Indochinese regimes. To assess the contemporary situation in Indochina and the programs of the current ruling groups is a worthwhile endeavor, but it has not been our objective.

As for appropriate response, its central component in the current situation should be a committed and very substantial effort to help the victims, insofar as this is possible: those who are oppressed, those who have fled, those who are seeking to reconstruct some kind of viable existence from the wreckage. Such response is not to be discerned among the dominant classes and states of either East or West.


There is no single cause for the misery and oppression that we find in every part of the world. But there are some major causes, and some of these are close at hand and subject to our influence and, ultimately, our control. These factors and the social matrix in which they are embedded will engage the concern and efforts of people who are honestly committed to alleviate human suffering and to contribute to freedom and justice.


The success of the Free Press in reconstructing imperial ideology since the U.S. withdrawal from Indochina has been spectacular. The shift of the United States from causal agent to concerned bystander—and even to leader in the world struggle for human rights—in the face of its empire of client fascism and long, vicious assault on the peasant societies of Indochina, is a remarkable achievement. The system of brainwashing under freedom, with mass media voluntary self-censorship in accord with the larger interests of the state, has worked brilliantly. The new propaganda line has been established by endless repetition of the Big Distortions and negligible grant of access to non-establishment points of view; all rendered more effective by the illusion of equal access and the free flow of ideas. U.S. dissenters can produce their Samizdats freely, and stay out of jail, but they do not reach the general public or the Free Press except on an episodic basis. This reflects the power and interests that benefit from the uncontrolled arms race, the status quo of domestic economic arrangements, and the external system of multinational expansion and collaboration with the Shahs, Suhartos, Marcoses in the contemporary "development" and sacking of the Third World. Change will come only when material facts arouse sufficient numbers to force a reassessment of policy. At the present time, the machine expands, the mass media adapt to the political economy, and human rights are set aside except in rhetorical flourishes useful for ideological reconstruction.



[^ch07-fn001]: On these matters, see Alex Carey, “Reshaping the Truth: Pragmatists and Propagandists in America,” Meanjin Quarterly (Australia), vol. 35, no. 4, 1976; Carey and Truda Korber, Propaganda and Democracy in America, forthcoming.


[^ch07-fn002]: In particular, the singular failure of significant segments of the French intelligentsia to come to terms with the true nature of Stalinism and its roots in Leninist ideology and practice.


[^ch07-fn003]: See David Caute, The Great Fear, Simon & Schuster, 1978, pp. 19, 35.


